/// <reference types="node" />
import { webcrypto,createHash } from 'node:crypto';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {cleanup,render,screen,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {StrictMode} from 'react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {FinanceEvidenceAttachmentPanel} from './FinanceEvidenceAttachmentPanel';
import {prepareEvidenceFile,uploadFinanceEvidence,downloadFinanceEvidence} from './finance-evidence-api';
import {FINANCE_EVIDENCE_MAX_BYTES,type FinanceEvidenceMetadataDto} from './finance-evidence.types';
import {v2TestFixture,v2TestId} from './v2-test.fixture';
import type {FinanceV2Access} from './v2-ui.types';
const context={businessId:'evidence-business',userId:'evidence-owner',accessToken:'evidence-old-token'};
const access:FinanceV2Access={role:'OWNER',capabilities:['finance.evidence.read','finance.evidence.write'],availableSections:['expense-evidence']};
const metadata:FinanceEvidenceMetadataDto={id:v2TestId,businessId:context.businessId,expenseId:v2TestId,expenseVersion:2,filename:'Comprobante ñ.pdf',mimeType:'application/pdf',sizeBytes:3,sha256:createHash('sha256').update(new Uint8Array([1,2,3])).digest('hex'),recordedByUserId:context.userId,createdAt:'2026-10-05T12:00:00.000Z'};
const list={enabled:true,retention:'PRESERVE_WITHOUT_PURGE',fileSizeLimitBytes:FINANCE_EVIDENCE_MAX_BYTES,allowedMimeTypes:['application/pdf','image/jpeg','image/png'],files:[]};
const result={type:'UPLOAD_FINANCE_EVIDENCE',id:v2TestId,version:2,file:metadata};
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}});
const clients:QueryClient[]=[];
function mount(input={context,access,expenseId:v2TestId,expenseVersion:1 as number|undefined}){const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});clients.push(client);const wrap=(value:typeof input)=><QueryClientProvider client={client}><StrictMode><FinanceEvidenceAttachmentPanel {...value}/></StrictMode></QueryClientProvider>;return {...render(wrap(input)),update:wrap};}
async function fileBytes(file:Blob){return new Promise<number[]>((resolve)=>{const reader=new FileReader();reader.onload=()=>resolve(Array.from(new Uint8Array(reader.result as ArrayBuffer)));reader.readAsArrayBuffer(file);});}
beforeEach(()=>{vi.stubGlobal('crypto',webcrypto);});
afterEach(()=>{cleanup();clients.splice(0).forEach((client)=>client.clear());vi.restoreAllMocks();vi.unstubAllGlobals();});
it.each(['ADMIN','RECEPTIONIST','VIEWER'])('default-deny %s aunque reciba capabilities; no lee adjuntos',async(role)=>{vi.stubGlobal('fetch',vi.fn());mount({context,access:{...access,role},expenseId:v2TestId,expenseVersion:1});expect(screen.getByText(/Adjuntos no habilitados/)).toBeInTheDocument();expect(fetch).not.toHaveBeenCalled();});
it('provider deshabilitado conserva referencia textual y no ofrece una carga falsa',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(json({...list,enabled:false})));mount();await screen.findByText('Adjuntos no habilitados. La referencia textual del gasto sigue disponible.');expect(screen.queryByLabelText('Archivo del comprobante')).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Adjuntar comprobante'})).not.toBeInTheDocument();});
it.each([new File(['abc'],'sin-mime.pdf'),new File(['abc'],'no-permitido.txt',{type:'text/plain'}),new File([],'vacío.pdf',{type:'application/pdf'}),new File([new Uint8Array(FINANCE_EVIDENCE_MAX_BYTES+1)],'demasiado.pdf',{type:'application/pdf'})])('archivo sin MIME, MIME ajeno, vacío o mayor a2MiB falla antes de POST',async(file)=>{vi.stubGlobal('fetch',vi.fn());await expect(prepareEvidenceFile(file,v2TestId,1)).rejects.toBeInstanceOf(Error);expect(fetch).not.toHaveBeenCalled();});
it('carga perdida→GET500→desmontaje→401→token renovado repite los mismos bytes/payload/key una sola vez económica',async()=>{
  const facts=new Map<string,{bytes:number[];version:string}>();let posts=0;let failRead=false;const fetch=vi.fn(async(_url:string,request?:RequestInit)=>{if(request?.method!=='POST')return failRead?json({message:'Read failed'},500):json(list);const form=request.body as FormData;const key=new Headers(request.headers).get('Idempotency-Key')!;const bytes=await fileBytes(form.get('file') as File);const version=String(form.get('expectedVersion'));posts++;expect(new Headers(request.headers).has('Content-Type')).toBe(false);if(posts===1){facts.set(key,{bytes,version});throw new TypeError('Commit con respuesta perdida');}expect({bytes,version}).toEqual(facts.get(key));if(posts===2)return json({message:'Sesión vencida'},401);return json(result);});vi.stubGlobal('fetch',fetch);const user=userEvent.setup();const first=mount();await user.upload(await screen.findByLabelText('Archivo del comprobante'),new File([new Uint8Array([1,2,3])],'Comprobante ñ.pdf',{type:'application/pdf'}));await user.click(screen.getByRole('button',{name:'Adjuntar comprobante'}));await screen.findByText(/Carga pendiente de verificar/);failRead=true;first.unmount();const nextContext={...context,accessToken:'evidence-renewed-token'};const second=mount({context:nextContext,access,expenseId:v2TestId,expenseVersion:undefined});expect(posts).toBe(1);await screen.findByText(/Comprobante ñ.pdf/);await user.click(screen.getByRole('button',{name:'Reintentar la misma carga'}));await screen.findByText(/Tu sesión venció/);expect(posts).toBe(2);second.rerender(second.update({context:{...context,accessToken:'evidence-current-token'},access,expenseId:v2TestId,expenseVersion:2}));expect(posts).toBe(2);await user.click(screen.getByRole('button',{name:'Reintentar la misma carga'}));await screen.findByText('Comprobante adjunto conservado con su gasto y versión.');expect(facts.size).toBe(1);expect([...facts.values()]).toEqual([{bytes:[1,2,3],version:'1'}]);const requests=fetch.mock.calls.filter(([,request])=>request?.method==='POST');expect(requests).toHaveLength(3);expect(new Set(requests.map(([,request])=>new Headers(request!.headers).get('Idempotency-Key'))).size).toBe(1);expect(new Headers(requests[2][1]!.headers).get('Authorization')).toBe('Bearer evidence-current-token');
});
it('CAS409 permite consultar versión del gasto, conserva bytes y crea nueva intención explícita',async()=>{const expense={...v2TestFixture().references.report.expenses[0],id:v2TestId,version:3};let posts=0;const fetch=vi.fn(async(url:string,request?:RequestInit)=>request?.method==='POST'?(++posts===1?json({message:'Changed'},409):json({...result,version:4,file:{...metadata,expenseVersion:4}})):json(url.endsWith(`/expenses/${v2TestId}`)?{expense,audit:[]}:list));vi.stubGlobal('fetch',fetch);const user=userEvent.setup();mount();await user.upload(await screen.findByLabelText('Archivo del comprobante'),new File([new Uint8Array([1,2,3])],metadata.filename,{type:metadata.mimeType}));await user.click(screen.getByRole('button',{name:'Adjuntar comprobante'}));await user.click(await screen.findByRole('button',{name:'Consultar versión del gasto y conservar archivo'}));await screen.findByText(/Versión vigente consultada/);await user.click(screen.getByRole('button',{name:'Adjuntar comprobante'}));await screen.findByText(/Comprobante adjunto conservado/);const requests=fetch.mock.calls.filter(([,request])=>request?.method==='POST');expect((requests[1][1]!.body as FormData).get('expectedVersion')).toBe('3');expect(await fileBytes((requests[1][1]!.body as FormData).get('file') as File)).toEqual([1,2,3]);expect(new Set(requests.map(([,request])=>new Headers(request!.headers).get('Idempotency-Key'))).size).toBe(2);});
it('descarga usa API autenticada con token vigente, Blob y filename UTF8; no navega a una URL pública',async()=>{vi.stubGlobal('fetch',vi.fn(async(url:string,_request?:RequestInit)=>String(url).endsWith('/download')?new Response(new Uint8Array([1,2,3]),{headers:{'Content-Type':'application/pdf'}}):json({...list,files:[metadata]})));const create=vi.fn().mockReturnValue('blob:private-owned-file');vi.spyOn(URL,'createObjectURL').mockImplementation(create);vi.spyOn(URL,'revokeObjectURL').mockImplementation(()=>undefined);let filename='';vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(function(this:HTMLAnchorElement){filename=this.download;expect(this.href).toBe('blob:private-owned-file');});const user=userEvent.setup();mount({context:{...context,accessToken:'evidence-current-token'},access,expenseId:v2TestId,expenseVersion:2});await user.click(await screen.findByRole('button',{name:`Descargar ${metadata.filename}`}));await waitFor(()=>expect(create).toHaveBeenCalledOnce());expect(filename).toBe(metadata.filename);const request=vi.mocked(fetch).mock.calls.find(([url])=>String(url).endsWith('/download'))!;expect(new Headers(request[1]!.headers).get('Authorization')).toBe('Bearer evidence-current-token');expect(String(request[0])).toContain(`/finance/evidence/${v2TestId}/download`);});
it('éxito vacío o metadata de otro negocio no acredita carga;403/503 conservan el tipo de error',async()=>{const command=await prepareEvidenceFile(new File([new Uint8Array([1,2,3])],metadata.filename,{type:metadata.mimeType}),v2TestId,1);const fetch=vi.fn().mockResolvedValueOnce(new Response('{}')).mockResolvedValueOnce(json({...result,file:{...metadata,businessId:'foreign'}})).mockResolvedValueOnce(json({message:'Denied'},403)).mockResolvedValueOnce(json({message:'Provider unavailable'},503));vi.stubGlobal('fetch',fetch);await expect(uploadFinanceEvidence(context,command,'same-key')).rejects.toMatchObject({name:'ApiResponseError'});await expect(uploadFinanceEvidence(context,command,'same-key')).rejects.toMatchObject({name:'ApiResponseError'});await expect(uploadFinanceEvidence(context,command,'same-key')).rejects.toMatchObject({status:403});await expect(uploadFinanceEvidence(context,command,'same-key')).rejects.toMatchObject({status:503});});
it('download rechaza metadata ajena sin hacer un request',async()=>{vi.stubGlobal('fetch',vi.fn());await expect(downloadFinanceEvidence(context,{...metadata,businessId:'foreign'})).rejects.toMatchObject({name:'ApiResponseError'});expect(fetch).not.toHaveBeenCalled();});
