import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {act,cleanup,render,screen,waitFor,within} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {StrictMode} from 'react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {FinanceV2Workspace} from './FinanceV2Workspace';
import {v2TestFixture,v2TestId} from './v2-test.fixture';
import type {FinanceV2WorkspaceProps} from './v2-ui.types';
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}});
const clients:QueryClient[]=[];
function props():FinanceV2WorkspaceProps{return {context:{businessId:'synthetic-a',userId:'owner-a',accessToken:'synthetic-token'},businessName:'Posada sintética',view:'planning',access:{role:'OWNER',capabilities:['finance.read','finance.write','finance.import'],availableSections:['commands']},references:v2TestFixture().references,period:{from:'2026-09-01',to:'2026-10-01'}};}
function mount(input=props()){const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});clients.push(client);const wrap=(value:FinanceV2WorkspaceProps)=><QueryClientProvider client={client}><StrictMode><FinanceV2Workspace {...value}/></StrictMode></QueryClientProvider>;return {client,...render(wrap(input)),update:(value:FinanceV2WorkspaceProps)=>wrap(value)};}
beforeEach(()=>vi.stubGlobal('fetch',vi.fn().mockImplementation(async(_url,request)=>request?.method==='POST'?json({id:v2TestId,version:1,type:JSON.parse(request.body as string).type}):json({items:[],nextCursor:null}))));
afterEach(()=>{cleanup();clients.splice(0).forEach((client)=>client.clear());vi.unstubAllGlobals();});
it.each(['ADMIN','RECEPTIONIST','VIEWER'])('default-deny para %s aunque se suministren capabilities; no solicita salarios ni fuentes',async(role)=>{const input=props();input.access={role,capabilities:['finance.read','finance.write','finance.labor'],availableSections:['commands','labor-costs','drafts']};mount(input);expect(screen.getByRole('alert')).toHaveTextContent('No tienes permiso');expect(fetch).not.toHaveBeenCalled();});
it('OWNER sin finance.labor no consulta datos privados de personal',()=>{const input=props();input.view='results';input.access.availableSections=['commands','labor-costs'];mount(input);expect(screen.queryByRole('button',{name:'Registrar costo de personal o trabajo propio'})).not.toBeInTheDocument();expect(fetch).not.toHaveBeenCalled();});
it('borrador PYG900000 usa campos operativos, referencia nula y Resource histórico; StrictMode admite el resultado',async()=>{const user=userEvent.setup();mount();await user.click(screen.getByRole('button',{name:'Crear borrador de gasto'}));const dialog=screen.getByRole('dialog',{name:'Crear borrador de gasto'});await user.type(within(dialog).getByLabelText('Descripción del gasto'),'Reparación QA');await user.type(within(dialog).getByRole('textbox',{name:'Total del documento, guaraníes PYG'}),'900.000');await user.type(within(dialog).getByLabelText('Concepto'),'Trabajo');await user.type(within(dialog).getByRole('textbox',{name:'Importe de la línea, guaraníes PYG'}),'900.000');await user.selectOptions(within(dialog).getByLabelText('Categoría'),'category-a');await user.click(within(dialog).getByRole('button',{name:'Registrar'}));await screen.findByText('Registro guardado.');const call=vi.mocked(fetch).mock.calls.find(([,request])=>request?.method==='POST')!;expect(JSON.parse(call[1]!.body as string)).toMatchObject({type:'CREATE_EXPENSE_DRAFT',expenseDefinition:{amountMinor:900000,counterpartyId:null,reference:null,lines:[{amountMinor:900000,resourceId:null,bookingId:null}]}});expect(String(call[0])).toContain('/finance/v2/commands');expect(new Headers(call[1]!.headers).get('Idempotency-Key')).toMatch(/^[0-9a-f-]{36}$/i);});
it('commit con respuesta perdida, GET fallido, Escape/reapertura y401 conservan la misma intención al renovar sesión',async()=>{
  const fixture=v2TestFixture();const facts=new Map<string,string>();let postCount=0;let failRead=false;
  vi.mocked(fetch).mockImplementation(async(_url,request)=>{if(request?.method!=='POST')return failRead?json({message:'Lectura fallida'},500):json({items:fixture.data.drafts,nextCursor:null});const key=new Headers(request.headers).get('Idempotency-Key')!;postCount++;if(postCount===1){facts.set(key,request.body as string);throw new TypeError('Commit hecho, respuesta perdida');}if(postCount===2)return json({message:'Sesión vencida'},401);expect(request.body).toBe(facts.get(key));return json({id:v2TestId,version:1,type:'CREATE_EXPENSE_TEMPLATE'});});
  const input=props();input.access.availableSections=[...input.access.availableSections,'drafts'];const user=userEvent.setup();const view=mount(input);await screen.findByText('Reparación sintética');await user.click(screen.getByRole('button',{name:'Crear plantilla de gasto'}));let dialog=screen.getByRole('dialog');await user.type(within(dialog).getByLabelText('Nombre'),'Plantilla QA');await user.type(within(dialog).getByLabelText('Descripción del gasto'),'Costo QA');await user.type(within(dialog).getByRole('textbox',{name:'Total del documento, guaraníes PYG'}),'450000');await user.type(within(dialog).getByLabelText('Concepto'),'Concepto');await user.type(within(dialog).getByRole('textbox',{name:'Importe de la línea, guaraníes PYG'}),'450000');await user.selectOptions(within(dialog).getByLabelText('Categoría'),'category-a');await user.click(within(dialog).getByRole('button',{name:'Registrar'}));await within(dialog).findByText('Resultado pendiente de verificar');failRead=true;await act(async()=>{await view.client.invalidateQueries({queryKey:['finance','owner-a','synthetic-a','v2','drafts']});});await waitFor(()=>expect(document.querySelector('.finance-state--error')).toBeInTheDocument());expect(screen.getByRole('dialog')).toBe(dialog);await user.keyboard('{Escape}');await user.click(screen.getByRole('button',{name:'Recuperar registro pendiente'}));dialog=screen.getByRole('dialog');expect(within(dialog).getByLabelText('Nombre')).toHaveValue('Plantilla QA');await user.click(within(dialog).getByRole('button',{name:'Reintentar el mismo registro'}));await within(dialog).findByText(/Tu sesión venció/);expect(within(dialog).getByLabelText('Nombre')).toBeDisabled();view.rerender(view.update({...input,context:{...input.context,accessToken:'renewed-synthetic-token'}}));expect(postCount).toBe(2);await user.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Reintentar el mismo registro'}));
  await screen.findByText('Registro guardado.');const calls=vi.mocked(fetch).mock.calls.filter(([,request])=>request?.method==='POST');expect(calls).toHaveLength(3);expect(facts.size).toBe(1);expect(new Set(calls.map(([,request])=>new Headers(request!.headers).get('Idempotency-Key'))).size).toBe(1);expect(new Headers(calls[2][1]!.headers).get('Authorization')).toBe('Bearer renewed-synthetic-token');
});
it('CSV con errores conserva vista previa por fila y no permite confirmar historia',async()=>{const user=userEvent.setup();const input=props();input.access.availableSections=[...input.access.availableSections,'history-preview'];vi.mocked(fetch).mockResolvedValue(json({statusCode:400,error:'Bad Request',message:'El CSV contiene errores.',previewToken:null,issues:[{ordinal:3,column:'amountMinor',code:'INVALID_INPUT',message:'Importe inválido'}]},400));mount(input);await user.click(screen.getByRole('button',{name:'Importar historia propia'}));const dialog=screen.getByRole('dialog');await user.type(within(dialog).getByLabelText('Origen identificado del archivo'),'history-qa');await user.type(within(dialog).getByLabelText('Contenido CSV'),'csv-synthetic');await user.type(within(dialog).getByLabelText('Motivo'),'Historia sintética');await user.click(within(dialog).getByRole('button',{name:'Consultar vista previa'}));expect(await within(dialog).findByText('Fila 3, amountMinor: Importe inválido')).toBeVisible();expect(within(dialog).getByRole('button',{name:'Registrar'})).toBeDisabled();expect(vi.mocked(fetch).mock.calls.every(([url])=>!String(url).includes('/commands'))).toBe(true);});
it('conserva texto al cerrar, cambiar formulario y reabrir con catálogos actuales antes de enviar',async()=>{
  const input=props();const user=userEvent.setup();const view=mount(input);await user.click(screen.getByRole('button',{name:'Crear borrador de gasto'}));await user.type(within(screen.getByRole('dialog')).getByLabelText('Descripción del gasto'),'Borrador sin enviar');await user.keyboard('{Escape}');await user.click(screen.getByRole('button',{name:'Crear plantilla de gasto'}));await user.type(within(screen.getByRole('dialog')).getByLabelText('Nombre'),'Otra plantilla');await user.keyboard('{Escape}');
  const next=structuredClone(input);next.references.report.catalogs.push({...next.references.report.catalogs[0],id:'category-new',name:'Categoría recién creada'});view.rerender(view.update(next));await user.click(screen.getByRole('button',{name:'Crear borrador de gasto'}));const dialog=screen.getByRole('dialog');expect(within(dialog).getByLabelText('Descripción del gasto')).toHaveValue('Borrador sin enviar');await user.selectOptions(within(dialog).getByLabelText('Categoría'),'category-new');expect(within(dialog).getByLabelText('Categoría')).toHaveValue('category-new');expect(fetch).not.toHaveBeenCalled();
});
it('remontaje completo recupera contenido y clave originales sin crear otro hecho económico',async()=>{
  const input=props();input.context.userId='owner-remount';const facts=new Map<string,string>();let count=0;vi.mocked(fetch).mockImplementation(async(_url,request)=>{if(request?.method!=='POST')return json({items:[],nextCursor:null});const key=new Headers(request.headers).get('Idempotency-Key')!;count++;if(count===1){facts.set(key,request.body as string);throw new TypeError('Respuesta perdida después del commit');}expect(request.body).toBe(facts.get(key));if(count===2)return json({message:'Sesión vencida'},401);return json({id:v2TestId,version:1,type:'CREATE_EXPENSE_TEMPLATE'});});const user=userEvent.setup();const first=mount(input);await user.click(screen.getByRole('button',{name:'Crear plantilla de gasto'}));const dialog=screen.getByRole('dialog');await user.type(within(dialog).getByLabelText('Nombre'),'Plantilla remontada');await user.type(within(dialog).getByLabelText('Descripción del gasto'),'Gasto original');await user.type(within(dialog).getByRole('textbox',{name:'Total del documento, guaraníes PYG'}),'450000');await user.type(within(dialog).getByLabelText('Concepto'),'Concepto');await user.type(within(dialog).getByRole('textbox',{name:'Importe de la línea, guaraníes PYG'}),'450000');await user.selectOptions(within(dialog).getByLabelText('Categoría'),'category-a');await user.click(within(dialog).getByRole('button',{name:'Registrar'}));await within(dialog).findByText('Resultado pendiente de verificar');first.unmount();
  const second=mount({...input,context:{...input.context,accessToken:'renewed-remount-token'}});expect(count).toBe(1);await user.click(screen.getByRole('button',{name:'Recuperar registro pendiente'}));const recovery=screen.getByRole('dialog');expect(within(recovery).getByText('Gasto original')).toBeInTheDocument();await user.click(within(recovery).getByRole('button',{name:'Reintentar el mismo registro'}));await within(recovery).findByText(/Tu sesión venció/);await user.keyboard('{Escape}');await user.click(screen.getByRole('button',{name:'Recuperar registro pendiente'}));expect(count).toBe(2);second.rerender(second.update({...input,context:{...input.context,accessToken:'latest-remount-token'}}));await user.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Reintentar el mismo registro'}));await screen.findByText('Registro guardado.');const posts=vi.mocked(fetch).mock.calls.filter(([,request])=>request?.method==='POST');expect(posts).toHaveLength(3);expect(facts.size).toBe(1);expect(new Set(posts.map(([,request])=>new Headers(request!.headers).get('Idempotency-Key'))).size).toBe(1);expect(new Headers(posts[2][1]!.headers).get('Authorization')).toBe('Bearer latest-remount-token');
});
it('mantiene el workspace montado pero no solicita secciones mientras una vista V1 está activa',()=>{const input=props();input.active=false;input.access.availableSections=['drafts','templates','approval-policy','periods','corrections','recognition-sources','aging'];mount(input);expect(fetch).not.toHaveBeenCalled();});

it.each(['history', 'bank'] as const)('CSV %s HTTP400 conserva fila y error global, texto editable y confirmación deshabilitada', async (kind) => {
  const input = props(); input.view = kind === 'history' ? 'planning' : 'reconciliation'; input.access.availableSections = [...input.access.availableSections, kind === 'history' ? 'history-preview' : 'bank-preview']; input.references.report.accounts[0].kind = 'BANK';
  const issues = [{ ordinal: 0, column: '', code: 'INVALID_INPUT', message: 'Cabecera inválida' }, { ordinal: 3, column: 'amountMinor', code: 'MONEY_OVERFLOW', message: 'Importe fuera del límite' }];
  vi.mocked(fetch).mockResolvedValue(json({ statusCode: 400, error: 'Bad Request', message: 'El CSV contiene errores.', previewToken: null, issues }, 400));
  const user = userEvent.setup(); mount(input); await user.click(screen.getByRole('button', { name: kind === 'history' ? 'Importar historia propia' : 'Importar extracto manual' }));
  const dialog = screen.getByRole('dialog'); if (kind === 'bank') await user.selectOptions(within(dialog).getByLabelText('Cuenta bancaria'), 'account-a');
  await user.type(within(dialog).getByLabelText('Origen identificado del archivo'), 'history-qa'); await user.type(within(dialog).getByLabelText('Contenido CSV'), 'CSV incorrecto'); await user.type(within(dialog).getByLabelText('Motivo'), 'Conservar motivo');
  await user.click(within(dialog).getByRole('button', { name: 'Consultar vista previa' }));
  expect(await within(dialog).findByText('Archivo: Cabecera inválida')).toBeVisible(); expect(within(dialog).getByText('Fila 3, amountMinor: Importe fuera del límite')).toBeVisible();
  expect(within(dialog).getByLabelText('Contenido CSV')).toHaveValue('CSV incorrecto'); expect(within(dialog).getByLabelText('Contenido CSV')).toBeEnabled(); expect(within(dialog).getByLabelText('Motivo')).toHaveValue('Conservar motivo');
  expect(within(dialog).getByRole('button', { name: 'Registrar' })).toBeDisabled(); expect(within(dialog).queryByText('Vista previa del servidor')).not.toBeInTheDocument();
  expect(vi.mocked(fetch).mock.calls).toHaveLength(1); expect(vi.mocked(fetch).mock.calls.every(([url]) => !String(url).includes('/commands'))).toBe(true);
  await user.keyboard('{Escape}'); await user.click(screen.getByRole('button', { name: kind === 'history' ? 'Importar historia propia' : 'Importar extracto manual' }));
  expect(within(screen.getByRole('dialog')).getByLabelText('Contenido CSV')).toHaveValue('CSV incorrecto'); expect(within(screen.getByRole('dialog')).getByRole('button', { name: 'Registrar' })).toBeDisabled();
});

it.each([400, 500])('preview válido seguido por HTTP%s pierde sólo la autorización del preview; CSV y motivo se conservan', async (status) => {
  const input = props(); input.access.availableSections = [...input.access.availableSections, 'history-preview'];
  const valid = { businessId: 'synthetic-a', sourceNamespace: 'history-qa', digest: 'server-digest', previewToken: 'server-preview-token', issues: [], sources: [], totals: { expenseMinor: 900000, settlementMinor: 0, includedCashMinor: 0, excludedCashMinor: 0 } };
  const invalid = { statusCode: 400, error: 'Bad Request', message: 'El CSV contiene errores.', previewToken: null, issues: [{ ordinal: 2, column: 'amountMinor', code: 'INVALID_INPUT', message: 'Importe inválido' }] };
  vi.mocked(fetch).mockResolvedValueOnce(json(valid)).mockResolvedValueOnce(json(invalid, status)).mockResolvedValueOnce(json(valid));
  const user = userEvent.setup(); mount(input); await user.click(screen.getByRole('button', { name: 'Importar historia propia' })); const dialog = screen.getByRole('dialog');
  await user.type(within(dialog).getByLabelText('Origen identificado del archivo'), 'history-qa'); await user.type(within(dialog).getByLabelText('Contenido CSV'), 'Mismo CSV'); await user.type(within(dialog).getByLabelText('Motivo'), 'Motivo conservado');
  await user.click(within(dialog).getByRole('button', { name: 'Consultar vista previa' })); await waitFor(() => expect(within(dialog).getByRole('button', { name: 'Registrar' })).toBeEnabled());
  await user.click(within(dialog).getByRole('button', { name: 'Consultar vista previa' })); await waitFor(() => expect(within(dialog).getByRole('button', { name: 'Consultar vista previa' })).toBeEnabled());
  expect(within(dialog).getByRole('button', { name: 'Registrar' })).toBeDisabled(); expect(within(dialog).queryByText('Vista previa del servidor')).not.toBeInTheDocument(); expect(within(dialog).getByLabelText('Contenido CSV')).toHaveValue('Mismo CSV'); expect(within(dialog).getByLabelText('Motivo')).toHaveValue('Motivo conservado');
  if (status === 500) expect(within(dialog).queryByLabelText('Errores del archivo CSV')).not.toBeInTheDocument();
  expect(vi.mocked(fetch).mock.calls).toHaveLength(2); expect(vi.mocked(fetch).mock.calls.every(([url]) => !String(url).includes('/commands'))).toBe(true);
  await user.click(within(dialog).getByRole('button', { name: 'Consultar vista previa' })); await waitFor(() => expect(within(dialog).getByRole('button', { name: 'Registrar' })).toBeEnabled()); expect(vi.mocked(fetch).mock.calls).toHaveLength(3);
});
