import { useQuery } from '@tanstack/react-query';
import { useEffect, useRef, useState } from 'react';
import { X } from 'lucide-react';
import { ApiError } from '../../../shared/api/api-client';
import { Button } from '../../../shared/ui/Button';
import { Input } from '../../../shared/ui/Input';
import { OverlayPanel } from '../../../shared/ui/OverlayPanel';
import { formatMoney } from '../../../shared/utils/money';
import { formatBusinessInstant } from '../../../shared/utils/date-format';
import type { FinanceContext } from '../api/finance-api';
import { AccountField, MoneyField } from '../components/FinanceFields';
import { FinanceError, financeErrorMessage } from '../components/FinanceFeedback';
import type { FinanceCorrectionBooking, FinanceEffectiveAmounts } from './finance-corrections.types';
import { executeFinanceCorrection, getFinanceCorrections, type FinanceCorrectionCommand, type FinanceCorrectionResult } from './finance-corrections-api';
import { useFinanceIntent } from './use-finance-intent';
import { financeV2Key } from './use-v2-command';
import { canFinanceV2, sectionReady, type FinanceV2Access, type FinanceV2References } from './v2-ui.types';
import { v2Instant, v2Money } from './v2-form';

const labels = { VOID_PAYMENT: 'Anular cobro erróneo', REFUND_PAYMENT: 'Registrar devolución externa', SET_TERMINAL_FINAL_AMOUNT: 'Fijar importe final de cancelación' } as const;
type Form = { type: FinanceCorrectionCommand['type']; booking: FinanceCorrectionBooking; paymentId: string; amount: string; occurredAt: string; accountId: string; reference: string; reason: string; references: FinanceV2References };
function Amounts({ amounts }: { amounts: FinanceEffectiveAmounts }) { return <dl className="finance-v2-amounts"><dt>Original registrado</dt><dd>{formatMoney(amounts.grossRecordedAmountMinor)}</dd><dt>Anulado</dt><dd>{formatMoney(amounts.voidedAmountMinor)}</dd><dt>Devuelto</dt><dd>{formatMoney(amounts.refundedAmountMinor)}</dd><dt>Neto retenido</dt><dd>{formatMoney(amounts.netRetainedAmountMinor)}</dd></dl>; }
export function buildCorrection(form: Form): FinanceCorrectionCommand {
  const common = { bookingId: form.booking.bookingId, expectedBookingUpdatedAt: form.booking.bookingUpdatedAt, currentPricingId: form.booking.pricing.currentPricingId, expectedFinancialVersion: form.booking.financialVersion, reason: form.reason.trim() };
  if (form.type === 'SET_TERMINAL_FINAL_AMOUNT') return { ...common, type: form.type, finalAmountMinor: v2Money(form.amount, true) };
  const payment = form.booking.payments.find((item) => item.id === form.paymentId); if (!payment) throw new Error('Elige un cobro de la reserva consultada.');
  const adjustment = { ...common, paymentId: payment.id, expectedPaymentVersion: payment.paymentVersion };
  if (form.type === 'VOID_PAYMENT') return { ...adjustment, type: form.type };
  const account = form.references.report.accounts.find((item) => item.id === form.accountId && !item.archived); if (!account) throw new Error('Elige la cuenta de la devolución realizada.');
  return { ...adjustment, type: form.type, amountMinor: v2Money(form.amount), occurredAt: v2Instant(form.occurredAt), accountId: account.id, expectedAccountVersion: account.version, reference: form.reference.trim() || null };
}
export function FinanceCorrections({ context, access, references, active }: { context: FinanceContext; access: FinanceV2Access; references: FinanceV2References; active: boolean }) {
  const query = useQuery({ queryKey: [...financeV2Key(context), 'corrections'], queryFn: ({ signal }) => getFinanceCorrections(context, signal), enabled: active && canFinanceV2(access, 'finance.read') && sectionReady(access, 'corrections'), retry: false });
  const intent = useFinanceIntent(context, 'corrections', executeFinanceCorrection); const trigger = useRef<HTMLElement | null>(null);
  const [form, setForm] = useState<Form | null>(null); const [open, setOpen] = useState(false); const [error, setError] = useState<unknown>(null); const [notice, setNotice] = useState(''); const [saved, setSaved] = useState<FinanceCorrectionResult | null>(null);
  const alive = useRef(true); useEffect(() => { alive.current = true; return () => { alive.current = false; }; }, []);
  const capability = (type: Form['type']) => type === 'VOID_PAYMENT' ? 'payment.void' : type === 'REFUND_PAYMENT' ? 'payment.refund' : 'pricing.final-amount';
  function begin(type: Form['type'], booking: FinanceCorrectionBooking, paymentId: string, element: HTMLElement) { trigger.current = element; if (!intent.hasUncertainResult) setForm({ type, booking, paymentId, amount: '', occurredAt: new Date().toISOString().slice(0, 16), accountId: booking.payments.find((payment) => payment.id === paymentId)?.accountLink?.accountId ?? '', reference: '', reason: '', references }); setError(null); setOpen(true); }
  async function submit(retry = false) { setError(null); try { const result = await (retry ? intent.retry() : intent.execute(buildCorrection(form!))); if (alive.current) { setSaved(result); setForm(null); setOpen(false); setNotice('Corrección registrada. El original y su historial se conservan.'); } } catch (failure) { if (alive.current) setError(failure); } }
  async function refresh() { setError(null); try { const latest = await getFinanceCorrections(context); const booking = latest.bookings.find((item) => item.bookingId === form?.booking.bookingId); if (!booking || (form?.paymentId && !booking.payments.some((payment) => payment.id === form.paymentId))) throw new Error('La reserva o el cobro ya no está disponible en esta lectura. Conserva el borrador.'); if (alive.current) { setForm((current) => current ? { ...current, booking, references } : null); setNotice('Versión actual consultada. Revisa el borrador antes de registrar una nueva intención.'); } } catch (failure) { if (alive.current) setError(failure); } }
  const uncertain = intent.hasUncertainResult; const conflict = error instanceof ApiError && error.status === 409; const busy = intent.isPending || uncertain;
  return <><section hidden={!active} className="finance-panel" aria-label="Correcciones de cobros"><header><h3>Cobros, devoluciones e importe final</h3></header><p className="finance-help">TOP registra la devolución realizada fuera del sistema. El historial no reabre la reserva y conserva el cobro original.</p>
    {!sectionReady(access, 'corrections') ? <p>La consulta de correcciones todavía no está disponible.</p> : query.isLoading ? <p role="status">Consultando cobros originales.</p> : query.isError ? <FinanceError error={query.error} onRetry={() => { void query.refetch(); }} /> : null}
    {notice ? <p role="status">{notice}</p> : null}{saved ? <Amounts amounts={saved.amounts} /> : null}
    {uncertain && !open ? <Button type="button" onClick={(event) => { trigger.current = event.currentTarget; setOpen(true); }}>Recuperar corrección pendiente</Button> : null}
    <div className="finance-v2-list">{query.data?.bookings.map((booking) => <article key={booking.bookingId}><h4>{booking.label}</h4><p>{booking.status} · Exigible {formatMoney(booking.pricing.totalAmountMinor)} · pendiente {formatMoney(booking.outstandingMinor)} · crédito {formatMoney(booking.creditMinor)}</p><Amounts amounts={booking.amounts} />{booking.needsReconciliation ? <p className="finance-warning">Requiere reconciliación de sus aplicaciones. Revisa el origen.</p> : null}{booking.warnings.map((warning) => <p key={warning}>{warning}</p>)}
      {booking.payments.map((payment) => <section key={payment.id}><h5>Cobro del {formatBusinessInstant(payment.paidAt, references.report.timeZone)}</h5><Amounts amounts={payment} /><p>{payment.effectiveStatus} · disponible para devolución {formatMoney(payment.refundAvailableMinor)}</p><div className="finance-actions">{canFinanceV2(access, 'payment.void') && query.data?.capabilities.voidPayment ? <Button type="button" variant="secondary" disabled={!payment.voidAllowed || !sectionReady(access, 'payment-adjustments') || intent.isPending} onClick={(event) => begin('VOID_PAYMENT', booking, payment.id, event.currentTarget)}>Anular cobro erróneo</Button> : null}{canFinanceV2(access, 'payment.refund') && query.data?.capabilities.refundPayment ? <Button type="button" variant="secondary" disabled={payment.refundAvailableMinor <= 0 || !sectionReady(access, 'payment-adjustments') || intent.isPending} onClick={(event) => begin('REFUND_PAYMENT', booking, payment.id, event.currentTarget)}>Registrar devolución externa</Button> : null}</div></section>)}
      {canFinanceV2(access, 'pricing.final-amount') && query.data?.capabilities.terminalFinalAmount ? <Button type="button" variant="secondary" disabled={!booking.canSetTerminalFinalAmount || !sectionReady(access, 'terminal-pricing') || intent.isPending} onClick={(event) => begin('SET_TERMINAL_FINAL_AMOUNT', booking, '', event.currentTarget)}>Fijar importe final de cancelación</Button> : null}</article>)}</div></section>
    {open && (form || intent.pendingCommand) ? <OverlayPanel open portal closeLabel="Cerrar formulario" label={labels[form?.type ?? intent.pendingCommand!.type]} className="finance-dialog" layerClassName="finance-dialog-layer" triggerRef={trigger} dismissible={!intent.isPending} onClose={() => setOpen(false)}><header><h2>{labels[form?.type ?? intent.pendingCommand!.type]}</h2><Button type="button" iconOnly variant="ghost" aria-label="Cerrar corrección" disabled={intent.isPending} onClick={() => setOpen(false)}><X size={20} aria-hidden="true" /></Button></header><form onSubmit={(event) => { event.preventDefault(); void submit(); }}>
      {form ? <fieldset disabled={busy} className="finance-form-body"><p>{form.booking.label} · {form.booking.status}</p><Amounts amounts={form.booking.amounts} />{form.type !== 'VOID_PAYMENT' ? <MoneyField id="correction-amount" label={form.type === 'REFUND_PAYMENT' ? 'Importe devuelto' : 'Importe final exigible'} value={form.amount} onChange={(amount) => setForm({ ...form, amount })} /> : <p>El reverso conserva el cobro y añade un evento con motivo. No registra una salida bancaria.</p>}{form.type === 'REFUND_PAYMENT' ? <><AccountField id="correction-account" accounts={form.references.report.accounts} value={form.accountId} onChange={(accountId) => setForm({ ...form, accountId })} /><Input id="correction-occurred-at" label="Fecha y hora de devolución (UTC)" type="datetime-local" required value={form.occurredAt} onChange={(event) => setForm({ ...form, occurredAt: event.target.value })} /><Input id="correction-reference" label="Referencia externa (opcional)" maxLength={120} value={form.reference} onChange={(event) => setForm({ ...form, reference: event.target.value })} /></> : null}<Input id="correction-reason" label="Motivo" minLength={2} maxLength={500} required value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} /></fieldset> : <p className="finance-form-body">Recupera la intención pendiente de esta identidad y negocio. Conserva la clave y todos sus datos originales.</p>}
      {error ? <p role="alert" className="finance-form-error">{financeErrorMessage(error)}</p> : null}{uncertain ? <p role="status" className="finance-form-error">Resultado pendiente de verificar. El reintento conserva el registro original.</p> : null}<footer><Button type="button" variant="secondary" disabled={intent.isPending} onClick={() => setOpen(false)}>Cerrar y conservar borrador</Button>{uncertain ? <Button type="button" loading={intent.isPending} disabled={!canFinanceV2(access,capability(form?.type??intent.pendingCommand!.type))} onClick={() => { void submit(true); }}>Reintentar el mismo registro</Button> : conflict ? <Button type="button" onClick={() => { void refresh(); }}>Consultar versión actual</Button> : <Button type="submit" loading={intent.isPending} disabled={!form || !canFinanceV2(access, capability(form.type))}>Registrar</Button>}</footer></form></OverlayPanel> : null}</>;
}
