import { useQuery } from '@tanstack/react-query';
import { useEffect, useRef, useState } from 'react';
import { Download, X } from 'lucide-react';
import { ApiError } from '../../../shared/api/api-client';
import { Button } from '../../../shared/ui/Button';
import { Input } from '../../../shared/ui/Input';
import { OverlayPanel } from '../../../shared/ui/OverlayPanel';
import { formatBusinessInstant, formatPureDate } from '../../../shared/utils/date-format';
import type { FinanceContext } from '../api/finance-api';
import { FinanceError, financeErrorMessage } from '../components/FinanceFeedback';
import type { FinanceCloseSnapshot, FinanceCloseSources, FinancePeriod } from './finance-close.types';
import { closeAcknowledgementKeys, executeFinanceClose, getFinanceClosePackage, getFinanceCloseSnapshot, getFinancePeriods, prepareFinanceClose, type CloseAcknowledgementKey, type FinanceCloseRequest } from './finance-close-api';
import { useFinanceIntent } from './use-finance-intent';
import { financeV2Key } from './use-v2-command';
import { canFinanceV2, sectionReady, type FinanceV2Access } from './v2-ui.types';

const checklistLabels: Record<string, string> = { SOURCES_COMPLETE: 'Integridad de todas las fuentes y sus bloqueos', RECOGNITION_COVERAGE: 'Cobertura del ingreso certificado', ACCOUNT_OPENINGS: 'Aperturas de cuentas', EVIDENCE: 'Evidencia de gastos', MOVEMENT_REVIEW: 'Revisión de movimientos', CASH_COUNTS: 'Arqueos y diferencias de caja' };
const operationLabels = { CREATE_PERIOD: 'Crear período financiero', CLOSE_PERIOD: 'Cerrar período financiero', REOPEN_PERIOD: 'Reabrir período financiero' } as const;
interface CloseForm { operation: FinanceCloseRequest['operation']; period: FinancePeriod | null; sources: FinanceCloseSources | null; from: string; to: string; reason: string; acknowledgements: Partial<Record<CloseAcknowledgementKey, string>> }
function needsAcknowledgements(sources: FinanceCloseSources | null) { return sources?.checklist.filter((item) => !item.passed && item.severity === 'EXCEPTION') ?? []; }
export function buildCloseRequest(form: CloseForm): FinanceCloseRequest {
  if (form.operation === 'CREATE_PERIOD') return { operation: form.operation, command: { from: form.from, to: form.to, reason: form.reason.trim() } };
  if (!form.period) throw new Error('Selecciona un período del negocio activo.');
  if (form.operation === 'REOPEN_PERIOD') return { operation: form.operation, periodId: form.period.id, command: { expectedVersion: form.period.version, reason: form.reason.trim() } };
  if (!form.sources || form.sources.from !== form.period.from || form.sources.to !== form.period.to || form.sources.checklist.some((item) => !item.passed && item.severity === 'BLOCKER')) throw new Error('Consulta el checklist y resuelve los bloqueos antes de cerrar.');
  for (const item of needsAcknowledgements(form.sources)) if (!closeAcknowledgementKeys.includes(item.key as CloseAcknowledgementKey) || !(form.acknowledgements[item.key as CloseAcknowledgementKey]?.trim().length ?? 0)) throw new Error('Declara un motivo para cada excepción antes de cerrar.');
  return { operation: form.operation, periodId: form.period.id, command: { expectedVersion: form.period.version, expectedSourceToken: form.sources.sourceToken, reason: form.reason.trim(), acknowledgements: Object.fromEntries(Object.entries(form.acknowledgements).map(([key, value]) => [key, value.trim()])) } };
}
export function FinanceClose({ context, access, active, period }: { context: FinanceContext; access: FinanceV2Access; active: boolean; period: { from: string; to: string } }) {
  const query = useQuery({ queryKey: [...financeV2Key(context), 'periods'], queryFn: ({ signal }) => getFinancePeriods(context, signal), enabled: active && canFinanceV2(access, 'finance.read') && sectionReady(access, 'periods'), retry: false });
  const intent = useFinanceIntent(context, 'period-close', executeFinanceClose); const trigger = useRef<HTMLElement | null>(null);
  const [form, setForm] = useState<CloseForm | null>(null); const [open, setOpen] = useState(false); const [error, setError] = useState<unknown>(null); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false); const [snapshot, setSnapshot] = useState<FinanceCloseSnapshot | null>(null);
  const alive = useRef(true); const controller = useRef<AbortController | null>(null); useEffect(() => { alive.current = true; return () => { alive.current = false; controller.current?.abort(); }; }, []);
  async function begin(operation: CloseForm['operation'], selected: FinancePeriod | null, element: HTMLElement) {
    trigger.current = element; setError(null); if (intent.hasUncertainResult) { setOpen(true); return; }
    const next: CloseForm = { operation, period: selected, sources: null, from: selected?.from ?? period.from, to: selected?.to ?? period.to, reason: '', acknowledgements: {} }; setForm(next); setOpen(true);
    if (operation === 'CLOSE_PERIOD' && selected) { setBusy(true); const request = new AbortController(); controller.current = request; try { const sources = await prepareFinanceClose(context, selected, request.signal); if (alive.current && !request.signal.aborted) setForm((current) => current?.period?.id === selected.id ? { ...current, sources } : current); } catch (failure) { if (alive.current) setError(failure); } finally { if (alive.current) setBusy(false); } }
  }
  async function submit(retry = false) { setError(null); try { const result = await (retry ? intent.retry() : intent.execute(buildCloseRequest(form!))); if (alive.current) { if ('snapshot' in result && result.snapshot) setSnapshot(result.snapshot); setForm(null); setOpen(false); setNotice('Operación del período registrada con su motivo y versión.'); } } catch (failure) { if (alive.current) setError(failure); } }
  async function refresh() { setBusy(true); setError(null); try { const periods = await getFinancePeriods(context); const latest = periods.find((item) => item.id === form?.period?.id); if (!latest) throw new Error('El período ya no está disponible. Conserva el borrador.'); const sources = form?.operation === 'CLOSE_PERIOD' ? await prepareFinanceClose(context, latest) : null; if (alive.current) { setForm((current) => current ? { ...current, period: latest, sources } : null); setNotice('Versión y fuentes actuales consultadas. Revisa las excepciones y confirma una nueva intención.'); } } catch (failure) { if (alive.current) setError(failure); } finally { if (alive.current) setBusy(false); } }
  async function readSnapshot(selected: FinancePeriod, snapshotId?: string) { setBusy(true); setError(null); try { const result = await getFinanceCloseSnapshot(context, selected.id, snapshotId); if (alive.current) setSnapshot(result); } catch (failure) { if (alive.current) setError(failure); } finally { if (alive.current) setBusy(false); } }
  async function download(format: 'json' | 'csv') {
    if (!snapshot || !canFinanceV2(access, 'finance.export') || !sectionReady(access, 'period-package')) return;
    setBusy(true); setError(null); const request = new AbortController(); controller.current = request;
    try {
      const accountantPackage = await getFinanceClosePackage(context, snapshot.periodId, snapshot.id, request.signal);
      if (!alive.current || request.signal.aborted) return;
      const content = format === 'json' ? JSON.stringify(accountantPackage, null, 2) : accountantPackage.detailsCsv;
      const url = URL.createObjectURL(new Blob([content], { type: format === 'json' ? 'application/json;charset=utf-8' : 'text/csv;charset=utf-8' }));
      const anchor = document.createElement('a'); anchor.href = url; anchor.download = `TOP-finance-close-${snapshot.periodId}-v${snapshot.closeVersion}.${format}`; anchor.click(); URL.revokeObjectURL(url);
      setNotice('Paquete del cierre seleccionado descargado desde sus fuentes conservadas.');
    } catch (failure) { if (alive.current && !request.signal.aborted) setError(failure); }
    finally { if (alive.current) setBusy(false); }
  }
  const uncertain = intent.hasUncertainResult; const conflict = error instanceof ApiError && error.status === 409; const blocker = form?.operation === 'CLOSE_PERIOD' && (!form.sources || form.sources.checklist.some((item) => !item.passed && item.severity === 'BLOCKER'));
  return <><section hidden={!active} className="finance-panel" aria-label="Cierre y paquete del contador"><header><h3>Períodos y cierres conservados</h3></header><p>El cierre conserva un snapshot inmutable y las fuentes del servidor. Reabrir exige un motivo y mantiene los cierres anteriores.</p>
    {!sectionReady(access, 'periods') ? <p>La consulta de períodos todavía no está disponible.</p> : query.isLoading ? <p role="status">Consultando períodos.</p> : query.isError ? <FinanceError error={query.error} onRetry={() => { void query.refetch(); }} /> : null}
    {notice ? <p role="status">{notice}</p> : null}{error && !open ? <p role="alert" className="finance-form-error">{financeErrorMessage(error)}</p> : null}
    {uncertain && !open ? <Button type="button" onClick={(event) => { trigger.current = event.currentTarget; setOpen(true); }}>Recuperar operación de período pendiente</Button> : null}
    {canFinanceV2(access, 'finance.write') ? <Button type="button" variant="secondary" disabled={!sectionReady(access, 'periods') || intent.isPending || busy} onClick={(event) => { void begin('CREATE_PERIOD', null, event.currentTarget); }}>Crear período financiero</Button> : null}
    <div className="finance-v2-list">{query.data?.map((item) => <article key={item.id}><h4>{formatPureDate(item.from)} → {formatPureDate(item.to)} · fin excluido</h4><p>{item.status === 'CLOSED' ? 'Cerrado' : 'Abierto'} · versión {item.version} · {item.timeZone}</p><div className="finance-actions">{canFinanceV2(access, 'finance.write') ? <Button type="button" variant="secondary" disabled={!sectionReady(access, item.status === 'OPEN' ? 'period-close' : 'period-reopen') || intent.isPending || busy} onClick={(event) => { void begin(item.status === 'OPEN' ? 'CLOSE_PERIOD' : 'REOPEN_PERIOD', item, event.currentTarget); }}>{item.status === 'OPEN' ? 'Consultar checklist y cerrar' : 'Reabrir con motivo'}</Button> : null}{item.latestSnapshotId ? <Button type="button" variant="secondary" disabled={!sectionReady(access, 'period-snapshot') || busy} onClick={() => { void readSnapshot(item, item.latestSnapshotId!); }}>Consultar cierre conservado</Button> : null}</div></article>)}</div>
    {snapshot ? <section className="finance-v2-list" aria-label="Snapshot financiero conservado"><h4>Cierre conservado · versión {snapshot.closeVersion}</h4><p>{formatBusinessInstant(snapshot.recordedAt, query.data?.find((item) => item.id === snapshot.periodId)?.timeZone ?? 'UTC')} · actor {snapshot.recordedByUserId}</p><p>Hash de contenido {snapshot.payloadHash}</p><p>{snapshot.sourceRefs.length} fuentes · token {snapshot.sourceToken}</p>{snapshot.checklist.map((item) => <p key={item.key}>{checklistLabels[item.key] ?? item.key}: {item.passed ? 'Conforme' : `${item.severity === 'BLOCKER' ? 'Bloqueo' : 'Excepción'} · ${item.acknowledgement ?? 'Sin motivo declarado'}`}</p>)}<p>Paquete financiero para revisión contable. Alcance de archivos privados pendiente; sin certificado fiscal ni enlace público.</p>{canFinanceV2(access, 'finance.export') ? <div className="finance-actions"><Button type="button" disabled={busy||!sectionReady(access, 'period-package')} onClick={()=>{void download('json');}}><Download size={16} aria-hidden="true" />Descargar paquete de este cierre</Button><Button type="button" variant="secondary" disabled={busy||!sectionReady(access, 'period-package')} onClick={()=>{void download('csv');}}>Descargar detalle CSV del cierre</Button></div> : null}{snapshot.previousSnapshotId ? <Button type="button" variant="secondary" disabled={busy} onClick={() => { const selected = query.data?.find((item) => item.id === snapshot.periodId); if (selected) void readSnapshot(selected, snapshot.previousSnapshotId!); }}>Consultar cierre anterior</Button> : null}</section> : null}
  </section>{open && (form || intent.pendingCommand) ? <OverlayPanel open portal closeLabel="Cerrar formulario" label={operationLabels[form?.operation ?? intent.pendingCommand!.operation]} className="finance-dialog" layerClassName="finance-dialog-layer" triggerRef={trigger} dismissible={!intent.isPending && !busy} onClose={() => setOpen(false)}><header><h2>{operationLabels[form?.operation ?? intent.pendingCommand!.operation]}</h2><Button type="button" iconOnly variant="ghost" aria-label="Cerrar período" disabled={intent.isPending || busy} onClick={() => setOpen(false)}><X size={20} aria-hidden="true" /></Button></header><form onSubmit={(event) => { event.preventDefault(); void submit(); }}><fieldset className="finance-form-body" disabled={intent.isPending || busy || uncertain}>
    {form ? <>{form.operation === 'CREATE_PERIOD' ? <><Input id="close-from" label="Desde" type="date" required value={form.from} onChange={(event) => setForm({ ...form, from: event.target.value })} /><Input id="close-to" label="Hasta (sin incluir)" type="date" required value={form.to} onChange={(event) => setForm({ ...form, to: event.target.value })} /></> : <p>{formatPureDate(form.from)} → {formatPureDate(form.to)} · versión {form.period?.version}</p>}{busy ? <p role="status">Consultando fuentes y checklist.</p> : null}{form.sources ? <><p>{form.sources.sourceRefs.length} fuentes · corte {formatBusinessInstant(form.sources.asOf, form.sources.timeZone)}</p><div className="finance-close-checklist">{form.sources.checklist.map((item) => <div key={item.key}><strong>{checklistLabels[item.key] ?? item.key}</strong><p>{item.passed ? 'Conforme' : item.severity === 'BLOCKER' ? 'Bloquea el cierre hasta resolver su origen' : 'Excepción que exige reconocimiento explícito'}</p>{!item.passed && item.severity === 'EXCEPTION' && closeAcknowledgementKeys.includes(item.key as CloseAcknowledgementKey) ? <Input id={`close-ack-${item.key}`} label={`Motivo de excepción: ${checklistLabels[item.key] ?? item.key}`} minLength={2} maxLength={500} required value={form.acknowledgements[item.key as CloseAcknowledgementKey] ?? ''} onChange={(event) => setForm({ ...form, acknowledgements: { ...form.acknowledgements, [item.key]: event.target.value } })} /> : null}</div>)}</div></> : null}<Input id="close-reason" label="Motivo de la operación" required minLength={2} maxLength={500} value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} /></> : <p>Recupera la operación pendiente con la misma clave y todos los datos originales.</p>}</fieldset>
    {error ? <p role="alert" className="finance-form-error">{financeErrorMessage(error)}</p> : null}{uncertain ? <p role="status" className="finance-form-error">Resultado pendiente de verificar. Reintentar conserva exactamente la intención original.</p> : null}<footer><Button type="button" variant="secondary" disabled={intent.isPending || busy} onClick={() => setOpen(false)}>Cerrar y conservar borrador</Button>{uncertain ? <Button type="button" loading={intent.isPending} disabled={!canFinanceV2(access, 'finance.write')} onClick={() => { void submit(true); }}>Reintentar el mismo registro</Button> : conflict ? <Button type="button" loading={busy} onClick={() => { void refresh(); }}>Consultar versión y fuentes actuales</Button> : <Button type="submit" loading={intent.isPending} disabled={busy || Boolean(blocker) || !form || !canFinanceV2(access, 'finance.write')}>Registrar</Button>}</footer></form></OverlayPanel> : null}</>;
}
