import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { cleanup, render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { StrictMode } from 'react';
import { afterEach, expect, it, vi } from 'vitest';
import { FinanceV2Workspace } from './FinanceV2Workspace';
import type { FinanceV2WorkspaceProps } from './v2-ui.types';
import type { FinanceCorrectionsData, FinancePaymentAdjustmentResult } from './finance-corrections.types';
import type { FinanceCloseSnapshot, FinanceCloseSources, FinancePeriod } from './finance-close.types';
import type { FinanceRecognitionSourceReport } from './finance-recognition-ui.types';
import type { ServiceCertificate } from './finance-recognition.types';
import { buildRecognition } from './FinanceRecognition';
import { v2TestFixture, v2TestId } from './v2-test.fixture';

const json = (value: unknown, status = 200) => new Response(JSON.stringify(value), { status, headers: { 'Content-Type': 'application/json' } });
const clients: QueryClient[] = [];
function props(view: FinanceV2WorkspaceProps['view']): FinanceV2WorkspaceProps { return { context: { businessId: 'operations-synthetic', userId: 'operations-owner', accessToken: 'synthetic-token' }, businessName: 'Negocio QA', view, access: { role: 'OWNER', capabilities: ['finance.read', 'finance.write', 'finance.export', 'payment.refund', 'payment.void', 'pricing.final-amount'], availableSections: [] }, references: v2TestFixture().references, period: { from: '2026-09-01', to: '2026-10-01' } }; }
function mount(input: FinanceV2WorkspaceProps) { input.references.report.businessId=input.context.businessId; const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); clients.push(client); return render(<QueryClientProvider client={client}><StrictMode><FinanceV2Workspace {...input} /></StrictMode></QueryClientProvider>); }
afterEach(() => { cleanup(); clients.splice(0).forEach((client) => client.clear()); vi.restoreAllMocks(); vi.unstubAllGlobals(); });
const amounts = { grossRecordedAmountMinor: 1000000, voidedAmountMinor: 0, refundedAmountMinor: 0, netRetainedAmountMinor: 1000000 };
function corrections(): FinanceCorrectionsData { return { businessId: 'operations-synthetic', currency: 'PYG', timeZone: 'America/Asuncion', asOf: '2026-10-05T12:00:00.000Z', token: 'corrections-server-token', sourceLimit: 5000, capabilities: { voidPayment: true, refundPayment: true, terminalFinalAmount: true }, bookings: [{ bookingId: v2TestId, label: 'Reserva QA cancelada', status: 'CANCELLED', bookingUpdatedAt: '2026-09-30T12:00:00.000Z', resourceIds: [], checkInDate: '2026-09-01', checkOutDate: '2026-09-03', pricing: { currentPricingId: v2TestId, originalSnapshotId: v2TestId, pricingRevisionId: v2TestId, revisionNumber: 2, kind: 'TERMINAL_FINAL_AMOUNT', currency: 'PYG', totalAmountMinor: 800000 }, financialVersion: 4, amounts, outstandingMinor: 0, creditMinor: 200000, needsReconciliation: false, canSetTerminalFinalAmount: true, warnings: [], payments: [{ id: v2TestId, bookingId: v2TestId, paidAt: '2026-09-02T12:00:00.000Z', paymentVersion: 2, effectiveStatus: 'RETAINED', voidAllowed: true, refundAvailableMinor: 1000000, accountLink: { accountId: 'account-a', version: 7 }, ...amounts }] }] }; }
it('devolución200000 conserva bruto1M y muestra neto800000/crédito0 del servidor sin reabrir la reserva', async () => {
  const input = props('corrections'); input.access.availableSections = ['corrections', 'payment-adjustments', 'terminal-pricing']; let data = corrections();
  const result: FinancePaymentAdjustmentResult = { id: v2TestId, type: 'REFUND_PAYMENT', version: 1, bookingId: v2TestId, paymentId: v2TestId, currentPricingId: v2TestId, paymentVersion: 3, financialVersion: 5, amounts: { ...amounts, refundedAmountMinor: 200000, netRetainedAmountMinor: 800000 }, applicationReversals: [] };
  const fetch = vi.fn(async (_url: string, request?: RequestInit) => { if (request?.method !== 'POST') return json(data); data = { ...data, bookings: [{ ...data.bookings[0], amounts: result.amounts, creditMinor: 0, financialVersion: 5, payments: [{ ...data.bookings[0].payments[0], ...result.amounts, paymentVersion: 3, effectiveStatus: 'PARTIALLY_REFUNDED', refundAvailableMinor: 800000 }] }] }; return json(result); }); vi.stubGlobal('fetch', fetch);
  const user = userEvent.setup(); mount(input); await user.click(await screen.findByRole('button', { name: 'Registrar devolución externa' })); const dialog = screen.getByRole('dialog');
  await user.type(within(dialog).getByRole('textbox', { name: 'Importe devuelto, guaraníes PYG' }), '200000'); await user.type(within(dialog).getByLabelText('Motivo'), 'Devolución externa declarada'); await user.click(within(dialog).getByRole('button', { name: 'Registrar' }));
  await screen.findByText('Corrección registrada. El original y su historial se conservan.'); await waitFor(() => expect(screen.getByText(/crédito/)).toHaveTextContent('crédito ₲ 0'));
  const post = fetch.mock.calls.find(([, request]) => request?.method === 'POST')!; expect(String(post[0])).toContain('/finance/payment-adjustments'); expect(JSON.parse(post[1]!.body as string)).toMatchObject({ type: 'REFUND_PAYMENT', bookingId: v2TestId, paymentId: v2TestId, amountMinor: 200000, expectedAccountVersion: 1, expectedPaymentVersion: 2, expectedFinancialVersion: 4, currentPricingId: v2TestId }); expect(screen.getByText(/Reserva QA cancelada/)).toBeInTheDocument(); expect(screen.getAllByText('₲ 800.000').length).toBeGreaterThan(0); expect(screen.getByText(/no reabre la reserva/)).toBeInTheDocument();
});
const period: FinancePeriod = { id: v2TestId, businessId: 'operations-synthetic', from: '2026-09-01', to: '2026-10-01', timeZone: 'America/Asuncion', status: 'OPEN', version: 1, latestSnapshotId: null };
function sources(): FinanceCloseSources { return { businessId: period.businessId, from: period.from, to: period.to, timeZone: period.timeZone, asOf: '2026-10-05T12:00:00.000Z', sourceToken: 'close-original-server-token', payload: { immutable: 'Original source payload' }, payloadHash: 'original-server-hash', sourceRefs: [{ type: 'SERVICE_CERTIFICATE', id: v2TestId, version: '1' }], policyVersions: { period: 'BLOCK_CLOSED_PERIOD_V1' }, guardedWriters: ['PAYMENT', 'FINANCE_V2'], checklist: [{ key: 'SOURCES_COMPLETE', passed: true, severity: 'BLOCKER', acknowledgement: null }, { key: 'CASH_COUNTS', passed: false, severity: 'EXCEPTION', acknowledgement: null }] }; }
it('checklist con fuentes incompletas bloquea el cierre; ningún acknowledgement ni motivo simula un POST', async () => {
  const input = props('close'); input.access.availableSections = ['periods', 'period-close']; const incomplete = sources(); incomplete.checklist = [{ key: 'SOURCES_COMPLETE', passed: false, severity: 'BLOCKER', acknowledgement: null }];
  const fetch = vi.fn(async (url: string) => json(url.includes('/prepare') ? incomplete : [period])); vi.stubGlobal('fetch', fetch); const user = userEvent.setup(); mount(input); await user.click(await screen.findByRole('button', { name: 'Consultar checklist y cerrar' })); const dialog = screen.getByRole('dialog');
  expect(await within(dialog).findByText('Bloquea el cierre hasta resolver su origen')).toBeInTheDocument(); await user.type(within(dialog).getByLabelText('Motivo de la operación'), 'Intento de cierre con origen pendiente'); expect(within(dialog).getByRole('button', { name: 'Registrar' })).toBeDisabled(); expect(fetch.mock.calls.every(([url]) => !url.endsWith('/close'))).toBe(true);
});
it('excepción de caja exige motivo, cierre usa token/version y paquete descarga el snapshot inmutable del servidor', async () => {
  const input = props('close'); input.access.availableSections = ['periods', 'period-close', 'period-snapshot', 'period-package']; const prepared = sources();
  const snapshot: FinanceCloseSnapshot = { id: v2TestId, businessId: period.businessId, periodId: period.id, closeVersion: 2, previousSnapshotId: null, asOf: prepared.asOf, sourceToken: prepared.sourceToken, policyVersion: 'BLOCK_CLOSED_PERIOD_V1', policyVersions: prepared.policyVersions, payload: prepared.payload, payloadHash: prepared.payloadHash, sourceRefs: prepared.sourceRefs, checklist: prepared.checklist, recordedByUserId: 'operations-owner', recordedAt: prepared.asOf };
  const closed = { ...period, status: 'CLOSED' as const, version: 2, latestSnapshotId: snapshot.id }; let registered = false;
  const accountantPackage = { period: { from: period.from, to: period.to, timeZone: period.timeZone }, snapshot, detailsCsv: 'source_id,amount_minor\r\noriginal,100001\r\n', alerts: [{ code: 'CHECKLIST:CASH_COUNTS', count: 1, acknowledgement: 'Diferencia investigada' }], debtBasis: 'OBSERVED_AT_AS_OF', unknownHistoricalDebt: true };
  const fetch = vi.fn(async (url: string, request?: RequestInit) => { if (request?.method === 'POST') { registered = true; return json({ period: closed, event: { id: v2TestId, businessId: period.businessId, periodId: period.id, type: 'CLOSE', beforeVersion: 1, afterVersion: 2, snapshotId: snapshot.id, reason: 'Cierre revisado', actorUserId: 'operations-owner', occurredAt: prepared.asOf }, snapshot }); } if (url.includes('/package?')) return json(accountantPackage); if (url.includes('/prepare')) return json(prepared); return json([registered ? closed : period]); }); vi.stubGlobal('fetch', fetch);
  const createUrl = vi.fn().mockReturnValue('blob:owned-finance-close'); vi.stubGlobal('URL', Object.assign(URL, { createObjectURL: createUrl, revokeObjectURL: vi.fn() })); vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => undefined);
  const user = userEvent.setup(); mount(input); await user.click(await screen.findByRole('button', { name: 'Consultar checklist y cerrar' })); const dialog = screen.getByRole('dialog'); await within(dialog).findByText('Excepción que exige reconocimiento explícito'); await user.type(within(dialog).getByLabelText('Motivo de la operación'), 'Cierre revisado'); await user.click(within(dialog).getByRole('button', { name: 'Registrar' })); expect(registered).toBe(false); await user.type(within(dialog).getByLabelText('Motivo de excepción: Arqueos y diferencias de caja'), 'Diferencia investigada'); await user.click(within(dialog).getByRole('button', { name: 'Registrar' })); await screen.findByText('Operación del período registrada con su motivo y versión.');
  const post = fetch.mock.calls.find(([, request]) => request?.method === 'POST')!; expect(JSON.parse(post[1]!.body as string)).toEqual({ expectedVersion: 1, expectedSourceToken: 'close-original-server-token', reason: 'Cierre revisado', acknowledgements: { CASH_COUNTS: 'Diferencia investigada' } });
  await user.click(screen.getByRole('button', { name: 'Descargar paquete de este cierre' })); await waitFor(() => expect(createUrl).toHaveBeenCalledOnce()); const blob = createUrl.mock.calls[0][0] as Blob; const contents = await new Promise<string>((resolve) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.readAsText(blob); }); expect(JSON.parse(contents)).toEqual(accountantPackage); expect(fetch.mock.calls.some(([url]) => url.includes(`/package?snapshotId=${snapshot.id}`))).toBe(true); expect(fetch.mock.calls.filter(([url]) => url.includes('/prepare'))).toHaveLength(1);
});
function recognitionSources(): FinanceRecognitionSourceReport {
  const pricing = { businessId: 'operations-synthetic', bookingId: v2TestId, resourceId: v2TestId, originalSnapshotId: v2TestId, sourceId: v2TestId, serviceRevisionId: null, revisionNumber: 0, sourceHash: 'server-night-map-hash', currency: 'PYG', checkInDate: '2026-09-01', checkOutDate: '2026-09-03', mode: 'MANUAL_OVERRIDE' as const, agreedAmountMinor: 100001, totalAmountMinor: 100001, suggestedAmountMinor: null, adjustmentAmountMinor: null, overrideReason: 'Acuerdo manual', nights: 2, breakdown: [] };
  return { businessId: 'operations-synthetic', from: '2026-09-01', to: '2026-10-01', timeZone: 'America/Asuncion', localToday: '2026-10-05', asOf: '2026-10-05T12:00:00.000Z', token: 'recognition-server-token', sourceLimit: 5000, sourceCount: 1, sources: [{ bookingId: v2TestId, bookingUpdatedAt: '2026-09-04T12:00:00.000Z', status: 'COMPLETED', resourceIds: [v2TestId], checkInDate: '2026-09-01', checkOutDate: '2026-09-03', checkInEventId: v2TestId, checkOutEventId: v2TestId, pricing, agreedNights: [{ localNight: '2026-09-01', amountMinor: 50001 }, { localNight: '2026-09-02', amountMinor: 50000 }], eligibleNights: ['2026-09-01', '2026-09-02'], certificationBlockers: [], currentCertificate: null, terminal: null }] };
}
it('certificación no selecciona noches automáticamente; envía sólo prestación declarada y muestra unidades exactas del servidor', async () => {
  const input = props('results'); input.access.availableSections = ['recognition-sources', 'service-certificates']; let data = recognitionSources();
  const certificate: ServiceCertificate = { id: v2TestId, businessId: data.businessId, bookingId: v2TestId, resourceId: v2TestId, version: 1, supersedesCertificateId: null, recordedByUserId: 'operations-owner', recordedAt: data.asOf, bookingUpdatedAt: data.sources[0].bookingUpdatedAt, effectiveCheckInOn: '2026-09-01', effectiveCheckOutOn: '2026-09-03', checkInEventId: v2TestId, checkOutEventId: v2TestId, pricing: data.sources[0].pricing!, policyVersion: 'EQUAL_AGREED_NIGHTS_V1', servicePolicyVersion: 'NIGHT_SERVICE_V1', evidence: 'Acta sintética manual', reason: 'Prestación comprobada', units: [{ localNight: '2026-09-01', amountMinor: 50001 }] };
  const fetch = vi.fn(async (_url: string, request?: RequestInit) => { if (request?.method !== 'POST') return json(data); data = { ...data, sources: [{ ...data.sources[0], currentCertificate: certificate }] }; return json(certificate); }); vi.stubGlobal('fetch', fetch); const user = userEvent.setup(); mount(input); await user.click(await screen.findByRole('button', { name: 'Certificar servicio prestado' })); const dialog = screen.getByRole('dialog');
  const nights = within(dialog).getAllByRole('checkbox'); expect(nights).toHaveLength(2); nights.forEach((night) => expect(night).not.toBeChecked()); await user.click(nights[0]); await user.type(within(dialog).getByLabelText('Fecha efectiva de entrada'), '2026-09-01'); await user.type(within(dialog).getByLabelText('Evidencia de prestación'), 'Acta sintética manual'); await user.type(within(dialog).getByLabelText('Motivo'), 'Prestación comprobada'); await user.click(within(dialog).getByRole('button', { name: 'Registrar' })); await screen.findByText('Declaración registrada con su fuente y versión.');
  const post = fetch.mock.calls.find(([, request]) => request?.method === 'POST')!; expect(JSON.parse(post[1]!.body as string)).toMatchObject({ servedNights: ['2026-09-01'], expectedCertificateVersion: 0, expectedPricingSourceId: v2TestId, effectiveCheckInOn: '2026-09-01', effectiveCheckOutOn: null, supersedesCertificateId: null }); expect(JSON.parse(post[1]!.body as string)).not.toHaveProperty('amountMinor'); expect(await screen.findByText(/₲ 50.001/)).toBeInTheDocument();
});
it('reverso explícito usa la fuente fijada en el certificado anterior aunque cambió el precio actual', () => {
  const data = recognitionSources(); const source = data.sources[0]; const oldPrice = { ...source.pricing!, sourceId: 'older-fixed-price' }; source.currentCertificate = { id: v2TestId, businessId: data.businessId, bookingId: source.bookingId, resourceId: v2TestId, version: 3, supersedesCertificateId: null, recordedByUserId: 'owner', recordedAt: data.asOf, bookingUpdatedAt: source.bookingUpdatedAt, effectiveCheckInOn: '2026-09-01', effectiveCheckOutOn: null, checkInEventId: v2TestId, checkOutEventId: null, pricing: oldPrice, policyVersion: 'EQUAL_AGREED_NIGHTS_V1', servicePolicyVersion: 'NIGHT_SERVICE_V1', evidence: 'Acta previa', reason: 'Prestación previa', units: [] };
  expect(buildRecognition({ operation: 'CERTIFY_SERVICE', source, reverse: true, servedNights: ['2026-09-01'], checkIn: '2026-09-01', checkOut: '', evidence: 'Acta rectificada', reason: 'Reverso explícito', recognitionOn: '', amount: '', coverage: '', classification: '' })).toMatchObject({ command: { expectedPricingSourceId: 'older-fixed-price', servedNights: [], expectedCertificateVersion: 3, supersedesCertificateId: v2TestId } });
});
