import {afterEach,expect,it,vi} from 'vitest';
import {configureUnauthorizedRecovery} from '../../../shared/api/api-client';
import {executeV2Command,getV2Page,getV2Report,getV2Budget,previewV2History} from './finance-v2-api';
import {v2TestFixture,v2TestId} from './v2-test.fixture';
const context={businessId:'synthetic-a',userId:'owner-a',accessToken:'synthetic-token'};
afterEach(()=>{vi.unstubAllGlobals();configureUnauthorizedRecovery(null);});
it.each([new Response(null,{status:204}),new Response('{}'),new Response(JSON.stringify({id:v2TestId,type:'CREATE_COMMITMENT',version:1}))])('éxito inválido no acredita otro comando ni pierde la recuperación',async(response)=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(response));await expect(executeV2Command(context,{type:'CREATE_EXPENSE_TEMPLATE',name:'Sintética',expenseDefinition:{description:'Sintética',amountMinor:450000,lines:[],counterpartyId:null,reference:null}},'key')).rejects.toMatchObject({name:'ApiResponseError'});});
it('mutación401 no invoca recuperación ni se repite automáticamente',async()=>{const recover=vi.fn();configureUnauthorizedRecovery({recover});const fetch=vi.fn().mockResolvedValue(new Response('{"message":"No autorizado"}',{status:401}));vi.stubGlobal('fetch',fetch);await expect(executeV2Command(context,{type:'SET_EXPENSE_APPROVAL_POLICY',expectedPolicyVersion:0,enabled:false,scope:'ALL_NEW_EXPENSE_CONFIRMATIONS',requireDifferentActor:true,reason:'Sintética'},'key')).rejects.toMatchObject({status:401});expect(fetch).toHaveBeenCalledOnce();expect(recover).not.toHaveBeenCalled();});
it('lectura paginada descarta Business ajeno y envía cursor/limit exactos',async()=>{const fetch=vi.fn().mockResolvedValue(new Response(JSON.stringify({items:[{id:v2TestId,businessId:'other',version:1}],nextCursor:null})));vi.stubGlobal('fetch',fetch);await expect(getV2Page(context,'drafts','cursor-a')).rejects.toMatchObject({name:'ApiResponseError'});const url=new URL(fetch.mock.calls[0][0]);expect(url.searchParams.get('cursor')).toBe('cursor-a');expect(url.searchParams.get('limit')).toBe('50');});
it('vista previa inválida conserva HTTP400 y errores por fila, sin clave de escritura',async()=>{const issues=[{ordinal:3,column:'amountMinor',code:'INVALID_INPUT',message:'Importe inválido'}];const response={statusCode:400,error:'Bad Request',message:'El CSV contiene errores.',previewToken:null,issues};const fetch=vi.fn().mockResolvedValue(new Response(JSON.stringify(response),{status:400}));vi.stubGlobal('fetch',fetch);await expect(previewV2History(context,{sourceNamespace:'history-qa',csv:'csv-synthetic'})).rejects.toMatchObject({status:400,previewIssues:issues});expect(String(fetch.mock.calls[0][0])).toContain('/v2/history-preview');expect(new Headers(fetch.mock.calls[0][1].headers).has('Idempotency-Key')).toBe(false);});
it('reporte conserva corte explícito; una respuesta con otro asOf no sirve para comparar costos/resultados',async()=>{const report=v2TestFixture().data.costs!;const fetch=vi.fn().mockImplementation(async()=>new Response(JSON.stringify(report)));vi.stubGlobal('fetch',fetch);await expect(getV2Report(context,'costs',{from:report.from,to:report.to,asOf:report.asOf})).resolves.toEqual(report);expect(new URL(fetch.mock.calls[0][0]).searchParams.get('asOf')).toBe(report.asOf);await expect(getV2Report(context,'costs',{from:report.from,to:report.to,asOf:'2026-10-06T12:00:00.000Z'})).rejects.toMatchObject({name:'ApiResponseError'});});

it.each(['','null'])('presupuesto inexistente acepta únicamente ausencia vacía o JSONnull de este GET (%j)',async(body)=>{const fetch=vi.fn().mockResolvedValue(new Response(body));vi.stubGlobal('fetch',fetch);await expect(getV2Budget(context,'2026-09')).resolves.toBeNull();expect(new URL(fetch.mock.calls[0][0]).pathname).toContain('/finance/v2/budget');expect(new URL(fetch.mock.calls[0][0]).searchParams.get('periodMonth')).toBe('2026-09');expect(fetch).toHaveBeenCalledOnce();});
it('presupuesto JSON existente conserva el DTO y el mes solicitado',async()=>{const budget={id:v2TestId,businessId:context.businessId,periodMonth:'2026-10',version:1,approvedRevisionId:null,revisions:[]};vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify(budget))));await expect(getV2Budget(context,'2026-10')).resolves.toEqual(budget);});
it.each([' ','\n','{invalid','{}','[]','1','true','"budget"',JSON.stringify({businessId:'foreign',periodMonth:'2026-09',version:1}),JSON.stringify({businessId:context.businessId,periodMonth:'2026-10',version:1}),JSON.stringify({businessId:context.businessId,periodMonth:'2026-09',version:0})])('presupuesto nullable rechaza whitespace, formato o DTO incorrecto (%j)',async(body)=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(body)));await expect(getV2Budget(context,'2026-09')).rejects.toMatchObject({name:'ApiResponseError'});});
it('presupuesto204 no equivale a la ausencia exitosa200 del contrato nullable',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(null,{status:204})));await expect(getV2Budget(context,'2026-09')).rejects.toMatchObject({name:'ApiResponseError'});});
it('presupuesto403 conserva HTTP403 sin convertirlo en ausencia ni reintentar',async()=>{const fetch=vi.fn().mockResolvedValue(new Response('{"message":"No autorizado"}',{status:403}));vi.stubGlobal('fetch',fetch);await expect(getV2Budget(context,'2026-09')).rejects.toMatchObject({name:'ApiError',status:403});expect(fetch).toHaveBeenCalledOnce();});
it('presupuesto con fallo de transporte conserva el error sin inventar ausencia',async()=>{vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new TypeError('synthetic offline')));await expect(getV2Budget(context,'2026-09')).rejects.toMatchObject({name:'ApiTransportError'});});
it('otra lectura vacía sigue siendo una respuesta inválida',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('')));await expect(getV2Page(context,'drafts',null)).rejects.toMatchObject({name:'ApiResponseError'});});
