import { formatMoney } from '../../../shared/utils/money';
import type { FinanceResourceReport, FinanceResourceResult } from './finance-v2.types';
import type { FinanceV2References } from './v2-ui.types';
function Result({ row, label }: { row: FinanceResourceResult; label: string }) {
  const money = (value: number | null) => value === null ? 'Desconocido' : formatMoney(value);
  return <article><h4>{label}</h4><p>{row.status === 'COMPLETE' ? 'Cobertura completa' : row.status === 'ESTIMATED' ? 'Incluye estimación seleccionada' : 'Cobertura incompleta'}</p><dl className="finance-v2-amounts"><dt>Ingreso reconocido</dt><dd>{money(row.recognizedRevenueMinor)}</dd><dt>Costo real directo</dt><dd>{money(row.directActualCostMinor)}</dd><dt>Costo real común asignado</dt><dd>{money(row.commonActualCostMinor)}</dd><dt>Estimación seleccionada</dt><dd>{money(row.selectedEstimatedCostMinor)}</dd><dt>Trabajo propio imputado</dt><dd>{money(row.ownerImputedMinor)}</dd><dt>Contribución</dt><dd>{money(row.contributionMinor)}</dd><dt>Resultado antes del trabajo propio</dt><dd>{money(row.operatingResultBeforeOwnerWorkMinor)}</dd><dt>Resultado después del trabajo propio</dt><dd>{money(row.resultAfterOwnerWorkMinor)}</dd><dt>Margen</dt><dd>{row.marginBasisPoints === null ? 'Sin base suficiente' : `${(row.marginBasisPoints / 100).toLocaleString('es-PY', { maximumFractionDigits: 2 })}%`}</dd></dl>{row.reasons.map((reason) => <p key={reason}>{reason}</p>)}<details><summary>Fuentes conservadas</summary>{row.sourceKeys.map((source) => <p key={source}>{source}</p>)}</details></article>;
}
export function FinanceResultsSummary({ report, references }: { report: FinanceResourceReport; references: FinanceV2References }) {
  return <section className="finance-panel" aria-label="Resultados del negocio y recursos"><header><h3>Resultado con ingreso certificado</h3></header><div className="finance-v2-list"><Result row={report.business} label="Negocio completo" />{report.rows.map((row) => <Result key={row.resourceId ?? 'unassigned'} row={row} label={references.report.resources.find((resource) => resource.id === row.resourceId)?.name ?? 'Sin asignar'} />)}<p>Contribución: ingreso reconocido y costos directos. Resultado operativo: incluye costos comunes y la estimación seleccionada. El trabajo propio conserva una base separada.</p>{report.coverage.pendingRecognition.length ? <p className="finance-warning">Ingreso pendiente de certificación: {report.coverage.pendingRecognition.join(', ')}</p> : null}{report.coverage.unknownCosts.length ? <p className="finance-warning">Costos sin cobertura completa: {report.coverage.unknownCosts.join(', ')}</p> : null}<p>Fuentes de ingreso {report.recognitionToken} · costos {report.costToken} · corte {report.asOf}</p><p>Los importes, resultados y margen proceden del servidor. Una base incompleta o ingreso sin base no permite un ranking concluyente.</p></div></section>;
}
