import { useQuery } from '@tanstack/react-query';
import { Button } from '../../../shared/ui/Button';
import { formatMoney } from '../../../shared/utils/money';
import type { FinanceContext } from '../api/finance-api';
import { FinanceError } from '../components/FinanceFeedback';
import { getV2Aging } from './finance-v2-api';
import { financeV2Key } from './use-v2-command';
import { canFinanceV2, sectionReady, type FinanceV2Access, type FinanceV2References } from './v2-ui.types';
const bucketLabels = { CURRENT: 'Vigente', DAYS_1_30: 'Vencido entre 1 y 30 días', DAYS_31_60: 'Vencido entre 31 y 60 días', DAYS_61_90: 'Vencido entre 61 y 90 días', OVER_90: 'Vencido hace más de 90 días', UNDATED: 'Sin vencimiento confirmado', REVIEW: 'Plan o fuente en revisión' } as const;
export function FinanceAgingAlerts({ context, access, references, active }: { context: FinanceContext; access: FinanceV2Access; references: FinanceV2References; active: boolean }) {
  const query = useQuery({ queryKey: [...financeV2Key(context), 'aging', references.report.asOf], queryFn: ({ signal }) => getV2Aging(context, references.report.asOf, signal), enabled: active && sectionReady(access, 'aging') && canFinanceV2(access, 'finance.planning'), retry: false });
  const report = references.report;
  return <section hidden={!active} className="finance-panel" aria-label="Antigüedad y alertas internas"><header><h3>Obligaciones y alertas internas de este negocio</h3></header><p>La antigüedad procede del servidor y muestra obligaciones actuales. Las alertas se vuelven a consultar al actualizar sus fuentes; no envían mensajes externos.</p>{query.isError ? <FinanceError error={query.error} onRetry={() => { void query.refetch(); }} /> : query.isLoading ? <p role="status">Consultando obligaciones actuales.</p> : null}{!sectionReady(access, 'aging') ? <p>La consulta de antigüedad todavía no está disponible.</p> : null}
    <div className="finance-v2-list">{query.data?.rows.map((row) => <article key={row.sourceKey}><strong>{row.direction === 'PAYABLE' ? 'Por pagar' : 'Por cobrar'} · {formatMoney(row.amountMinor)}</strong><p>{bucketLabels[row.bucket]} · {row.dueOn ?? 'Sin fecha confirmada'}</p>{row.bookingId ? <a href={`/app/bookings/${encodeURIComponent(row.bookingId)}/payments`}>Consultar cobros y plan de la reserva</a> : row.expenseId ? <a href="/app/finance?view=expenses">Consultar el gasto original</a> : null}<p>Origen {row.sourceKey} · versión {row.sourceVersion}</p></article>)}{query.data?.credits.map((credit) => <article key={`credit:${credit.bookingId}`}><strong>Crédito de la reserva {formatMoney(credit.amountMinor)}</strong><a href={`/app/bookings/${encodeURIComponent(credit.bookingId)}/payments`}>Consultar saldo y devoluciones</a></article>)}</div>
    <div className="finance-v2-list" aria-label="Fuentes que requieren revisión">{report.expenses.filter((expense) => expense.evidenceMissing).map((expense) => <article key={`evidence:${expense.id}`}><strong>Evidencia pendiente: {expense.description}</strong><a href="/app/finance?view=expenses">Consultar gasto y referencia</a></article>)}{report.accounts.filter((account) => !account.opening).map((account) => <article key={`opening:${account.id}`}><strong>Apertura pendiente: {account.name}</strong><p>Saldo desconocido hasta declarar una apertura con su fecha.</p><a href="/app/finance?view=accounts">Consultar cuenta</a></article>)}{report.movements.filter((movement) => movement.reviewStale).map((movement) => <article key={`review:${movement.id}`}><strong>Revisión desactualizada: {movement.description}</strong><a href="/app/finance?view=movements">Consultar origen y versión actual</a></article>)}{report.cashCounts.filter((count) => count.differenceMinor !== 0).map((count) => <article key={`cash:${count.id}`}><strong>Diferencia declarada de caja {formatMoney(count.differenceMinor)}</strong><p>{count.adjustmentId ? 'Conserva un ajuste vinculado; la diferencia requiere revisión explícita al cerrar.' : 'Requiere revisión de su origen.'}</p><a href="/app/finance?view=movements">Consultar arqueo y origen</a></article>)}</div>
    {query.isSuccess ? <Button type="button" variant="secondary" loading={query.isFetching} onClick={() => { void query.refetch(); }}>Actualizar obligaciones y alertas</Button> : null}<p className="finance-help">Comprobantes: las referencias textuales conservan su origen. Puedes cargar y descargar archivos privados desde el detalle del gasto con los permisos correspondientes. Los adjuntos se conservan sin purga; su restauración se verificó con datos sintéticos. La conservación no autoriza su eliminación ni constituye una certificación fiscal.</p>
  </section>;
}
