import { useQuery } from '@tanstack/react-query';
import { useEffect, useRef, useState } from 'react';
import { X } from 'lucide-react';
import { ApiError } from '../../../shared/api/api-client';
import { Button } from '../../../shared/ui/Button';
import { Input } from '../../../shared/ui/Input';
import { OverlayPanel } from '../../../shared/ui/OverlayPanel';
import { formatMoney } from '../../../shared/utils/money';
import { formatPureDate } from '../../../shared/utils/date-format';
import type { FinanceContext } from '../api/finance-api';
import { MoneyField, SelectField } from '../components/FinanceFields';
import { FinanceError, financeErrorMessage } from '../components/FinanceFeedback';
import type { FinanceRecognitionSource } from './finance-recognition-ui.types';
import { executeFinanceRecognition, getFinanceRecognitionSources, type FinanceRecognitionRequest } from './finance-recognition-api';
import { useFinanceIntent } from './use-finance-intent';
import { financeV2Key } from './use-v2-command';
import { canFinanceV2, sectionReady, type FinanceV2Access, type FinanceV2References } from './v2-ui.types';
import { v2Money } from './v2-form';

interface RecognitionForm { operation: FinanceRecognitionRequest['operation']; source: FinanceRecognitionSource; servedNights: string[]; reverse: boolean; checkIn: string; checkOut: string; evidence: string; reason: string; recognitionOn: string; amount: string; coverage: '' | 'COMPLETE' | 'DECLARED_NONE'; classification: string }
export function buildRecognition(form: RecognitionForm): FinanceRecognitionRequest {
  const source = form.source;
  if (form.operation === 'CERTIFY_SERVICE') {
    if (!form.reverse && !form.servedNights.length) throw new Error('Selecciona las noches realmente prestadas.');
    if (form.reverse && !source.currentCertificate) throw new Error('El reverso requiere una certificación anterior consultada.');
    const pricing = form.reverse ? source.currentCertificate!.pricing : source.pricing; if (!pricing) throw new Error('No hay una fuente de precio de servicio disponible.');
    return { operation: form.operation, command: { bookingId: source.bookingId, expectedBookingUpdatedAt: source.bookingUpdatedAt, expectedCertificateVersion: source.currentCertificate?.version ?? 0, expectedPricingSourceId: pricing.sourceId, servedNights: form.reverse ? [] : form.servedNights, effectiveCheckInOn: form.checkIn, effectiveCheckOutOn: form.checkOut || null, evidence: form.evidence.trim(), reason: form.reason.trim(), supersedesCertificateId: source.currentCertificate?.id ?? null } };
  }
  if (!source.terminal || source.terminal.blockers.length) throw new Error('Resuelve los bloqueos del importe final antes de reconocerlo.');
  if (!form.coverage) throw new Error('Declara la cobertura del importe que no corresponde al servicio.');
  return { operation: form.operation, command: { bookingId: source.bookingId, expectedBookingUpdatedAt: source.bookingUpdatedAt, expectedVersion: source.terminal.expectedVersion, expectedPricingRevisionId: source.terminal.pricingRevisionId, serviceCertificateId: source.terminal.serviceCertificateId, serviceCertificateVersion: source.terminal.serviceCertificateVersion, recognitionOn: form.recognitionOn, confirmedNonServiceAmountMinor: v2Money(form.amount, true), coverage: form.coverage, classification: form.classification.trim(), reason: form.reason.trim() } };
}
export function FinanceRecognition({ context, access, references, active, period }: { context: FinanceContext; access: FinanceV2Access; references: FinanceV2References; active: boolean; period: { from: string; to: string } }) {
  const query = useQuery({ queryKey: [...financeV2Key(context), 'recognition-sources', period], queryFn: ({ signal }) => getFinanceRecognitionSources(context, period, signal), enabled: active && canFinanceV2(access, 'finance.read') && sectionReady(access, 'recognition-sources'), retry: false });
  const intent = useFinanceIntent(context, 'recognition', executeFinanceRecognition); const trigger = useRef<HTMLElement | null>(null); const [form, setForm] = useState<RecognitionForm | null>(null); const [open, setOpen] = useState(false); const [error, setError] = useState<unknown>(null); const [notice, setNotice] = useState(''); const alive = useRef(true);
  useEffect(() => { alive.current = true; return () => { alive.current = false; }; }, []);
  function begin(operation: RecognitionForm['operation'], source: FinanceRecognitionSource, element: HTMLElement) { trigger.current = element; if (!intent.hasUncertainResult) setForm({ operation, source, servedNights: [], reverse: false, checkIn: source.currentCertificate?.effectiveCheckInOn ?? '', checkOut: source.currentCertificate?.effectiveCheckOutOn ?? '', evidence: '', reason: '', recognitionOn: query.data?.localToday ?? '', amount: '', coverage: '', classification: '' }); setOpen(true); setError(null); }
  async function submit(retry = false) { setError(null); try { await (retry ? intent.retry() : intent.execute(buildRecognition(form!))); if (alive.current) { setForm(null); setOpen(false); setNotice('Declaración registrada con su fuente y versión.'); } } catch (failure) { if (alive.current) setError(failure); } }
  async function refresh() { setError(null); try { const latest = await getFinanceRecognitionSources(context, period); const source = latest.sources.find((item) => item.bookingId === form?.source.bookingId); if (!source) throw new Error('El origen ya no aparece en el período. Conserva la declaración.'); if (alive.current) { setForm((current) => current ? { ...current, source } : null); setNotice('Fuentes actuales consultadas. Revisa las noches y confirma una nueva intención.'); } } catch (failure) { if (alive.current) setError(failure); } }
  const uncertain = intent.hasUncertainResult; const conflict = error instanceof ApiError && error.status === 409; const label = (form?.operation ?? intent.pendingCommand?.operation) === 'RECOGNIZE_TERMINAL' ? 'Reconocer importe no prestado' : 'Certificar servicio prestado';
  return <><section hidden={!active} className="finance-panel" aria-label="Prestación e ingreso certificado"><header><h3>Prestación e ingreso certificado</h3></header><p>Selecciona manualmente las noches realmente prestadas. Las fechas acordadas, el estado de la reserva y el paso del tiempo no certifican servicio.</p>{!sectionReady(access, 'recognition-sources') ? <p>La consulta de fuentes de prestación todavía no está disponible.</p> : query.isLoading ? <p role="status">Consultando evidencia y precios de servicio.</p> : query.isError ? <FinanceError error={query.error} onRetry={() => { void query.refetch(); }} /> : null}{notice ? <p role="status">{notice}</p> : null}{uncertain && !open ? <Button type="button" onClick={(event) => { trigger.current = event.currentTarget; setOpen(true); }}>Recuperar declaración pendiente</Button> : null}
    <div className="finance-v2-list">{query.data?.sources.map((source) => <article key={source.bookingId}><h4>{references.bookings.find((booking) => booking.id === source.bookingId)?.label ?? `Reserva ${source.bookingId}`}</h4><p>{source.status} · <a href={`/app/bookings/${encodeURIComponent(source.bookingId)}`}>Consultar reserva y sus cargos directos</a></p>{source.pricing ? <p>Precio acordado {formatMoney(source.pricing.agreedAmountMinor)} · fuente {source.pricing.sourceId} · revisión {source.pricing.revisionNumber}</p> : <p>Precio de servicio sin cobertura suficiente.</p>}{source.currentCertificate ? <><p>Certificado v{source.currentCertificate.version} · {source.currentCertificate.policyVersion} · {source.currentCertificate.servicePolicyVersion}</p>{source.currentCertificate.units.map((night) => <p key={night.localNight}>{formatPureDate(night.localNight)} · {formatMoney(night.amountMinor)}</p>)}<p>Evidencia: {source.currentCertificate.evidence} · {source.currentCertificate.reason}</p></> : <p>Servicio pendiente de certificación.</p>}{source.certificationBlockers.map((reason) => <p className="finance-warning" key={reason}>{reason}</p>)}
      {canFinanceV2(access, 'finance.write') ? <Button type="button" variant="secondary" disabled={!sectionReady(access, 'service-certificates') || intent.isPending || (source.certificationBlockers.length > 0 && !source.currentCertificate)} onClick={(event) => begin('CERTIFY_SERVICE', source, event.currentTarget)}>{source.currentCertificate ? 'Corregir certificación de servicio' : 'Certificar servicio prestado'}</Button> : null}
      {source.terminal ? <><p>Importe final {formatMoney(source.terminal.finalAmountMinor)} · servicio certificado {formatMoney(source.terminal.serviceAmountMinor)} · residual propuesto {source.terminal.suggestedResidualMinor === null ? 'Sin cobertura' : formatMoney(source.terminal.suggestedResidualMinor)}</p>{source.terminal.currentRecognition ? <p>Reconocimiento v{source.terminal.currentRecognition.version}: {formatMoney(source.terminal.currentRecognition.amountMinor)} · {source.terminal.currentRecognition.stale ? 'Fuente cambió; requiere revisión' : source.terminal.currentRecognition.coverage}</p> : <p>Residual pendiente de declaración.</p>}{source.terminal.blockers.map((reason) => <p key={reason}>{reason}</p>)}{canFinanceV2(access, 'finance.write') ? <Button type="button" variant="secondary" disabled={!sectionReady(access, 'terminal-recognitions') || intent.isPending || source.terminal.blockers.length > 0} onClick={(event) => begin('RECOGNIZE_TERMINAL', source, event.currentTarget)}>Reconocer importe no prestado</Button> : null}</> : null}</article>)}</div></section>
    {open && (form || intent.pendingCommand) ? <OverlayPanel open portal closeLabel="Cerrar declaración" label={label} className="finance-dialog" layerClassName="finance-dialog-layer" triggerRef={trigger} dismissible={!intent.isPending} onClose={() => setOpen(false)}><header><h2>{label}</h2><Button type="button" iconOnly variant="ghost" aria-label="Cerrar declaración" disabled={intent.isPending} onClick={() => setOpen(false)}><X size={20} aria-hidden="true" /></Button></header><form onSubmit={(event) => { event.preventDefault(); void submit(); }}><fieldset className="finance-form-body" disabled={intent.isPending || uncertain}>
    {form ? form.operation === 'CERTIFY_SERVICE' ? <>{form.source.currentCertificate ? <label className="finance-check"><input type="checkbox" checked={form.reverse} onChange={(event) => setForm({ ...form, reverse: event.target.checked })} />Revertir explícitamente la certificación anterior sin declarar noches</label> : null}{!form.reverse ? <fieldset className="finance-line"><legend>Noches realmente prestadas</legend>{form.source.eligibleNights.map((night) => <label className="finance-check" key={night}><input type="checkbox" checked={form.servedNights.includes(night)} onChange={(event) => setForm({ ...form, servedNights: event.target.checked ? [...form.servedNights, night] : form.servedNights.filter((value) => value !== night) })} />{formatPureDate(night)}</label>)}{!form.source.eligibleNights.length ? <p>No hay noches elegibles consultadas. Revisa sus bloqueos.</p> : null}</fieldset> : <p>El reverso conserva la fuente de la certificación anterior y añade una versión con motivo.</p>}<Input id="recognition-check-in" label="Fecha efectiva de entrada" type="date" required value={form.checkIn} onChange={(event) => setForm({ ...form, checkIn: event.target.value })} /><Input id="recognition-check-out" label="Fecha efectiva de salida (opcional)" type="date" value={form.checkOut} onChange={(event) => setForm({ ...form, checkOut: event.target.value })} /><Input id="recognition-evidence" label="Evidencia de prestación" required minLength={2} maxLength={500} value={form.evidence} onChange={(event) => setForm({ ...form, evidence: event.target.value })} /></> : <><p>El importe final {formatMoney(form.source.terminal!.finalAmountMinor)} procede de la revisión del servidor.</p><MoneyField id="recognition-residual" label="Importe confirmado que no corresponde al servicio" value={form.amount} onChange={(amount) => setForm({ ...form, amount })} /><SelectField id="recognition-coverage" label="Cobertura declarada" required value={form.coverage} onChange={(coverage) => setForm({ ...form, coverage: coverage as RecognitionForm['coverage'] })}><option value="">Selecciona cobertura</option><option value="COMPLETE">Cobertura completa declarada</option><option value="DECLARED_NONE">Declaro que no hay residual de servicio pendiente</option></SelectField><Input id="recognition-date" label="Fecha del reconocimiento" type="date" required value={form.recognitionOn} onChange={(event) => setForm({ ...form, recognitionOn: event.target.value })} /><Input id="recognition-classification" label="Clasificación del importe" required minLength={2} value={form.classification} onChange={(event) => setForm({ ...form, classification: event.target.value })} /></> : <p>Recupera la declaración pendiente con sus datos y clave originales.</p>}{form ? <Input id="recognition-reason" label="Motivo" required minLength={2} maxLength={500} value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} /> : null}</fieldset>
    {error ? <p role="alert" className="finance-form-error">{financeErrorMessage(error)}</p> : null}{uncertain ? <p role="status" className="finance-form-error">Resultado pendiente de verificar. El reintento conserva exactamente la declaración original.</p> : null}<footer><Button type="button" variant="secondary" disabled={intent.isPending} onClick={() => setOpen(false)}>Cerrar y conservar borrador</Button>{uncertain ? <Button type="button" loading={intent.isPending} disabled={!canFinanceV2(access, 'finance.write')} onClick={() => { void submit(true); }}>Reintentar el mismo registro</Button> : conflict ? <Button type="button" onClick={() => { void refresh(); }}>Consultar fuentes actuales</Button> : <Button type="submit" loading={intent.isPending} disabled={!form || !canFinanceV2(access, 'finance.write')}>Registrar</Button>}</footer></form></OverlayPanel> : null}</>;
}
