import {useQuery} from '@tanstack/react-query';
import {useEffect,useRef,useState} from 'react';
import {ApiError} from '../../../shared/api/api-client';
import {Button} from '../../../shared/ui/Button';
import type {FinanceContext} from '../api/finance-api';
import {getFinanceExpense} from '../api/finance-api';
import {FinanceError,financeErrorMessage} from '../components/FinanceFeedback';
import {downloadFinanceEvidence,getFinanceEvidence,prepareEvidenceFile,uploadFinanceEvidence,type EvidenceFileIntent} from './finance-evidence-api';
import type {FinanceEvidenceMetadataDto} from './finance-evidence.types';
import {useFinanceIntent} from './use-finance-intent';
import {financeV2Key} from './use-v2-command';
import {canFinanceV2,sectionReady,type FinanceV2Access} from './v2-ui.types';
export function FinanceEvidenceAttachmentPanel(props:{context:FinanceContext;access:FinanceV2Access;expenseId:string;expenseVersion:number|undefined}) {
  if(!canFinanceV2(props.access,'finance.evidence.read'))return <p>Adjuntos no habilitados. Puedes conservar una referencia textual del comprobante.</p>;
  return <AttachmentContent key={JSON.stringify([props.context.userId,props.context.businessId,props.expenseId])} {...props}/>;
}
function AttachmentContent({context,access,expenseId,expenseVersion}:{context:FinanceContext;access:FinanceV2Access;expenseId:string;expenseVersion:number|undefined}) {
  const query=useQuery({queryKey:[...financeV2Key(context),'evidence',expenseId],queryFn:({signal})=>getFinanceEvidence(context,expenseId,signal),enabled:sectionReady(access,'expense-evidence'),retry:false});
  const intent=useFinanceIntent(context,`evidence:${expenseId}`,uploadFinanceEvidence);
  const [file,setFile]=useState<EvidenceFileIntent|null>(null);const [version,setVersion]=useState(expenseVersion);const [error,setError]=useState<unknown>(null);const [notice,setNotice]=useState('');const [reading,setReading]=useState(false);const [downloading,setDownloading]=useState<string|null>(null);const input=useRef<HTMLInputElement|null>(null);const alive=useRef(true);const downloadController=useRef<AbortController|null>(null);
  useEffect(()=>{alive.current=true;return()=>{alive.current=false;downloadController.current?.abort();};},[]);
  useEffect(()=>{if(expenseVersion)setVersion(expenseVersion);},[expenseVersion]);
  const uncertain=intent.hasUncertainResult;const busy=reading||intent.isPending;const enabled=Boolean(query.data?.enabled)&&sectionReady(access,'expense-evidence');const write=enabled&&canFinanceV2(access,'finance.evidence.write');const selected=file??intent.pendingCommand;
  async function choose(chosen:File|undefined){if(!chosen)return;if(intent.hasUncertainResult||intent.isPending){setError(new Error('Verifica primero la carga pendiente antes de elegir otro archivo.'));return;}setReading(true);setError(null);try{if(!version)throw new Error('Consulta primero la versión vigente del gasto.');const prepared=await prepareEvidenceFile(chosen,expenseId,version);if(alive.current)setFile(prepared);}catch(failure){if(alive.current){setError(failure);setFile(null);if(input.current)input.current.value='';}}finally{if(alive.current)setReading(false);}}
  async function upload(retry=false){setError(null);try{if(!canFinanceV2(access,'finance.evidence.write')||!sectionReady(access,'expense-evidence'))throw new Error('Necesitas autorización vigente para cargar este comprobante.');const result=await(retry?intent.retry():intent.execute({...file!,expectedVersion:version!}));if(alive.current){setVersion(result.version);setFile(null);if(input.current)input.current.value='';setNotice('Comprobante adjunto conservado con su gasto y versión.');}}catch(failure){if(alive.current)setError(failure);}}
  async function refresh(){setReading(true);setError(null);try{const detail=await getFinanceExpense(context,expenseId);if(alive.current){setVersion(detail.expense.version);setNotice('Versión vigente consultada. Revisa el archivo antes de confirmar una nueva intención.');}await query.refetch();}catch(failure){if(alive.current)setError(failure);}finally{if(alive.current)setReading(false);}}
  async function download(metadata:FinanceEvidenceMetadataDto){setError(null);setDownloading(metadata.id);const controller=new AbortController();downloadController.current=controller;try{const blob=await downloadFinanceEvidence(context,metadata,controller.signal);if(alive.current&&!controller.signal.aborted){const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=metadata.filename;anchor.click();URL.revokeObjectURL(url);}}catch(failure){if(alive.current&&!controller.signal.aborted)setError(failure);}finally{if(alive.current)setDownloading(null);}}
  return <section className="finance-panel" aria-label="Comprobantes adjuntos del gasto"><header><h3>Comprobantes adjuntos</h3></header>{notice?<p role="status">{notice}</p>:null}{!enabled&&!query.isFetching?<p>Adjuntos no habilitados. La referencia textual del gasto sigue disponible.</p>:null}{query.isFetching?<p role="status">Consultando comprobantes del gasto.</p>:null}{query.isError?<FinanceError error={query.error} onRetry={()=>{void query.refetch();}}/>:null}{enabled?<p>PDF, JPEG o PNG, máximo 2 MiB por archivo. Los adjuntos se conservan sin purga.</p>:null}{enabled&&canFinanceV2(access,'finance.evidence.write')?<form className="finance-form-body" onSubmit={(event)=>{event.preventDefault();void upload();}}><label className="top-field" htmlFor={`finance-evidence-${expenseId}`}><span className="top-field__label">Archivo del comprobante</span><input ref={input} id={`finance-evidence-${expenseId}`} className="top-input" type="file" accept="application/pdf,image/jpeg,image/png" disabled={busy||uncertain||!version} onChange={(event)=>{void choose(event.currentTarget.files?.[0]);}}/></label>{selected?<p>Archivo original: {selected.filename} · {selected.mimeType} · {selected.sizeBytes} bytes</p>:null}{!uncertain?<Button type="submit" loading={busy} disabled={!file||!write||!version}>Adjuntar comprobante</Button>:null}</form>:selected?<p>Archivo original: {selected.filename} · {selected.mimeType} · {selected.sizeBytes} bytes</p>:null}{uncertain?<div><p role="status">Carga pendiente de verificar. Conservamos los bytes, el archivo, la versión y la clave originales para esta identidad y gasto.</p><Button type="button" loading={intent.isPending} disabled={!canFinanceV2(access,'finance.evidence.write')||!sectionReady(access,'expense-evidence')} onClick={()=>{void upload(true);}}>Reintentar la misma carga</Button></div>:null}{error?<p role="alert" className="finance-form-error">{financeErrorMessage(error)}</p>:null}{!uncertain&&error instanceof ApiError&&error.status===409?<Button type="button" variant="secondary" loading={reading} onClick={()=>{void refresh();}}>Consultar versión del gasto y conservar archivo</Button>:null}<div className="finance-v2-list">{query.data?.files.map((metadata)=><article key={metadata.id}><strong>{metadata.filename}</strong><p>{metadata.mimeType} · {metadata.sizeBytes} bytes · gasto versión {metadata.expenseVersion}</p><p>Registró {metadata.recordedByUserId} · {metadata.createdAt}</p><Button type="button" variant="secondary" loading={downloading===metadata.id} disabled={downloading!==null&&downloading!==metadata.id} onClick={()=>{void download(metadata);}}>Descargar {metadata.filename}</Button></article>)}</div></section>;
}
