import { Given, Then, When } from '@cucumber/cucumber';
import { strict as assert } from 'node:assert';
import request from 'supertest';
import { Block } from '../../../src/modules/block/domain/block.entity';
import { BlockStatus } from '../../../src/modules/block/domain/block-status.enum';
import { BlockType } from '../../../src/modules/block/domain/block-type.enum';
import { Booking } from '../../../src/modules/booking/domain/booking.entity';
import { BookingStatus } from '../../../src/modules/booking/domain/booking-status.enum';
import { Resource } from '../../../src/modules/resource/domain/resource.entity';
import { ResourceStatus } from '../../../src/modules/resource/domain/resource-status.enum';
import { addBlockFake } from '../support/block-repository.fake';
import { addBookingFake } from '../support/booking-repository.fake';
import { addResourceFake } from '../support/resource-repository.fake';
import { TopWorld } from '../support/world';

const businessId = 'f8c49800-e50e-4d0e-b82b-0b51c09a0001'; const otherBusinessId = 'f8c49800-e50e-4d0e-b82b-0b51c09a0002'; const resourceId = 'a8c49800-e50e-4d0e-b82b-0b51c09a0001';
const makeResource = (owner: string, status: ResourceStatus) => Resource.create({ id: resourceId, businessId: owner, name: 'Cabaña', internalCode: 'AVL01', description: null, capacityMinimum: 1, capacityMaximum: 2, capacityMaximumChildren: 0, status, sortOrder: 0, createdAt: new Date(), updatedAt: new Date() });
Given('existe un Resource activo para Availability', () => addResourceFake(makeResource(businessId, ResourceStatus.ACTIVE)));
Given('existe un Resource activo para el calendario', () => addResourceFake(makeResource(businessId, ResourceStatus.ACTIVE)));
Given('existe un Resource fuera de servicio para Availability', () => addResourceFake(makeResource(businessId, ResourceStatus.OUT_OF_SERVICE)));
Given('existe un Resource archivado para Availability', () => addResourceFake(makeResource(businessId, ResourceStatus.ARCHIVED)));
Given('existe un Resource de Availability en otro negocio', () => addResourceFake(makeResource(otherBusinessId, ResourceStatus.ACTIVE)));
Given('existe un Booking confirmado que bloquea el Resource', () => addBookingFake(Booking.create({ id: 'b8c49800-e50e-4d0e-b82b-0b51c09a0001', businessId, status: BookingStatus.CONFIRMED, contactId: null, resourceIds: [resourceId], checkInDate: new Date('2026-04-01'), checkOutDate: new Date('2026-04-03'), adults: null, children: null, notes: null, createdAt: new Date(), updatedAt: new Date() })));
Given('existe un Block que bloquea el Resource', () => addBlockFake(Block.create({ id: 'c8c49800-e50e-4d0e-b82b-0b51c09a0001', businessId, resourceId, type: BlockType.MAINTENANCE, reason: 'Mantenimiento', notes: null, startsAt: new Date('2026-04-01'), endsAt: new Date('2026-04-03'), status: BlockStatus.SCHEDULED, cancellationReason: null, cancelledAt: null, createdAt: new Date(), updatedAt: new Date() })));
When('consulto su disponibilidad', async function (this: TopWorld): Promise<void> { this.response = await request(this.app?.getHttpServer()).get(`/api/businesses/${businessId}/availability?resourceId=${resourceId}&from=2026-04-01&to=2026-04-03`); });
When('consulto su disponibilidad desde mi negocio', async function (this: TopWorld): Promise<void> { this.response = await request(this.app?.getHttpServer()).get(`/api/businesses/${businessId}/availability?resourceId=${resourceId}&from=2026-04-01&to=2026-04-03`); });
When('consulto un rango de disponibilidad inválido', async function (this: TopWorld): Promise<void> { this.response = await request(this.app?.getHttpServer()).get(`/api/businesses/${businessId}/availability?resourceId=${resourceId}&from=2026-04-03&to=2026-04-03`); });
When('consulto el calendario de disponibilidad', async function (this: TopWorld): Promise<void> { this.response = await request(this.app?.getHttpServer()).get(`/api/businesses/${businessId}/availability/calendar?from=2026-04-01&to=2026-04-03`); });
When('consulto un rango de calendario mayor a 31 días', async function (this: TopWorld): Promise<void> { this.response = await request(this.app?.getHttpServer()).get(`/api/businesses/${businessId}/availability/calendar?from=2026-04-01&to=2026-05-03`); });
When('consulto ese Resource en el calendario desde mi negocio', async function (this: TopWorld): Promise<void> { this.response = await request(this.app?.getHttpServer()).get(`/api/businesses/${businessId}/availability/calendar?from=2026-04-01&to=2026-04-03&resourceId=${resourceId}`); });
Then('recibo disponibilidad AVAILABLE', function (this: TopWorld): void { assert.equal(this.response?.status, 200); assert.equal(this.response?.body.status, 'AVAILABLE'); assert.deepEqual(this.response?.body.reasons, []); });
Then('recibo razón {word}', function (this: TopWorld, reason: string): void { assert.equal(this.response?.status, 200); assert.deepEqual(this.response?.body.reasons, [reason]); });
Then('recibo ambas razones de conflicto', function (this: TopWorld): void { assert.deepEqual(this.response?.body.reasons, ['BOOKING_CONFLICT', 'BLOCK_CONFLICT']); });
Then('recibo una celda AVAILABLE del calendario', function (this: TopWorld): void { assert.equal(this.response?.status, 200); assert.deepEqual(this.response?.body.resources[0].days[0], { date: '2026-04-01', status: 'AVAILABLE', reasons: [] }); });
Then('recibo ambas razones de conflicto en el calendario', function (this: TopWorld): void { assert.deepEqual(this.response?.body.resources[0].days[0].reasons, ['BOOKING_CONFLICT', 'BLOCK_CONFLICT']); });
Then('recibo razón {word} en el calendario', function (this: TopWorld, reason: string): void { assert.equal(this.response?.status, 200); assert.deepEqual(this.response?.body.resources[0].days[0].reasons, [reason]); });
