import { useState, type FormEvent } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { ArrowLeft, CheckCircle2 } from "lucide-react";
import { useMutation } from "@tanstack/react-query";
import { resetPassword } from "../api/reset-password";
import { ApiError } from "../../../shared/api/api-client";
import { Button } from "../../../shared/ui/Button";
import { Input } from "../../../shared/ui/Input";
import { AuthPageShell } from "../components/AuthPageShell";
export function ResetPasswordPage() { const [params] = useSearchParams(); const token = params.get("token") ?? sessionStorage.getItem("top.auth.reset-grant.v1") ?? ""; const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [validation, setValidation] = useState<string | null>(null); const mutation = useMutation({ mutationFn: () => resetPassword(token, password), onSuccess: () => sessionStorage.removeItem("top.auth.reset-grant.v1") }); const submit = (event: FormEvent) => { event.preventDefault(); if (!token) return setValidation("No hay un código de recuperación activo."); if (password.length < 12) return setValidation("Usá entre 12 y 128 caracteres."); if (password !== confirm) return setValidation("Las contraseñas no coinciden."); setValidation(null); void mutation.mutateAsync(); }; return <AuthPageShell labelledBy="reset-title"><Link className="top-auth-back" to="/login"><ArrowLeft size={16} aria-hidden="true" /> Volver al inicio de sesión</Link><div className="top-auth-mobile-brand">TOP<span>Gestión de alojamientos</span></div><header className="top-auth-header"><CheckCircle2 size={30} aria-hidden="true" /><h1 id="reset-title" className="top-auth-title">Elegí una nueva contraseña</h1><p className="top-auth-description">La nueva contraseña debe tener entre 12 y 128 caracteres.</p></header>{mutation.isSuccess ? <div className="top-auth-success-state" role="status"><CheckCircle2 size={42} aria-hidden="true" /><h2>Contraseña actualizada</h2><p>Ya podés iniciar sesión con tu nueva contraseña.</p><Link className="top-button top-button--primary" to="/login">Iniciar sesión</Link></div> : <form className="top-auth-form" onSubmit={submit} noValidate><Input label="Nueva contraseña" type="password" autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} required /><Input label="Repetir contraseña" type="password" autoComplete="new-password" value={confirm} onChange={(event) => setConfirm(event.target.value)} required />{validation || mutation.error ? <div className="top-auth-error" role="alert">{validation ?? (mutation.error instanceof ApiError ? mutation.error.message : "No pudimos restablecer la contraseña.")}</div> : null}<Button type="submit" size="lg" loading={mutation.isPending} loadingLabel="Guardando...">Guardar contraseña</Button></form>}</AuthPageShell>; }
