import { useEffect, useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowRight, Eye, EyeOff, MailCheck } from "lucide-react";
import { useMutation } from "@tanstack/react-query";
import { signup } from "../api/signup";
import { ApiError } from "../../../shared/api/api-client";
import { Button } from "../../../shared/ui/Button";
import { Input } from "../../../shared/ui/Input";
import { AuthPageShell } from "../components/AuthPageShell";
import { resendVerification } from "../api/resend-verification";

export function SignupPage() {
  const [step, setStep] = useState(1); const [displayName, setDisplayName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [businessName, setBusinessName] = useState(""); const [timezone, setTimezone] = useState("America/Asuncion"); const [error, setError] = useState<string | null>(null); const [showPassword, setShowPassword] = useState(false);
  const mutation = useMutation({ mutationFn: () => signup({ displayName, email, password, businessName, timezone }) });
  const resendMutation = useMutation({ mutationFn: () => resendVerification(mutation.data?.email ?? email) });
  const [resendSeconds, setResendSeconds] = useState(0);
  useEffect(() => { if (resendSeconds <= 0) return undefined; const timer = window.setInterval(() => setResendSeconds((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, [resendSeconds]);
  const resend = () => { if (resendSeconds > 0 || resendMutation.isPending) return; void resendMutation.mutateAsync().then(() => setResendSeconds(60)); };
  const continueStep = (event: FormEvent) => { event.preventDefault(); if (displayName.trim().length === 0 || displayName.trim().length > 120 || !email.includes("@") || password.length < 12 || password.length > 128 || password !== confirm) { setError(password !== confirm ? "Las contraseñas no coinciden." : "Revisá los datos ingresados."); return; } setError(null); setStep(2); };
  const submit = (event: FormEvent) => { event.preventDefault(); if (!businessName.trim() || !timezone) { setError("Completá los datos de tu alojamiento."); return; } setError(null); void mutation.mutateAsync(); };
  if (mutation.isSuccess) return <AuthPageShell labelledBy="signup-success-title"><div className="top-auth-success-state"><MailCheck size={42} aria-hidden="true" /><h1 id="signup-success-title">Revisá tu correo</h1><p>Te enviamos un enlace para verificar tu cuenta.</p><p>{maskEmail(mutation.data.email)}</p><button type="button" className="top-button top-button--secondary" onClick={resend} disabled={resendSeconds > 0 || resendMutation.isPending}>{resendSeconds > 0 ? `Reenviar en ${resendSeconds}s` : "Reenviar correo"}</button>{resendMutation.isSuccess ? <p role="status">Si la cuenta puede recibir un enlace, te enviaremos uno nuevo.</p> : null}<Link className="top-button top-button--primary" to="/login">Volver al inicio de sesión</Link></div></AuthPageShell>;
  return <AuthPageShell labelledBy="signup-title"><Link className="top-auth-back" to="/login"><ArrowLeft size={16} aria-hidden="true" /> Volver al inicio de sesión</Link><header className="top-auth-header"><h1 id="signup-title" className="top-auth-title">{step === 1 ? "Creá tu cuenta" : "Contanos sobre tu alojamiento"}</h1><p className="top-auth-description">{step === 1 ? "Empezá a gestionar tu alojamiento con TOP." : "Configurá tu espacio inicial en TOP."}</p></header><form className="top-auth-form" onSubmit={step === 1 ? continueStep : submit} noValidate>{step === 1 ? <><Input label="Nombre completo" value={displayName} onChange={(e) => setDisplayName(e.target.value)} required /><Input label="Correo electrónico" type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /><div className="top-password-field"><Input label="Contraseña" type={showPassword ? "text" : "password"} value={password} onChange={(e) => setPassword(e.target.value)} required /><button type="button" className="top-password-field__toggle" aria-label={showPassword ? "Ocultar contraseña" : "Mostrar contraseña"} onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff size={18} /> : <Eye size={18} />}</button></div><Input label="Confirmar contraseña" type="password" value={confirm} onChange={(e) => setConfirm(e.target.value)} required /><Button type="submit" size="lg">Continuar <ArrowRight size={18} /></Button></> : <><Input label="Nombre del alojamiento" value={businessName} onChange={(e) => setBusinessName(e.target.value)} required /><label className="top-field"><span className="top-field__label">Zona horaria</span><select className="top-input" value={timezone} onChange={(e) => setTimezone(e.target.value)}><option value="America/Asuncion">America/Asuncion</option><option value="America/Argentina/Buenos_Aires">America/Argentina/Buenos_Aires</option><option value="America/Sao_Paulo">America/Sao_Paulo</option></select></label><div className="top-auth-options"><Button type="button" variant="secondary" onClick={() => setStep(1)}>Volver</Button><Button type="submit" size="lg" loading={mutation.isPending}>Crear cuenta</Button></div></>}{error || mutation.error ? <div className="top-auth-error" role="alert">{error ?? (mutation.error instanceof ApiError && mutation.error.status === 409 ? "Ya existe una cuenta con este correo." : "No pudimos crear tu cuenta.")}</div> : null}</form><p className="top-auth-footnote">¿Ya tenés una cuenta? <Link className="top-auth-forgot" to="/login">Iniciar sesión</Link></p></AuthPageShell>;
}
function maskEmail(email: string): string { const [name, domain] = email.split("@"); return name && domain ? `${name[0]}•••••@${domain}` : email; }
