import type { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import request from 'supertest';
import { AppModule } from '../../src/app.module';
import { configureApplication } from '../../src/config/configure-application';
import { BLOCK_REPOSITORY } from '../../src/modules/block/domain/block.repository';
import { Block } from '../../src/modules/block/domain/block.entity';
import { BlockStatus } from '../../src/modules/block/domain/block-status.enum';
import { BlockType } from '../../src/modules/block/domain/block-type.enum';
import { Business } from '../../src/modules/business/domain/business.entity';
import { BUSINESS_REPOSITORY } from '../../src/modules/business/domain/business.repository';
import { BusinessStatus } from '../../src/modules/business/domain/business-status.enum';
import { Resource } from '../../src/modules/resource/domain/resource.entity';
import { RESOURCE_REPOSITORY } from '../../src/modules/resource/domain/resource.repository';
import { ResourceStatus } from '../../src/modules/resource/domain/resource-status.enum';

const businessId = '11111111-1111-4111-8111-111111111111'; const otherBusinessId = '22222222-2222-4222-8222-222222222222'; const resourceId = '33333333-3333-4333-8333-333333333333'; const blockId = '44444444-4444-4444-8444-444444444444';
const business = (id: string, status = BusinessStatus.ACTIVE) => Business.create({ id, businessNumber: null, name: 'TOP', legalName: null, taxId: null, timezone: 'America/Asuncion', currency: 'PYG', status, createdAt: new Date(), updatedAt: new Date() });
const resource = (id: string, owner: string, status = ResourceStatus.ACTIVE) => Resource.create({ id, businessId: owner, name: 'Cabaña', internalCode: id, description: null, capacityMinimum: 1, capacityMaximum: 2, capacityMaximumChildren: 0, status, sortOrder: 0, createdAt: new Date(), updatedAt: new Date() });

describe('Block endpoint', () => {
  let app: INestApplication; let blocks: Block[]; let businesses: Business[]; let resources: Resource[];
  beforeAll(async () => {
    const module = await Test.createTestingModule({ imports: [AppModule] }).overrideProvider(BUSINESS_REPOSITORY).useValue({ findById: (id: string) => Promise.resolve(businesses.find((item) => item.id === id) ?? null), create: jest.fn(), list: jest.fn(), update: jest.fn() }).overrideProvider(RESOURCE_REPOSITORY).useValue({ findByIdAndBusinessId: (id: string, owner: string) => Promise.resolve(resources.find((item) => item.id === id && item.businessId === owner) ?? null), findByBusinessAndCode: jest.fn(), listByBusinessId: jest.fn(), create: jest.fn(), update: jest.fn() }).overrideProvider(BLOCK_REPOSITORY).useValue({ create: (data: { businessId: string; resourceId: string; type: BlockType; reason: string; notes: string | null; startsAt: Date; endsAt: Date }) => { const created = Block.create({ id: blockId, ...data, status: BlockStatus.SCHEDULED, cancellationReason: null, cancelledAt: null, createdAt: new Date(), updatedAt: new Date() }); blocks.push(created); return Promise.resolve(created); }, findByIdAndBusinessId: (id: string, owner: string) => Promise.resolve(blocks.find((item) => item.id === id && item.businessId === owner) ?? null), listByBusinessId: (owner: string, filters: { resourceId?: string; from?: Date; to?: Date }) => Promise.resolve(blocks.filter((item) => item.businessId === owner && (filters.resourceId === undefined || item.resourceId === filters.resourceId) && (filters.from === undefined || item.endsAt > filters.from) && (filters.to === undefined || item.startsAt < filters.to)).sort((left, right) => left.startsAt.getTime() - right.startsAt.getTime() || left.endsAt.getTime() - right.endsAt.getTime() || left.id.localeCompare(right.id))), update: (changed: Block) => { blocks = blocks.map((item) => item.id === changed.id ? changed : item); return Promise.resolve(changed); } }).compile();
    app = module.createNestApplication(); configureApplication(app); await app.init();
  });
  afterAll(async () => app.close());
  beforeEach(() => { blocks = []; businesses = [business(businessId), business(otherBusinessId)]; resources = [resource(resourceId, businessId), resource('55555555-5555-4555-8555-555555555555', otherBusinessId)]; });
  const body = { type: BlockType.MAINTENANCE, reason: ' Mantenimiento ', notes: ' Limpieza ', startsAt: '2026-12-20T10:00:00-03:00', endsAt: '2026-12-21T10:00:00-03:00' };
  it('creates, lists and cancels a public block', async () => { await request(app.getHttpServer()).post(`/api/businesses/${businessId}/resources/${resourceId}/blocks`).send(body).expect(201).expect(({ body: result }: { body: Record<string, unknown> }) => { expect(result).toMatchObject({ status: 'SCHEDULED', reason: 'Mantenimiento', notes: 'Limpieza' }); expect(result).not.toHaveProperty('props'); }); await request(app.getHttpServer()).get(`/api/businesses/${businessId}/blocks?resourceId=${resourceId}`).expect(200).expect(({ body: result }: { body: unknown[] }) => expect(result).toHaveLength(1)); await request(app.getHttpServer()).patch(`/api/businesses/${businessId}/blocks/${blockId}/cancel`).send({ reason: 'Cambio' }).expect(200).expect(({ body: result }: { body: Record<string, unknown> }) => expect(result).toMatchObject({ status: 'CANCELLED', cancellationReason: 'Cambio' })); });
  it('returns 400 for invalid inputs and intervals', async () => { await request(app.getHttpServer()).post(`/api/businesses/${businessId}/resources/${resourceId}/blocks`).send({ ...body, startsAt: '2026-12-20' }).expect(400); await request(app.getHttpServer()).post(`/api/businesses/${businessId}/resources/${resourceId}/blocks`).send({ ...body, endsAt: body.startsAt }).expect(400); await request(app.getHttpServer()).get(`/api/businesses/${businessId}/blocks?resourceId=invalid`).expect(400); });
  it('hides cross-tenant and rejects archived resources while allowing OUT_OF_SERVICE', async () => { await request(app.getHttpServer()).post(`/api/businesses/${businessId}/resources/55555555-5555-4555-8555-555555555555/blocks`).send(body).expect(404); resources[0] = resource(resourceId, businessId, ResourceStatus.ARCHIVED); await request(app.getHttpServer()).post(`/api/businesses/${businessId}/resources/${resourceId}/blocks`).send(body).expect(409); resources[0] = resource(resourceId, businessId, ResourceStatus.OUT_OF_SERVICE); await request(app.getHttpServer()).post(`/api/businesses/${businessId}/resources/${resourceId}/blocks`).send(body).expect(201); });
  it('returns 404 for foreign blocks and 409 for finished blocks', async () => { blocks = [Block.create({ id: blockId, businessId: otherBusinessId, resourceId, type: BlockType.OTHER, reason: 'Otro', notes: null, startsAt: new Date('2020-01-01'), endsAt: new Date('2020-01-02'), status: BlockStatus.SCHEDULED, cancellationReason: null, cancelledAt: null, createdAt: new Date(), updatedAt: new Date() })]; await request(app.getHttpServer()).patch(`/api/businesses/${businessId}/blocks/${blockId}/cancel`).send({ reason: 'Cambio' }).expect(404); blocks = [Block.create({ id: blockId, businessId, resourceId, type: BlockType.OTHER, reason: 'Otro', notes: null, startsAt: new Date('2020-01-01'), endsAt: new Date('2020-01-02'), status: BlockStatus.SCHEDULED, cancellationReason: null, cancelledAt: null, createdAt: new Date(), updatedAt: new Date() })]; await request(app.getHttpServer()).patch(`/api/businesses/${businessId}/blocks/${blockId}/cancel`).send({ reason: 'Cambio' }).expect(409); });
});
