import type { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import type { NextFunction, Response } from 'express';
import request from 'supertest';
import { AppModule } from '../../src/app.module';
import { configureApplication } from '../../src/config/configure-application';
import { BOOKING_REPOSITORY } from '../../src/modules/booking/booking.contract';
import { Booking } from '../../src/modules/booking/domain/booking.entity';
import { BookingStatus } from '../../src/modules/booking/domain/booking-status.enum';
import { BUSINESS_REPOSITORY } from '../../src/modules/business/business.contract';
import { Business } from '../../src/modules/business/domain/business.entity';
import { BusinessStatus } from '../../src/modules/business/domain/business-status.enum';
import { PAYMENT_PLAN_REPOSITORY, type CreatePaymentPlanData, type PaymentPlan } from '../../src/modules/payment/domain/payment-plan';
import { PAYMENT_REPOSITORY, PaymentMethod, PaymentStatus, type Payment, type RegisterPaymentData } from '../../src/modules/payment/domain/payment';
import { PRICING_SNAPSHOT_REPOSITORY } from '../../src/modules/pricing/pricing.contract';

const businessId = '11111111-1111-4111-8111-111111111111'; const otherBusinessId = '22222222-2222-4222-8222-222222222222'; const bookingId = '33333333-3333-4333-8333-333333333333'; const actorUserId = '44444444-4444-4444-8444-444444444444';
const business = (id: string, status = BusinessStatus.ACTIVE) => Business.create({ id, businessNumber: null, name: id, legalName: null, taxId: null, timezone: 'America/Asuncion', currency: 'PYG', status, createdAt: new Date(), updatedAt: new Date() });
const booking = (owner: string, status = BookingStatus.CONFIRMED) => Booking.create({ id: bookingId, businessId: owner, status, contactId: null, resourceIds: [], checkInDate: null, checkOutDate: null, adults: null, children: null, notes: null, createdAt: new Date(), updatedAt: new Date() });

describe('Payment Plan API', () => {
  let app: INestApplication; let businesses: Business[]; let currentBooking: Booking; let currentPlan: PaymentPlan | null; let payments: Payment[]; let authenticated: boolean;
  const apply = (plan: PaymentPlan, payment: Payment): void => { let remaining = payment.amountMinor; for (const installment of plan.installments) { const amount = Math.min(remaining, installment.amountMinor - installment.appliedAmountMinor); installment.appliedAmountMinor += amount; remaining -= amount; if (remaining === 0) break; } };
  const planRepository = {
    create: (data: CreatePaymentPlanData): Promise<PaymentPlan> => { if (currentPlan) return Promise.reject(new Error('PAYMENT_PLAN_EXISTS')); const now = new Date(); currentPlan = { id: 'plan-id', businessId: data.businessId, bookingId: data.bookingId, currency: data.currency, totalAmountMinor: data.totalAmountMinor, createdByUserId: data.actorUserId, updatedByUserId: data.actorUserId, createdAt: now, updatedAt: now, installments: data.installments.map((item, index) => ({ id: `installment-${index}`, ...item, appliedAmountMinor: 0 })) }; payments.forEach((payment) => apply(currentPlan!, payment)); return Promise.resolve(currentPlan); },
    findByBooking: ({ businessId: owner, bookingId: id }: { businessId: string; bookingId: string }): Promise<PaymentPlan | null> => Promise.resolve(currentPlan?.businessId === owner && currentPlan.bookingId === id ? currentPlan : null),
    replace: (data: CreatePaymentPlanData): Promise<PaymentPlan> => { if (!currentPlan) return Promise.reject(new Error('PAYMENT_PLAN_NOT_FOUND')); if (currentPlan.installments.some((item) => item.appliedAmountMinor > 0)) return Promise.reject(new Error('PAYMENT_PLAN_HAS_APPLICATIONS')); currentPlan = { ...currentPlan, updatedByUserId: data.actorUserId, updatedAt: new Date(), installments: data.installments.map((item, index) => ({ id: `replacement-${index}`, ...item, appliedAmountMinor: 0 })) }; return Promise.resolve(currentPlan); },
  };
  const paymentRepository = { register: (data: RegisterPaymentData, total: number) => { const prior = payments.find((item) => item.idempotencyKey === data.idempotencyKey && item.businessId === data.businessId); if (prior) return prior.requestFingerprint === data.requestFingerprint ? Promise.resolve({ payment: prior, duplicate: true }) : Promise.reject(new Error('IDEMPOTENCY_CONFLICT')); if (payments.reduce((sum, item) => sum + item.amountMinor, 0) + data.amountMinor > total) return Promise.reject(new Error('OVERPAYMENT')); const payment: Payment = { id: `payment-${payments.length}`, ...data, createdAt: new Date() }; payments.push(payment); if (currentPlan) apply(currentPlan, payment); return Promise.resolve({ payment, duplicate: false }); } };

  beforeAll(async () => { const module = await Test.createTestingModule({ imports: [AppModule] }).overrideProvider(BUSINESS_REPOSITORY).useValue({ findById: (id: string) => Promise.resolve(businesses.find((item) => item.id === id) ?? null), create: jest.fn(), list: jest.fn(), update: jest.fn() }).overrideProvider(BOOKING_REPOSITORY).useValue({ findByIdAndBusinessId: (id: string, owner: string) => Promise.resolve(currentBooking.id === id && currentBooking.businessId === owner ? currentBooking : null), create: jest.fn(), listByBusinessId: jest.fn(), update: jest.fn(), markPending: jest.fn(), markCancelled: jest.fn(), hasBlockingBooking: jest.fn(), listBlockingBookings: jest.fn() }).overrideProvider(PRICING_SNAPSHOT_REPOSITORY).useValue({ findByBookingId: (id: string) => Promise.resolve(id === bookingId ? { id: 'snapshot', businessId: currentBooking.businessId, bookingId, currency: 'PYG', totalAmountMinor: 100, items: [], createdAt: new Date() } : null), create: jest.fn() }).overrideProvider(PAYMENT_PLAN_REPOSITORY).useValue(planRepository).overrideProvider(PAYMENT_REPOSITORY).useValue(paymentRepository).compile(); app = module.createNestApplication(); app.use((req: { authenticatedPrincipal?: { userId: string } }, _res: Response, next: NextFunction) => { if (authenticated) req.authenticatedPrincipal = { userId: actorUserId }; next(); }); configureApplication(app, { security: false }); await app.init(); });
  afterAll(async () => app.close()); beforeEach(() => { businesses = [business(businessId), business(otherBusinessId)]; currentBooking = booking(businessId); currentPlan = null; payments = []; authenticated = true; });
  const endpoint = (owner = businessId) => `/api/businesses/${owner}/bookings/${bookingId}/payment-plan`; const body = { installments: [{ amountMinor: 40, dueDate: '2026-10-01' }, { amountMinor: 60, dueDate: null }] };

  it('creates, gets and replaces an unapplied plan without exposing internals', async () => { const created = await request(app.getHttpServer()).post(endpoint()).send(body).expect(201); expect(created.body).toMatchObject({ bookingId, currency: 'PYG', totalAmountMinor: 100, installments: [{ amountMinor: 40, sortOrder: 0, appliedAmountMinor: 0, outstandingAmountMinor: 40 }, { amountMinor: 60, sortOrder: 1 }] }); expect(created.body).not.toHaveProperty('businessId'); await request(app.getHttpServer()).get(endpoint()).expect(200); const replaced = await request(app.getHttpServer()).put(endpoint()).send({ installments: [{ amountMinor: 100, dueDate: null }] }).expect(200); expect(replaced.body.installments).toHaveLength(1); });
  it('returns 400 for invalid installments and 409 for sum mismatch or duplicate plan', async () => { await request(app.getHttpServer()).post(endpoint()).send({ installments: [] }).expect(400); await request(app.getHttpServer()).post(endpoint()).send({ installments: Array.from({ length: 101 }, () => ({ amountMinor: 1 })) }).expect(400); await request(app.getHttpServer()).post(endpoint()).send({ installments: [{ amountMinor: 99 }] }).expect(409); await request(app.getHttpServer()).post(endpoint()).send(body).expect(201); await request(app.getHttpServer()).post(endpoint()).send(body).expect(409); });
  it('applies an existing Payment and blocks replacement after the first application', async () => { const data: RegisterPaymentData = { businessId, bookingId, amountMinor: 50, currency: 'PYG', method: PaymentMethod.CASH, reference: null, note: null, paidAt: new Date('2026-09-01'), recordedByUserId: actorUserId, status: PaymentStatus.RECORDED, idempotencyKey: 'advance', requestFingerprint: 'advance' }; await paymentRepository.register(data, 100); const created = await request(app.getHttpServer()).post(endpoint()).send(body).expect(201); expect(created.body.installments.map((item: { appliedAmountMinor: number }) => item.appliedAmountMinor)).toEqual([40, 10]); await request(app.getHttpServer()).put(endpoint()).send(body).expect(409); });
  it.each([BookingStatus.COMPLETED, BookingStatus.CANCELLED, BookingStatus.NO_SHOW])('keeps historical GET available for %s', async (status) => { await request(app.getHttpServer()).post(endpoint()).send(body).expect(201); currentBooking = booking(businessId, status); await request(app.getHttpServer()).get(endpoint()).expect(200).expect(({ body: response }) => expect(response.bookingId).toBe(bookingId)); });
  it('returns 401 without an actor, 404 cross-tenant and 409 for archived Business or invalid Booking status', async () => { authenticated = false; await request(app.getHttpServer()).post(endpoint()).send(body).expect(401); authenticated = true; await request(app.getHttpServer()).post(endpoint(otherBusinessId)).send(body).expect(404); businesses = [business(businessId, BusinessStatus.ARCHIVED), business(otherBusinessId)]; await request(app.getHttpServer()).post(endpoint()).send(body).expect(409); businesses = [business(businessId), business(otherBusinessId)]; currentBooking = booking(businessId, BookingStatus.COMPLETED); await request(app.getHttpServer()).post(endpoint()).send(body).expect(409); });
});
