import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { BusinessProvider, useBusinessContext } from "./BusinessContext";

const auth = vi.hoisted(() => ({ current: { session: null as any, status: "unauthenticated" as string } }));
const list = vi.hoisted(() => vi.fn());
vi.mock("../../auth/context/AuthContext", () => ({ useAuth: () => auth.current }));
vi.mock("../api/list-businesses", () => ({ listBusinesses: (...args: unknown[]) => list(...args) }));

const business = (id: string, status = "ACTIVE") => ({ id, name: id, legalName: null, taxId: null, timezone: "America/Asuncion", currency: "PYG", status, createdAt: "2026-01-01", updatedAt: "2026-01-01" });
function Probe() { const value = useBusinessContext(); return <><output>{JSON.stringify({ status: value.status, id: value.activeBusinessId, role: value.activeRole, membership: value.activeMembership?.businessId ?? null })}</output><button onClick={value.retry}>Retry</button></>; }
function show() { return render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}><BusinessProvider><Probe /></BusinessProvider></QueryClientProvider>); }
function authenticated(businessId = "business-a") { auth.current = { status: "authenticated", session: { accessToken: "token", user: { id: "user-a" }, memberships: [{ businessId, role: "OWNER" }] } }; }

describe("BusinessProvider", () => {
  beforeEach(() => { list.mockReset(); auth.current = { session: null, status: "unauthenticated" }; });
  it("does not request businesses while restoring or anonymous", async () => { auth.current.status = "restoring"; show(); expect(list).not.toHaveBeenCalled(); auth.current.status = "unauthenticated"; show(); expect(list).not.toHaveBeenCalled(); });
  it("handles zero, one and multiple active businesses", async () => { authenticated(); list.mockResolvedValueOnce([]); const first = show(); await waitFor(() => expect(screen.getAllByRole("status")[0]).toHaveTextContent('"status":"empty"')); first.unmount(); authenticated(); list.mockResolvedValueOnce([business("business-a")]); show(); await waitFor(() => expect(screen.getByRole("status")).toHaveTextContent('"status":"ready","id":"business-a","role":"OWNER","membership":"business-a"')); });
  it("requires selection for multiple businesses and fails closed on mismatch", async () => { authenticated(); auth.current.session.memberships.push({ businessId: "business-b", role: "ADMIN" }); list.mockResolvedValueOnce([business("business-a"), business("business-b")]); const first = show(); await waitFor(() => expect(screen.getAllByRole("status")[0]).toHaveTextContent('"status":"selection-required","id":"","role":null,"membership":null')); first.unmount(); authenticated("other"); list.mockResolvedValueOnce([business("business-a")]); show(); await waitFor(() => expect(screen.getByRole("status")).toHaveTextContent('"status":"error","id":"","role":null,"membership":null')); });
  it("does not select suspended or archived businesses", async () => { authenticated(); list.mockResolvedValueOnce([business("business-a", "SUSPENDED")]); const first = show(); await waitFor(() => expect(screen.getAllByRole("status")[0]).toHaveTextContent('"status":"empty"')); first.unmount(); list.mockResolvedValueOnce([business("business-a", "ARCHIVED")]); show(); await waitFor(() => expect(screen.getByRole("status")).toHaveTextContent('"status":"empty"')); });
  it("exposes error and retries business discovery", async () => { authenticated(); list.mockRejectedValueOnce(new Error("network")).mockResolvedValueOnce([business("business-a")]); show(); await waitFor(() => expect(screen.getByRole("status")).toHaveTextContent('"status":"error","id":"","role":null,"membership":null')); fireEvent.click(screen.getByRole("button", { name: "Retry" })); await waitFor(() => expect(screen.getByRole("status")).toHaveTextContent('"status":"ready","id":"business-a"')); expect(list).toHaveBeenCalledTimes(2); });
  it("isolates business state when the authenticated user changes", async () => { authenticated("business-a"); list.mockResolvedValueOnce([business("business-a")]).mockResolvedValueOnce([business("business-b")]); const view = show(); await waitFor(() => expect(screen.getByRole("status")).toHaveTextContent('"id":"business-a"')); auth.current = { status: "authenticated", session: { accessToken: "token-b", user: { id: "user-b" }, memberships: [{ businessId: "business-b", role: "ADMIN" }] } }; view.rerender(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}><BusinessProvider><Probe /></BusinessProvider></QueryClientProvider>); await waitFor(() => expect(screen.getByRole("status")).toHaveTextContent('"status":"ready","id":"business-b","role":"ADMIN"')); expect(list).toHaveBeenLastCalledWith("token-b"); });
  it("clears the active business when auth is reset", async () => { authenticated(); list.mockResolvedValueOnce([business("business-a")]); const view = show(); await waitFor(() => expect(screen.getByRole("status")).toHaveTextContent('"id":"business-a"')); auth.current = { status: "unauthenticated", session: null }; view.rerender(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}><BusinessProvider><Probe /></BusinessProvider></QueryClientProvider>); await waitFor(() => expect(screen.getByRole("status")).toHaveTextContent('"status":"loading","id":"","role":null,"membership":null')); expect(list).toHaveBeenCalledTimes(1); });
  it("restores from auth restoring to authenticated", async () => { auth.current = { status: "restoring", session: null }; list.mockResolvedValueOnce([business("business-a")]); const view = show(); expect(list).not.toHaveBeenCalled(); auth.current = { status: "authenticated", session: { accessToken: "token", user: { id: "user-a" }, memberships: [{ businessId: "business-a", role: "OWNER" }] } }; view.rerender(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}><BusinessProvider><Probe /></BusinessProvider></QueryClientProvider>); await waitFor(() => expect(screen.getByRole("status")).toHaveTextContent('"status":"ready","id":"business-a"')); expect(list).toHaveBeenCalledTimes(1); });
});
