import { BadRequestException, ConflictException, NotFoundException } from '@nestjs/common';
import { Booking } from '../domain/booking.entity';
import { BookingStatus } from '../domain/booking-status.enum';
import { BookingAvailabilityConflictError, BookingNotDraftError, BookingNotFoundError, InvalidBookingInputError } from '../application/booking.errors';
import { BookingController } from './booking.controller';

const businessId = '11111111-1111-4111-8111-111111111111'; const bookingId = '22222222-2222-4222-8222-222222222222';
const booking = Booking.create({ id: bookingId, businessId, status: BookingStatus.DRAFT, contactId: null, resourceIds: [], checkInDate: null, checkOutDate: null, adults: null, children: null, notes: null, createdAt: new Date(), updatedAt: new Date() });
describe('BookingController', () => {
  const create = { execute: jest.fn() }; const get = { execute: jest.fn() }; const list = { execute: jest.fn() }; const update = { execute: jest.fn() }; const submit = { execute: jest.fn() }; const controller = new BookingController(create as never, get as never, list as never, update as never, submit as never);
  beforeEach(() => jest.resetAllMocks());
  it('delegates create, get, list and update with exact public responses', async () => { create.execute.mockResolvedValueOnce(booking); get.execute.mockResolvedValueOnce(booking); list.execute.mockResolvedValueOnce([booking]); update.execute.mockResolvedValueOnce(booking); await expect(controller.createBooking(businessId, {})).resolves.toMatchObject({ id: bookingId, resourceIds: [] }); await expect(controller.get(businessId, bookingId)).resolves.toMatchObject({ id: bookingId }); await expect(controller.listBookings(businessId, { status: 'DRAFT' })).resolves.toHaveLength(1); await expect(controller.update(businessId, bookingId, { notes: 'nota' })).resolves.toMatchObject({ notes: null }); expect(create.execute).toHaveBeenCalledWith({ businessId }); expect(update.execute).toHaveBeenCalledWith({ businessId, bookingId, notes: 'nota' }); });
  it('maps validated errors to the public HTTP exceptions and propagates unexpected errors', async () => { create.execute.mockRejectedValueOnce(new InvalidBookingInputError('bad')); await expect(controller.createBooking(businessId, {})).rejects.toBeInstanceOf(BadRequestException); get.execute.mockRejectedValueOnce(new BookingNotFoundError('missing')); await expect(controller.get(businessId, bookingId)).rejects.toBeInstanceOf(NotFoundException); update.execute.mockRejectedValueOnce(new BookingNotDraftError('conflict')); await expect(controller.update(businessId, bookingId, {})).rejects.toBeInstanceOf(ConflictException); const unexpected = new Error('db'); list.execute.mockRejectedValueOnce(unexpected); await expect(controller.listBookings(businessId, {})).rejects.toBe(unexpected); });
  it('delegates submission and maps Availability conflicts', async () => { submit.execute.mockResolvedValueOnce(booking.withStatus(BookingStatus.PENDING)); await expect(controller.submit(businessId, bookingId)).resolves.toMatchObject({ id: bookingId, status: BookingStatus.PENDING }); expect(submit.execute).toHaveBeenCalledWith({ businessId, bookingId }); submit.execute.mockRejectedValueOnce(new BookingAvailabilityConflictError('conflict')); await expect(controller.submit(businessId, bookingId)).rejects.toBeInstanceOf(ConflictException); });
});
