import { Booking } from '../../../src/modules/booking/domain/booking.entity';
import { BookingStatus } from '../../../src/modules/booking/domain/booking-status.enum';
import { BookingTimelineEventType, type BookingTimelineEvent, type BookingTimelineRepository } from '../../../src/modules/booking/domain/booking-timeline-event';
import type { BookingData, BookingListFilters, BookingRepository } from '../../../src/modules/booking/domain/booking.repository';
const bookings=new Map<string,Booking>(); const events:BookingTimelineEvent[]=[]; let sequence=0;
const addEvent=(booking:Booking,type:BookingTimelineEventType,actorUserId:string|null,reason?:string):void=>{sequence+=1;events.push({id:`e0000000-0000-4000-8000-${String(sequence).padStart(12,'0')}`,businessId:booking.businessId,bookingId:booking.id,type,occurredAt:new Date(Date.now()+sequence),actorUserId,details:reason?{reason}:{}});};
const isBlocking=(booking:Booking,businessId:string,from:Date,to:Date,pending=true)=>booking.businessId===businessId&&(pending?[BookingStatus.PENDING,BookingStatus.CONFIRMED,BookingStatus.IN_PROGRESS]:[BookingStatus.CONFIRMED,BookingStatus.IN_PROGRESS]).includes(booking.status)&&booking.checkInDate!==null&&booking.checkOutDate!==null&&booking.checkInDate<to&&booking.checkOutDate>from;
export const bookingRepositoryFake:BookingRepository={
  create:(data:BookingData)=>{const now=new Date();const booking=Booking.create({id:`b0000000-0000-4000-8000-${String(bookings.size+1).padStart(12,'0')}`,...data,status:BookingStatus.DRAFT,createdAt:now,updatedAt:now});bookings.set(booking.id,booking);addEvent(booking,BookingTimelineEventType.BOOKING_CREATED,data.actorUserId??null);return Promise.resolve(booking);},
  findByIdAndBusinessId:(id,businessId)=>Promise.resolve(bookings.get(id)?.businessId===businessId?bookings.get(id)??null:null),
  listByBusinessId:(businessId,filters:BookingListFilters)=>Promise.resolve([...bookings.values()].filter((booking)=>booking.businessId===businessId&&(filters.status===null||booking.status===filters.status)&&(filters.contactId===null||booking.contactId===filters.contactId)&&(filters.resourceId===null||booking.resourceIds.includes(filters.resourceId))).sort((a,b)=>b.createdAt.getTime()-a.createdAt.getTime()||a.id.localeCompare(b.id))),
  update:(booking)=>{bookings.set(booking.id,booking);return Promise.resolve(booking);},
  markPending:(id,businessId,actor)=>{const booking=bookings.get(id);if(!booking||booking.businessId!==businessId||booking.status!==BookingStatus.DRAFT)return Promise.resolve(null);const pending=booking.withStatus(BookingStatus.PENDING);bookings.set(id,pending);addEvent(pending,BookingTimelineEventType.BOOKING_SUBMITTED,actor);return Promise.resolve(pending);},
  markCancelled:(id,businessId,actor,reason)=>{const booking=bookings.get(id);if(!booking||booking.businessId!==businessId||![BookingStatus.DRAFT,BookingStatus.PENDING,BookingStatus.CONFIRMED].includes(booking.status))return Promise.resolve(null);const cancelled=booking.withStatus(BookingStatus.CANCELLED);bookings.set(id,cancelled);addEvent(cancelled,BookingTimelineEventType.BOOKING_CANCELLED,actor,reason);return Promise.resolve(cancelled);},
  hasBlockingBooking:(businessId,resourceId,from,to,pending)=>Promise.resolve([...bookings.values()].some((booking)=>isBlocking(booking,businessId,from,to,pending)&&booking.resourceIds.includes(resourceId))),
  listBlockingBookings:(businessId,from,to,pending)=>Promise.resolve([...bookings.values()].filter((booking)=>isBlocking(booking,businessId,from,to,pending)).flatMap((booking)=>booking.resourceIds.map((resourceId)=>({resourceId,checkInDate:booking.checkInDate!,checkOutDate:booking.checkOutDate!})))),
};
export const bookingTimelineRepositoryFake:BookingTimelineRepository={list:({businessId,bookingId,before,limit})=>Promise.resolve(events.filter((item)=>item.businessId===businessId&&item.bookingId===bookingId&&(!before||item.occurredAt<before.occurredAt||(item.occurredAt.getTime()===before.occurredAt.getTime()&&item.id<before.id))).sort((a,b)=>b.occurredAt.getTime()-a.occurredAt.getTime()||b.id.localeCompare(a.id)).slice(0,limit))};
export function addBookingFake(booking:Booking):void{bookings.set(booking.id,booking);} export function resetBookingRepositoryFake():void{bookings.clear();events.length=0;sequence=0;}
