export enum ConversationSessionState {
  START = 'START',
  MAIN_MENU = 'MAIN_MENU',
  AVAILABILITY_ASK_CHECK_IN = 'AVAILABILITY_ASK_CHECK_IN',
  AVAILABILITY_ASK_CHECK_OUT = 'AVAILABILITY_ASK_CHECK_OUT',
  AVAILABILITY_ASK_GUESTS = 'AVAILABILITY_ASK_GUESTS',
  AVAILABILITY_RESULTS = 'AVAILABILITY_RESULTS',
  PRICING_QUOTE = 'PRICING_QUOTE',
  CONTACT_ASK_NAME = 'CONTACT_ASK_NAME',
  BOOKING_CONFIRM = 'BOOKING_CONFIRM',
  BOOKING_CREATED = 'BOOKING_CREATED',
  HUMAN_HANDOFF = 'HUMAN_HANDOFF',
}
