import { InvalidBookingInputError } from './booking.errors';
import { assertDateRange, bookingContactId, bookingCount, bookingDate, bookingNotes, bookingResourceIds, bookingStatus, requireBookingPatch, requireBookingUuid } from './booking.validation';
import { BookingStatus } from '../domain/booking-status.enum';
const id = '11111111-1111-4111-8111-111111111111';
describe('Booking validation', () => {
  it('validates strict UUIDs, including prefix and suffix garbage', () => { expect(requireBookingUuid(id, 'bad')).toBe(id); for (const value of [`x${id}`, `${id}x`, 'invalid']) expect(() => requireBookingUuid(value, 'bad')).toThrow(InvalidBookingInputError); });
  it('validates resource arrays, their members, duplicates and an empty replacement', () => { expect(bookingResourceIds([])).toEqual([]); expect(bookingResourceIds([id])).toEqual([id]); expect(() => bookingResourceIds(id)).toThrow(InvalidBookingInputError); expect(() => bookingResourceIds(['invalid'])).toThrow(InvalidBookingInputError); expect(() => bookingResourceIds([id, id])).toThrow(InvalidBookingInputError); });
  it('keeps the contact patch distinction between undefined, null and an identifier', () => { expect(bookingContactId(undefined)).toBeUndefined(); expect(bookingContactId(null)).toBeNull(); expect(bookingContactId(id)).toBe(id); expect(() => bookingContactId('bad')).toThrow(InvalidBookingInputError); });
  it('normalizes notes and enforces its final length', () => { expect(bookingNotes(undefined)).toBeUndefined(); expect(bookingNotes(null)).toBeNull(); expect(bookingNotes('   ')).toBeNull(); expect(bookingNotes(' Nota ')).toBe('Nota'); expect(bookingNotes('x'.repeat(1000))).toHaveLength(1000); expect(() => bookingNotes('x'.repeat(1001))).toThrow(InvalidBookingInputError); });
  it.each([['adultos', bookingCount] as const, ['niños', bookingCount] as const])('validates nullable non-negative integer %s counts', (_field, parse) => { expect(parse(undefined, 'Cantidad')).toBeUndefined(); expect(parse(null, 'Cantidad')).toBeNull(); expect(parse(0, 'Cantidad')).toBe(0); expect(parse(2, 'Cantidad')).toBe(2); for (const value of [-1, 1.5, '2']) expect(() => parse(value, 'Cantidad')).toThrow(InvalidBookingInputError); });
  it('accepts only real strict calendar dates and validates final ranges', () => { expect(bookingDate('2028-02-29', 'Fecha')).toEqual(new Date('2028-02-29T00:00:00.000Z')); expect(bookingDate(undefined, 'Fecha')).toBeUndefined(); expect(bookingDate(null, 'Fecha')).toBeNull(); for (const value of ['2026-02-30', '2026/02/20', 'x2026-02-20', '2026-02-20x']) expect(() => bookingDate(value, 'Fecha')).toThrow(InvalidBookingInputError); const day = new Date('2026-04-01T00:00:00.000Z'); expect(() => assertDateRange(day, day)).toThrow(InvalidBookingInputError); expect(() => assertDateRange(new Date('2026-04-02'), day)).toThrow(InvalidBookingInputError); });
  it('recognizes statuses and every approved patch field', () => { expect(bookingStatus(BookingStatus.DRAFT)).toBe(BookingStatus.DRAFT); expect(() => bookingStatus('OTHER')).toThrow(InvalidBookingInputError); for (const field of ['contactId', 'resourceIds', 'checkInDate', 'checkOutDate', 'adults', 'children', 'notes']) expect(() => requireBookingPatch({ [field]: null })).not.toThrow(); expect(() => requireBookingPatch({})).toThrow(InvalidBookingInputError); });
});
