export class InvalidBookingInputError extends Error {}
export class BookingBusinessNotFoundError extends Error {}
export class BookingBusinessUnavailableError extends Error {}
export class BookingContactNotFoundError extends Error {}
export class BookingResourceNotFoundError extends Error {}
export class BookingResourceUnavailableError extends Error {}
export class BookingNotFoundError extends Error {}
export class BookingNotDraftError extends Error {}
export class BookingContactRequiredError extends Error {}
export class BookingResourcesRequiredError extends Error {}
export class BookingDatesRequiredError extends Error {}
export class BookingAvailabilityConflictError extends Error {}
