import { PrismaClient } from '@prisma/client';
import { PrismaBookingConfirmationTransaction } from '../../src/modules/booking-lifecycle/infrastructure/prisma-booking-confirmation.transaction';
import { BookingStatus } from '../../src/modules/booking/domain/booking-status.enum';
import { PrismaBookingRepository } from '../../src/modules/booking/infrastructure/prisma-booking.repository';
import { cleanTestDatabase } from './support/clean-test-database';

const databaseUrl=process.env.DATABASE_URL; const describeWithPostgres=databaseUrl?.includes('test')?describe:describe.skip;
const failingActor='00000000-0000-4000-8000-000000000001';
describeWithPostgres('Booking Timeline atomicity',()=>{
  const prisma=new PrismaClient(); const bookings=new PrismaBookingRepository(prisma); const confirmation=new PrismaBookingConfirmationTransaction(prisma as never);
  beforeAll(async()=>prisma.$connect());
  beforeEach(async()=>{await prisma.$executeRawUnsafe('DROP TRIGGER IF EXISTS fail_test_timeline_event_trigger ON "BookingTimelineEvent"');await prisma.$executeRawUnsafe('DROP FUNCTION IF EXISTS fail_test_timeline_event()');await cleanTestDatabase(prisma,databaseUrl);await prisma.$executeRawUnsafe(`CREATE OR REPLACE FUNCTION fail_test_timeline_event() RETURNS trigger AS $$ BEGIN IF NEW."actorUserId" = '${failingActor}' THEN RAISE EXCEPTION 'forced timeline failure'; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql`);await prisma.$executeRawUnsafe('CREATE TRIGGER fail_test_timeline_event_trigger BEFORE INSERT ON "BookingTimelineEvent" FOR EACH ROW EXECUTE FUNCTION fail_test_timeline_event()');});
  afterEach(async()=>{await prisma.$executeRawUnsafe('DROP TRIGGER IF EXISTS fail_test_timeline_event_trigger ON "BookingTimelineEvent"');await prisma.$executeRawUnsafe('DROP FUNCTION IF EXISTS fail_test_timeline_event()');await cleanTestDatabase(prisma,databaseUrl);});
  afterAll(async()=>prisma.$disconnect());
  const business=()=>prisma.business.create({data:{name:`Business ${crypto.randomUUID()}`}});
  const draft=async()=>{const owner=await business();const booking=await bookings.create({businessId:owner.id,contactId:null,resourceIds:[],checkInDate:null,checkOutDate:null,adults:null,children:null,notes:null,actorUserId:null});return{owner,booking};};
  it('rolls back Create when BOOKING_CREATED fails',async()=>{const owner=await business();await expect(bookings.create({businessId:owner.id,contactId:null,resourceIds:[],checkInDate:null,checkOutDate:null,adults:null,children:null,notes:null,actorUserId:failingActor})).rejects.toThrow();await expect(prisma.booking.count({where:{businessId:owner.id}})).resolves.toBe(0);});
  it('rolls back Submit when BOOKING_SUBMITTED fails',async()=>{const value=await draft();await expect(bookings.markPending(value.booking.id,value.owner.id,failingActor)).rejects.toThrow();await expect(prisma.booking.findUnique({where:{id:value.booking.id}})).resolves.toMatchObject({status:BookingStatus.DRAFT});await expect(prisma.bookingTimelineEvent.count({where:{bookingId:value.booking.id,type:'BOOKING_SUBMITTED'}})).resolves.toBe(0);});
  it('rolls back Cancel when BOOKING_CANCELLED fails',async()=>{const value=await draft();await expect(bookings.markCancelled(value.booking.id,value.owner.id,failingActor,'Motivo')).rejects.toThrow();await expect(prisma.booking.findUnique({where:{id:value.booking.id}})).resolves.toMatchObject({status:BookingStatus.DRAFT});await expect(prisma.bookingTimelineEvent.count({where:{bookingId:value.booking.id,type:'BOOKING_CANCELLED'}})).resolves.toBe(0);});
  it('rolls back Confirm and PricingSnapshot when BOOKING_CONFIRMED fails',async()=>{const value=await draft();await bookings.markPending(value.booking.id,value.owner.id,null);await expect(confirmation.confirm({businessId:value.owner.id,bookingId:value.booking.id,actorUserId:failingActor,prepare:async()=>({currency:'PYG',totalAmountMinor:1,items:[]})})).rejects.toThrow();await expect(prisma.booking.findUnique({where:{id:value.booking.id}})).resolves.toMatchObject({status:BookingStatus.PENDING});await expect(prisma.pricingSnapshot.count({where:{bookingId:value.booking.id}})).resolves.toBe(0);await expect(prisma.bookingTimelineEvent.count({where:{bookingId:value.booking.id,type:'BOOKING_CONFIRMED'}})).resolves.toBe(0);});
});
