import { PrismaClient } from '@prisma/client';
import { ConfirmBookingUseCase } from '../../src/modules/booking-lifecycle/application/confirm-booking.use-case';
import { PrismaBookingConfirmationTransaction } from '../../src/modules/booking-lifecycle/infrastructure/prisma-booking-confirmation.transaction';
import { BookingAvailabilityConflictError, BookingNotFoundError, BookingStatus } from '../../src/modules/booking/booking.contract';
import { PrismaBookingRepository } from '../../src/modules/booking/infrastructure/prisma-booking.repository';
import { PrismaBusinessRepository } from '../../src/modules/business/infrastructure/prisma-business.repository';
import { PrismaContactRepository } from '../../src/modules/contact/infrastructure/prisma-contact.repository';
import { PrismaResourceRepository } from '../../src/modules/resource/infrastructure/prisma-resource.repository';
import { PrismaBlockRepository } from '../../src/modules/block/infrastructure/prisma-block.repository';
import { PrismaAvailabilityRulesRepository } from '../../src/modules/availability/infrastructure/prisma-availability-rules.repository';
import { CheckAvailabilityUseCase } from '../../src/modules/availability/application/check-availability.use-case';
import { ValidateOverbookingUseCase } from '../../src/modules/availability/application/validate-overbooking.use-case';
import { PrismaRatePlanRepository } from '../../src/modules/pricing/infrastructure/prisma-rate-plan.repository';
import { PrismaSeasonalRateRepository } from '../../src/modules/pricing/infrastructure/prisma-seasonal-rate.repository';
import { CalculatePriceUseCase } from '../../src/modules/pricing/application/calculate-price.use-case';
import { ApplyManualPriceOverrideUseCase } from '../../src/modules/pricing/application/apply-manual-price-override.use-case';
import { PricingCalculator } from '../../src/modules/pricing/domain/pricing-calculator';
import { cleanTestDatabase } from './support/clean-test-database';

const databaseUrl = process.env.DATABASE_URL;
const describeWithPostgres = databaseUrl?.includes('test') ? describe : describe.skip;

describeWithPostgres('ConfirmBookingUseCase', () => {
  const prisma = new PrismaClient(); const businesses = new PrismaBusinessRepository(prisma); const contacts = new PrismaContactRepository(prisma); const resources = new PrismaResourceRepository(prisma); const bookings = new PrismaBookingRepository(prisma); const blocks = new PrismaBlockRepository(prisma); const rules = new PrismaAvailabilityRulesRepository(prisma); const rates = new PrismaRatePlanRepository(prisma); const seasons = new PrismaSeasonalRateRepository(prisma);
  const availability = new ValidateOverbookingUseCase(new CheckAvailabilityUseCase(businesses, resources, bookings, blocks, rules));
  const calculate = new CalculatePriceUseCase(businesses, resources, rates, rates, seasons, new PricingCalculator());
  const confirm = new ConfirmBookingUseCase(businesses, contacts, bookings, availability, calculate, new ApplyManualPriceOverrideUseCase(calculate), new PrismaBookingConfirmationTransaction(prisma));
  beforeAll(async () => prisma.$connect()); beforeEach(async () => cleanTestDatabase(prisma, databaseUrl)); afterEach(async () => cleanTestDatabase(prisma, databaseUrl)); afterAll(async () => { await cleanTestDatabase(prisma, databaseUrl); await prisma.$disconnect(); });
  async function fixture(name: string) { const business = await prisma.business.create({ data: { name } }); const contact = await prisma.contact.create({ data: { businessId: business.id, name: 'Guest', email: `${name.replaceAll(' ', '')}@test.local` } }); const resource = await prisma.resource.create({ data: { businessId: business.id, name: 'Room', internalCode: `${name.replaceAll(' ', '').toUpperCase()}R`, capacityMaximum: 2 } }); const ratePlan = await prisma.ratePlan.create({ data: { businessId: business.id, name: 'Base', baseNightlyAmountMinor: 150000, resources: { create: { resourceId: resource.id } } } }); const booking = await bookings.create({ businessId: business.id, contactId: contact.id, resourceIds: [resource.id], checkInDate: new Date('2026-06-10'), checkOutDate: new Date('2026-06-12'), adults: null, children: null, notes: null }); await bookings.markPending(booking.id, business.id, null); return { business, resource, ratePlan, booking }; }
  const pricing = (value: { resource: { id: string }; ratePlan: { id: string } }) => [{ resourceId: value.resource.id, ratePlanId: value.ratePlan.id }];
  it('confirms a pending booking, excludes itself, and persists calculated snapshot', async () => { const value = await fixture('Calculated'); await expect(confirm.execute({ businessId: value.business.id, bookingId: value.booking.id, pricing: pricing(value) })).resolves.toMatchObject({ status: BookingStatus.CONFIRMED }); await expect(prisma.pricingSnapshot.findUnique({ where: { bookingId: value.booking.id } })).resolves.toMatchObject({ currency: 'PYG', totalAmountMinor: 300000 }); });
  it('persists manual override pricing in the immutable snapshot', async () => { const value = await fixture('Manual'); await confirm.execute({ businessId: value.business.id, bookingId: value.booking.id, pricing: [{ ...pricing(value)[0], agreedAmountMinor: 250000, overrideReason: 'Commercial discount' }] }); await expect(prisma.pricingSnapshot.findUnique({ where: { bookingId: value.booking.id } })).resolves.toMatchObject({ totalAmountMinor: 250000, items: expect.arrayContaining([expect.objectContaining({ pricingMode: 'MANUAL_OVERRIDE', agreedAmountMinor: 250000 })]) }); });
  it('rolls back when another pending booking intersects the same resource', async () => { const value = await fixture('Conflict'); const other = await bookings.create({ businessId: value.business.id, contactId: (await prisma.contact.findFirst({ where: { businessId: value.business.id } }))!.id, resourceIds: [value.resource.id], checkInDate: new Date('2026-06-11'), checkOutDate: new Date('2026-06-13'), adults: null, children: null, notes: null }); await bookings.markPending(other.id, value.business.id, null); await expect(confirm.execute({ businessId: value.business.id, bookingId: value.booking.id, pricing: pricing(value) })).rejects.toBeInstanceOf(BookingAvailabilityConflictError); await expect(prisma.booking.findUnique({ where: { id: value.booking.id } })).resolves.toMatchObject({ status: BookingStatus.PENDING }); await expect(prisma.pricingSnapshot.count({ where: { bookingId: value.booking.id } })).resolves.toBe(0); });
  it('rolls back status and snapshot when pricing fails', async () => { const value = await fixture('Pricing failure'); await expect(confirm.execute({ businessId: value.business.id, bookingId: value.booking.id, pricing: [{ resourceId: value.resource.id, ratePlanId: '11111111-1111-4111-8111-111111111111' }] })).rejects.toThrow(); await expect(prisma.booking.findUnique({ where: { id: value.booking.id } })).resolves.toMatchObject({ status: BookingStatus.PENDING }); await expect(prisma.pricingSnapshot.count({ where: { bookingId: value.booking.id } })).resolves.toBe(0); });
  it('hides a pending booking from another tenant', async () => { const owner = await fixture('Owner'); const other = await fixture('Other'); await expect(confirm.execute({ businessId: other.business.id, bookingId: owner.booking.id, pricing: pricing(owner) })).rejects.toBeInstanceOf(BookingNotFoundError); });
  it('allows exactly one concurrent confirmation for conflicting pending bookings', async () => { const value = await fixture('Race'); await prisma.availabilityRule.create({ data: { businessId: value.business.id, pendingBlocksAvailability: false, bufferBeforeDays: 0, bufferAfterDays: 0 } }); const second = await bookings.create({ businessId: value.business.id, contactId: (await prisma.contact.findFirst({ where: { businessId: value.business.id } }))!.id, resourceIds: [value.resource.id], checkInDate: new Date('2026-06-10'), checkOutDate: new Date('2026-06-12'), adults: null, children: null, notes: null }); await bookings.markPending(second.id, value.business.id, null); const outcomes = await Promise.allSettled([confirm.execute({ businessId: value.business.id, bookingId: value.booking.id, pricing: pricing(value) }), confirm.execute({ businessId: value.business.id, bookingId: second.id, pricing: pricing(value) })]); expect(outcomes.filter((outcome) => outcome.status === 'fulfilled')).toHaveLength(1); await expect(prisma.booking.count({ where: { id: { in: [value.booking.id, second.id] }, status: BookingStatus.CONFIRMED } })).resolves.toBe(1); await expect(prisma.pricingSnapshot.count({ where: { bookingId: { in: [value.booking.id, second.id] } } })).resolves.toBe(1); });
});
