import { PrismaClient } from '@prisma/client';
import { PaymentMethod, PaymentStatus, type RegisterPaymentData } from '../../src/modules/payment/domain/payment';
import { PrismaPaymentPlanRepository } from '../../src/modules/payment/infrastructure/prisma-payment-plan.repository';
import { PrismaPaymentRepository } from '../../src/modules/payment/infrastructure/prisma-payment.repository';
import { cleanTestDatabase } from './support/clean-test-database';

const databaseUrl = process.env.DATABASE_URL; const describeWithPostgres = databaseUrl?.includes('test') ? describe : describe.skip;
describeWithPostgres('PaymentPlan with PostgreSQL', () => {
  const prisma = new PrismaClient(); const plans = new PrismaPaymentPlanRepository(prisma); const payments = new PrismaPaymentRepository(prisma);
  beforeAll(async () => prisma.$connect()); beforeEach(async () => cleanTestDatabase(prisma, databaseUrl)); afterEach(async () => cleanTestDatabase(prisma, databaseUrl)); afterAll(async () => prisma.$disconnect());
  async function fixture(total = 100) { const business = await prisma.business.create({ data: { name: `Plan ${crypto.randomUUID()}` } }); const booking = await prisma.booking.create({ data: { businessId: business.id, status: 'CONFIRMED' } }); await prisma.pricingSnapshot.create({ data: { businessId: business.id, bookingId: booking.id, currency: 'PYG', totalAmountMinor: total, items: [] } }); return { business, booking }; }
  const planData = (businessId: string, bookingId: string) => ({ businessId, bookingId, currency: 'PYG', totalAmountMinor: 100, actorUserId: 'actor', installments: [{ amountMinor: 40, dueDate: new Date('2026-10-01'), sortOrder: 0 }, { amountMinor: 60, dueDate: null, sortOrder: 1 }] });
  const paymentData = (businessId: string, bookingId: string, key: string, amountMinor: number): RegisterPaymentData => ({ businessId, bookingId, amountMinor, currency: 'PYG', method: PaymentMethod.CASH, reference: null, note: null, paidAt: new Date('2026-09-01'), recordedByUserId: 'actor', status: PaymentStatus.RECORDED, idempotencyKey: key, requestFingerprint: `${key}-${amountMinor}` });

  it('persists one tenant-scoped plan and its ordered installments', async () => { const value = await fixture(); const created = await plans.create(planData(value.business.id, value.booking.id)); expect(created.installments.map((item) => item.amountMinor)).toEqual([40, 60]); await expect(plans.findByBooking({ businessId: value.business.id, bookingId: value.booking.id })).resolves.toMatchObject({ id: created.id, currency: 'PYG', totalAmountMinor: 100 }); await expect(plans.findByBooking({ businessId: crypto.randomUUID(), bookingId: value.booking.id })).resolves.toBeNull(); await expect(plans.create(planData(value.business.id, value.booking.id))).rejects.toThrow('PAYMENT_PLAN_EXISTS'); });
  it('applies historical and new Payments oldest-due-first without duplicating an idempotent retry', async () => { const value = await fixture(); await payments.register(paymentData(value.business.id, value.booking.id, 'old', 30), 100); const created = await plans.create(planData(value.business.id, value.booking.id)); expect(created.installments.map((item) => item.appliedAmountMinor)).toEqual([30, 0]); const first = await payments.register(paymentData(value.business.id, value.booking.id, 'new', 50), 100); await payments.register(paymentData(value.business.id, value.booking.id, 'new', 50), 100); const current = await plans.findByBooking({ businessId: value.business.id, bookingId: value.booking.id }); expect(current?.installments.map((item) => item.appliedAmountMinor)).toEqual([40, 40]); await expect(prisma.paymentApplication.count({ where: { paymentId: first.payment.id } })).resolves.toBe(2); });
  it('replaces atomically before applications and blocks replacement afterwards', async () => { const value = await fixture(); const created = await plans.create(planData(value.business.id, value.booking.id)); const replaced = await plans.replace({ ...planData(value.business.id, value.booking.id), installments: [{ amountMinor: 100, dueDate: null, sortOrder: 0 }] }); expect(replaced.id).toBe(created.id); expect(replaced.installments).toHaveLength(1); await payments.register(paymentData(value.business.id, value.booking.id, 'applied', 10), 100); await expect(plans.replace(planData(value.business.id, value.booking.id))).rejects.toThrow('PAYMENT_PLAN_HAS_APPLICATIONS'); });
  it('serializes concurrent plan creation and concurrent Payments without overapplying installments', async () => { const value = await fixture(); const data = planData(value.business.id, value.booking.id); const creation = await Promise.allSettled([plans.create(data), plans.create(data)]); expect(creation.filter((result) => result.status === 'fulfilled')).toHaveLength(1); const registration = await Promise.allSettled([payments.register(paymentData(value.business.id, value.booking.id, 'a', 70), 100), payments.register(paymentData(value.business.id, value.booking.id, 'b', 70), 100)]); expect(registration.filter((result) => result.status === 'fulfilled')).toHaveLength(1); const applied = await prisma.paymentApplication.aggregate({ where: { installment: { paymentPlan: { bookingId: value.booking.id } } }, _sum: { amountMinor: true } }); expect(applied._sum.amountMinor).toBe(70); });
});
