import { PrismaClient } from '@prisma/client';
import { PrismaBusinessRepository } from '../../src/modules/business/infrastructure/prisma-business.repository';
import { UpdateRatePlanUseCase } from '../../src/modules/pricing/application/update-rate-plan.use-case';
import { PrismaRatePlanRepository } from '../../src/modules/pricing/infrastructure/prisma-rate-plan.repository';
import { PrismaResourceRepository } from '../../src/modules/resource/infrastructure/prisma-resource.repository';
import { ResourceStatus } from '../../src/modules/resource/domain/resource-status.enum';
import { cleanTestDatabase } from './support/clean-test-database';

const databaseUrl = process.env.DATABASE_URL;
const describeWithPostgres = databaseUrl?.includes('test') ? describe : describe.skip;
describeWithPostgres('PrismaRatePlanRepository', () => {
  const prisma = new PrismaClient(); const repository = new PrismaRatePlanRepository(prisma);
  const update = new UpdateRatePlanUseCase(new PrismaBusinessRepository(prisma), new PrismaResourceRepository(prisma), repository);
  beforeAll(async () => prisma.$connect()); beforeEach(async () => cleanTestDatabase(prisma, databaseUrl)); afterEach(async () => cleanTestDatabase(prisma, databaseUrl)); afterAll(async () => { await cleanTestDatabase(prisma, databaseUrl); await prisma.$disconnect(); });
  async function fixture() {
    const business = await prisma.business.create({ data: { name: 'Pricing' } });
    const resources = await Promise.all(['ONE', 'TWO', 'THREE'].map((internalCode, index) => prisma.resource.create({ data: { businessId: business.id, name: internalCode, internalCode, capacityMaximum: 2, status: index === 2 ? ResourceStatus.OUT_OF_SERVICE : ResourceStatus.ACTIVE } })));
    const plan = await repository.create({ businessId: business.id, name: 'Standard', description: 'Initial', baseNightlyAmountMinor: 450000, currency: 'PYG', validFrom: '2026-08-01', validTo: '2026-09-01', resourceIds: [resources[0].id, resources[1].id] });
    return { business, resources, plan };
  }
  async function persisted(id: string) { return prisma.ratePlan.findUniqueOrThrow({ where: { id }, include: { resources: true } }); }
  it('crea atómicamente un plan con Resources y tarifa base', async () => { const { business, resources, plan } = await fixture(); const saved = await persisted(plan.id); expect(plan).toMatchObject({ businessId: business.id, currency: 'PYG', baseNightlyAmountMinor: 450000 }); expect(saved.resources.map((item) => item.resourceId).sort()).toEqual([resources[0].id, resources[1].id].sort()); });
  it('preserva relaciones si resourceIds es undefined y las reemplaza o vacía cuando está presente', async () => { const { resources, plan } = await fixture(); await repository.update({ id: plan.id, businessId: plan.businessId, name: 'Updated', description: null, baseNightlyAmountMinor: 500000, currency: 'PYG', validFrom: null, validTo: plan.validTo, resourceIds: undefined }); let saved = await persisted(plan.id); expect(saved.resources.map((item) => item.resourceId).sort()).toEqual([resources[0].id, resources[1].id].sort()); await repository.update({ id: plan.id, businessId: plan.businessId, name: 'Updated', description: null, baseNightlyAmountMinor: 500000, currency: 'PYG', validFrom: null, validTo: null, resourceIds: [resources[1].id, resources[2].id] }); saved = await persisted(plan.id); expect(saved.resources.map((item) => item.resourceId).sort()).toEqual([resources[1].id, resources[2].id].sort()); await repository.update({ id: plan.id, businessId: plan.businessId, name: 'Updated', description: null, baseNightlyAmountMinor: 500000, currency: 'PYG', validFrom: null, validTo: null, resourceIds: [] }); expect((await persisted(plan.id)).resources).toHaveLength(0); });
  it('permite Resource OUT_OF_SERVICE y oculta Resources de otro Business', async () => { const { business, resources, plan } = await fixture(); await expect(update.execute({ businessId: business.id, ratePlanId: plan.id, resourceIds: [resources[2].id] })).resolves.toMatchObject({ resources: [{ id: resources[2].id }] }); const other = await prisma.business.create({ data: { name: 'Other' } }); const foreign = await prisma.resource.create({ data: { businessId: other.id, name: 'Foreign', internalCode: 'FOREIGN', capacityMaximum: 2 } }); await expect(update.execute({ businessId: business.id, ratePlanId: plan.id, resourceIds: [foreign.id] })).rejects.toThrow('El recurso no existe.'); expect((await persisted(plan.id)).resources.map((item) => item.resourceId)).toEqual([resources[2].id]); });
  it('rejects archived Resources without partial updates or relations', async () => { const { business, resources, plan } = await fixture(); const archived = await prisma.resource.create({ data: { businessId: business.id, name: 'Archived', internalCode: 'ARCHIVED', capacityMaximum: 2, status: ResourceStatus.ARCHIVED } }); await expect(update.execute({ businessId: business.id, ratePlanId: plan.id, baseNightlyAmountMinor: 500000, resourceIds: [resources[1].id, archived.id] })).rejects.toThrow('El recurso está archivado.'); const saved = await persisted(plan.id); expect(saved.baseNightlyAmountMinor).toBe(450000); expect(saved.resources.map((item) => item.resourceId).sort()).toEqual([resources[0].id, resources[1].id].sort()); expect(saved.resources.some((item) => item.resourceId === archived.id)).toBe(false); });
});
