import { PrismaClient } from '@prisma/client';
import { PrismaBookingTimelineRepository } from '../../src/modules/booking/infrastructure/prisma-booking-timeline.repository';
import { cleanTestDatabase } from './support/clean-test-database';
const databaseUrl=process.env.DATABASE_URL; const describeWithPostgres=databaseUrl?.includes('test')?describe:describe.skip;
describeWithPostgres('PrismaBookingTimelineRepository',()=>{
  const prisma=new PrismaClient();const repository=new PrismaBookingTimelineRepository(prisma as never);
  beforeAll(async()=>prisma.$connect());beforeEach(async()=>cleanTestDatabase(prisma,databaseUrl));afterEach(async()=>cleanTestDatabase(prisma,databaseUrl));afterAll(async()=>prisma.$disconnect());
  const booking=async(name:string)=>{const business=await prisma.business.create({data:{name}});const value=await prisma.booking.create({data:{businessId:business.id}});return{business,booking:value};};
  it('orders equal timestamps by id DESC and paginates without gaps',async()=>{const value=await booking('Owner');const occurredAt=new Date('2026-08-29T20:00:00.000Z');const ids=['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222','33333333-3333-4333-8333-333333333333'];for(const id of ids)await prisma.bookingTimelineEvent.create({data:{id,businessId:value.business.id,bookingId:value.booking.id,type:'BOOKING_CREATED',occurredAt,details:{}}});const first=await repository.list({businessId:value.business.id,bookingId:value.booking.id,before:null,limit:2});expect(first.map((item)=>item.id)).toEqual([ids[2],ids[1]]);const second=await repository.list({businessId:value.business.id,bookingId:value.booking.id,before:{occurredAt:first[1].occurredAt,id:first[1].id},limit:2});expect(second.map((item)=>item.id)).toEqual([ids[0]]);});
  it('never exposes events through a foreign business or booking scope',async()=>{const owner=await booking('Owner');const other=await booking('Other');await prisma.bookingTimelineEvent.create({data:{businessId:owner.business.id,bookingId:owner.booking.id,type:'BOOKING_CREATED',details:{}}});await expect(repository.list({businessId:other.business.id,bookingId:owner.booking.id,before:null,limit:50})).resolves.toEqual([]);await expect(repository.list({businessId:owner.business.id,bookingId:other.booking.id,before:null,limit:50})).resolves.toEqual([]);});
  it('enforces event type and composite tenant constraints',async()=>{const owner=await booking('Owner');const other=await booking('Other');await expect(prisma.bookingTimelineEvent.create({data:{businessId:owner.business.id,bookingId:owner.booking.id,type:'INVALID',details:{}}})).rejects.toThrow();await expect(prisma.bookingTimelineEvent.create({data:{businessId:other.business.id,bookingId:owner.booking.id,type:'BOOKING_CREATED',details:{}}})).rejects.toThrow();});
});
