export { MESSAGING_PROVIDER, type MessagingProvider, type MessagingProviderResult } from './application/messaging-provider';
export type { MessagingWebhookEvent, MessagingWebhookHandler, MessagingInboundTextWebhookEvent, MessagingDeliveryStatusWebhookEvent } from './application/messaging-webhook.contract';
export { MESSAGING_CONNECTION_RESOLVER, type ActiveMessagingConnection, type MessagingConnectionResolver } from './domain/messaging-connection.repository';
export { MessagingConnectionStatus } from './domain/messaging-connection-status.enum';
export { MessagingConnectionProvider } from './domain/messaging-provider.enum';
export { OUTBOUND_MESSAGE_REPOSITORY, type OutboundMessageRepository } from './domain/outbound-message.repository';
export { MessagingChannel } from './domain/messaging-channel.enum';
export { OutboundMessageStatus } from './domain/outbound-message-status.enum';
export { OutboundMessageType } from './domain/outbound-message-type.enum';
export type { OutboundMessage } from './domain/outbound-message.entity';
export { ConversationMode } from './domain/conversation-mode.enum';
export { ConversationStatus } from './domain/conversation-status.enum';
export { ConversationSessionState } from './domain/conversation-session-state.enum';
export { InboundMessageType } from './domain/inbound-message-type.enum';
export type { Conversation } from './domain/conversation.entity';
export type { ConversationSession, ConversationSessionContext } from './domain/conversation-session.entity';
export type { InboundMessage } from './domain/inbound-message.entity';
export { CONVERSATION_REPOSITORY, type ConversationRepository } from './domain/conversation.repository';
export { CONVERSATION_INBOX_READER, type ConversationInboxReader, type ConversationInboxSummary, type ConversationInboxDetail, type ConversationInboxMessage } from './domain/conversation-inbox.repository';
export { INBOUND_MESSAGE_REPOSITORY, type InboundMessageRepository } from './domain/inbound-message.repository';
export { RECEIVE_INBOUND_MESSAGE_TRANSACTION, type InboundMessageEnvelope, type ReceiveInboundMessageInput, type ReceiveInboundMessageResult, type ReceiveInboundMessageTransaction } from './application/receive-inbound-message.contract';
export { MessagingAutomationType } from './domain/messaging-automation-type.enum';
export { MESSAGING_SETTINGS_REPOSITORY, type MessagingSettings, type MessagingSettingsRepository } from './domain/messaging-settings.repository';
export { MESSAGING_AUTOMATION_RULE_REPOSITORY, type MessagingAutomationRule, type MessagingAutomationRuleRepository } from './domain/messaging-automation-rule.repository';
export { MESSAGING_MESSAGE_TEMPLATE_REPOSITORY, type MessagingMessageTemplate, type MessagingMessageTemplateRepository } from './domain/messaging-message-template.repository';
export { MESSAGING_AUTOMATION_CONFIGURATION, type MessagingAutomationConfigurationReader, type ResolvedMessagingAutomation } from './application/messaging-automation-configuration';
