import { Business } from '../../business/domain/business.entity';
import { BusinessStatus } from '../../business/domain/business-status.enum';
import { InvalidBusinessIdError, InvalidResourceIdError, ResourceBusinessNotFoundError, ResourceNotFoundError } from './get-resource.use-case';
import { Resource } from '../domain/resource.entity';
import type { ResourceRepository } from '../domain/resource.repository';
import { ResourceStatus } from '../domain/resource-status.enum';
import { InvalidResourceUpdateError, ResourceArchivedError, ResourceBusinessArchivedError, ResourceCodeAlreadyExistsError, UpdateResourceUseCase } from './update-resource.use-case';

const businessId = '11111111-1111-4111-8111-111111111111';
const resourceId = '22222222-2222-4222-8222-222222222222';
const otherId = '33333333-3333-4333-8333-333333333333';
const makeBusiness = (status = BusinessStatus.ACTIVE): Business => Business.create({ id: businessId, businessNumber: null, name: 'TOP', legalName: null, taxId: null, timezone: 'America/Asuncion', currency: 'PYG', status, createdAt: new Date('2026-01-01'), updatedAt: new Date('2026-01-01') });
const makeResource = (overrides: Partial<{ id: string; businessId: string; status: ResourceStatus; name: string; internalCode: string; description: string | null; capacityMinimum: number; capacityMaximum: number; capacityMaximumChildren: number; sortOrder: number }> = {}): Resource => Resource.create({ id: resourceId, businessId, name: 'Cabaña Norte', internalCode: 'NORTE', description: 'Vista', capacityMinimum: 3, capacityMaximum: 4, capacityMaximumChildren: 2, status: ResourceStatus.ACTIVE, sortOrder: 4, createdAt: new Date('2026-01-01'), updatedAt: new Date('2026-01-01'), ...overrides });

describe('UpdateResourceUseCase', () => {
  const findById = jest.fn(); const findByIdAndBusinessId = jest.fn(); const findByBusinessAndCode = jest.fn(); const update = jest.fn();
  const repository: ResourceRepository = { findByBusinessAndCode, findByIdAndBusinessId, listByBusinessId: jest.fn(), create: jest.fn(), update };
  const useCase = new UpdateResourceUseCase({ findById, create: jest.fn(), list: jest.fn(), update: jest.fn() }, repository);
  const input = (changes: Record<string, unknown> = {}) => ({ businessId, resourceId, ...changes });
  beforeEach(() => { jest.resetAllMocks(); findById.mockResolvedValue(makeBusiness()); findByIdAndBusinessId.mockResolvedValue(makeResource()); findByBusinessAndCode.mockResolvedValue(null); update.mockImplementation((value: Resource) => Promise.resolve(value)); });

  it('normaliza campos, preserva identidad y persiste una sola vez', async () => { const result = await useCase.execute(input({ name: ' Cabaña Sur ', internalCode: ' sur-1 ', description: ' ', sortOrder: 0 })); expect(result).toMatchObject({ id: resourceId, businessId, name: 'Cabaña Sur', internalCode: 'SUR-1', description: null, capacityMinimum: 3, status: ResourceStatus.ACTIVE }); expect(result.createdAt).toEqual(new Date('2026-01-01')); expect(result.updatedAt).not.toEqual(new Date('2026-01-01')); expect(update).toHaveBeenCalledTimes(1); });
  it.each([[{ businessId: 'bad', name: 'Nueva' }, InvalidBusinessIdError, 'El identificador del negocio no es válido.'], [{ resourceId: 'bad', name: 'Nueva' }, InvalidResourceIdError, 'El identificador del recurso no es válido.']])('valida IDs antes de consultar', async (changes, ErrorType, message) => { await expect(useCase.execute(input(changes))).rejects.toEqual(new ErrorType(message)); expect(findById).not.toHaveBeenCalled(); expect(findByIdAndBusinessId).not.toHaveBeenCalled(); });
  it.each([{ businessId: `x${businessId}`, name: 'Nueva' }, { businessId: `${businessId}x`, name: 'Nueva' }])('rechaza business UUID con texto adicional', async (changes) => { await expect(useCase.execute(input(changes))).rejects.toBeInstanceOf(InvalidBusinessIdError); });
  it.each([{ resourceId: `x${resourceId}`, name: 'Nueva' }, { resourceId: `${resourceId}x`, name: 'Nueva' }])('rechaza Resource UUID con texto adicional', async (changes) => { await expect(useCase.execute(input(changes))).rejects.toBeInstanceOf(InvalidResourceIdError); });
  it('rechaza body vacío y campos undefined sin persistir', async () => { await expect(useCase.execute(input())).rejects.toEqual(new InvalidResourceUpdateError('Se requiere al menos un campo actualizable.')); await expect(useCase.execute(input({ name: undefined, sortOrder: undefined }))).rejects.toEqual(new InvalidResourceUpdateError('Se requiere al menos un campo actualizable.')); expect(update).not.toHaveBeenCalled(); });
  it('acepta valores falsy presentes', async () => { await expect(useCase.execute(input({ description: null }))).resolves.toMatchObject({ description: null }); await expect(useCase.execute(input({ sortOrder: 0 }))).resolves.toMatchObject({ sortOrder: 0 }); await expect(useCase.execute(input({ capacityMaximumChildren: 0 }))).resolves.toMatchObject({ capacityMaximumChildren: 0 }); });
  it('rechaza Business inexistente y archivado sin consultar Resource', async () => { findById.mockResolvedValueOnce(null); await expect(useCase.execute(input({ name: 'Nueva' }))).rejects.toEqual(new ResourceBusinessNotFoundError('El negocio no existe.')); expect(findByIdAndBusinessId).not.toHaveBeenCalled(); findById.mockResolvedValueOnce(makeBusiness(BusinessStatus.ARCHIVED)); await expect(useCase.execute(input({ name: 'Nueva' }))).rejects.toEqual(new ResourceBusinessArchivedError('El negocio está archivado.')); expect(update).not.toHaveBeenCalled(); });
  it('rechaza Resource inexistente y archivado', async () => { findByIdAndBusinessId.mockResolvedValueOnce(null); await expect(useCase.execute(input({ name: 'Nueva' }))).rejects.toEqual(new ResourceNotFoundError('El recurso no existe.')); findByIdAndBusinessId.mockResolvedValueOnce(makeResource({ status: ResourceStatus.ARCHIVED })); await expect(useCase.execute(input({ name: 'Nueva' }))).rejects.toEqual(new ResourceArchivedError('El recurso está archivado.')); });
  it('permite OUT_OF_SERVICE y el mismo código propio', async () => { const out = makeResource({ status: ResourceStatus.OUT_OF_SERVICE }); findByIdAndBusinessId.mockResolvedValue(out); findByBusinessAndCode.mockResolvedValue(out); await expect(useCase.execute(input({ internalCode: ' norte ' }))).resolves.toMatchObject({ internalCode: 'NORTE', status: ResourceStatus.OUT_OF_SERVICE }); });
  it.each([[1, false], [2, true], [120, true], [121, false]])('valida longitud de name', async (length, valid) => { const promise = useCase.execute(input({ name: 'x'.repeat(length) })); if (valid) await expect(promise).resolves.toMatchObject({ name: 'x'.repeat(length) }); else await expect(promise).rejects.toEqual(new InvalidResourceUpdateError('El nombre es inválido.')); });
  it.each([[1, false], [2, true], [30, true], [31, false], ['A B', false], ['a_b-1', true]])('valida y normaliza internalCode', async (value, valid) => { const promise = useCase.execute(input({ internalCode: typeof value === 'number' ? 'A'.repeat(value) : value })); if (valid) await expect(promise).resolves.toMatchObject({ internalCode: typeof value === 'number' ? 'A'.repeat(value) : 'A_B-1' }); else await expect(promise).rejects.toEqual(new InvalidResourceUpdateError('El código interno es inválido.')); });
  it('rechaza duplicado ajeno sin persistir', async () => { findByBusinessAndCode.mockResolvedValueOnce(makeResource({ id: otherId })); await expect(useCase.execute(input({ internalCode: 'otro' }))).rejects.toEqual(new ResourceCodeAlreadyExistsError('El código interno ya existe.')); expect(update).not.toHaveBeenCalled(); });
  it.each([[null, null], ['', null], ['   ', null], [' texto ', 'texto'], ['x'.repeat(500), 'x'.repeat(500)]])('normaliza descripción', async (value, expected) => { await expect(useCase.execute(input({ description: value }))).resolves.toMatchObject({ description: expected }); });
  it.each([501, true])('rechaza descripción inválida', async (value) => { await expect(useCase.execute(input({ description: typeof value === 'number' ? 'x'.repeat(value) : value }))).rejects.toEqual(new InvalidResourceUpdateError('La descripción es inválida.')); });
  it.each([[{ capacityMaximum: 2 }, 'La capacidad mínima no puede superar la capacidad máxima.'], [{ capacityMaximum: 1 }, 'La capacidad mínima no puede superar la capacidad máxima.'], [{ capacityMaximum: 2, capacityMaximumChildren: 2 }, 'La capacidad mínima no puede superar la capacidad máxima.'], [{ capacityMinimum: 4, capacityMaximum: 4 }, undefined], [{ capacityMaximum: 4, capacityMaximumChildren: 4 }, undefined]])('valida capacidades finales', async (changes, message) => { const promise = useCase.execute(input(changes)); if (message) await expect(promise).rejects.toEqual(new InvalidResourceUpdateError(message)); else await expect(promise).resolves.toBeDefined(); });
  it.each([[{ capacityMaximumChildren: 5 }, 'La capacidad máxima de menores no puede superar la capacidad máxima.'], [{ capacityMinimum: 0 }, 'La capacidad mínima es inválida.'], [{ capacityMaximum: 51 }, 'La capacidad máxima debe ser un entero entre 1 y 50.'], [{ capacityMaximumChildren: -1 }, 'La capacidad máxima de menores es inválida.'], [{ sortOrder: -1 }, 'El orden es inválido.']])('aplica límites de capacidades y orden', async (changes, message) => { await expect(useCase.execute(input(changes))).rejects.toEqual(new InvalidResourceUpdateError(message)); });
  it.each(['capacityMinimum', 'capacityMaximum', 'capacityMaximumChildren', 'sortOrder'])('rechaza enteros inválidos', async (field) => { for (const value of [NaN, Infinity, 1.5, '2', true]) await expect(useCase.execute(input({ [field]: value }))).rejects.toBeInstanceOf(InvalidResourceUpdateError); });
  it('propaga errores inesperados del Business, repositorio y persistencia', async () => { const failure = new Error('fallo'); findById.mockRejectedValueOnce(failure); await expect(useCase.execute(input({ name: 'Nueva' }))).rejects.toBe(failure); findByIdAndBusinessId.mockRejectedValueOnce(failure); await expect(useCase.execute(input({ name: 'Nueva' }))).rejects.toBe(failure); update.mockRejectedValueOnce(failure); await expect(useCase.execute(input({ name: 'Nueva' }))).rejects.toBe(failure); });
  it('propaga un fallo al comprobar código duplicado y conserva campos omitidos', async () => { const failure = new Error('duplicado'); findByBusinessAndCode.mockRejectedValueOnce(failure); await expect(useCase.execute(input({ internalCode: 'nuevo' }))).rejects.toBe(failure); const result = await useCase.execute(input({ name: 'Nueva' })); expect(result).toMatchObject({ internalCode: 'NORTE', description: 'Vista', capacityMinimum: 3, capacityMaximum: 4, capacityMaximumChildren: 2, sortOrder: 4 }); expect(findByBusinessAndCode).toHaveBeenCalledTimes(1); });
});
