import { Link } from "react-router-dom";
import type { ReactNode } from "react";
import { ArrowRight, Plus } from "lucide-react";
import { Button } from "../../../shared/ui/Button";
import { formatBusinessInstant, formatPureDate } from "../../../shared/utils/date-format";
import { formatMoney } from "../../../shared/utils/money";
import type { FinanceMovement, FinanceReport } from "../types/finance.types";
import type { FinanceAction } from "./command-form";
import { sourceLabels } from "./FinanceSourceDetail";

type ActionHandler = (action: FinanceAction, trigger: HTMLElement) => void;
interface Props { report: FinanceReport; onAction: ActionHandler; onExpense: (id: string, trigger: HTMLElement) => void; onAccount?: (id: string, trigger: HTMLElement) => void; onSource?: (source: FinanceMovement, trigger: HTMLElement) => void }
function RegisterButton({ children, action, onAction }: { children: ReactNode; action: FinanceAction; onAction: ActionHandler }) {
  return <Button type="button" variant="secondary" size="sm" onClick={(event) => onAction(action, event.currentTarget)}>{children}</Button>;
}
function Empty({ children }: { children: ReactNode }) { return <p className="finance-empty" role="status">{children}</p>; }
export function ExpensesPanel({ report, onAction, onExpense }: Props) {
  return <section className="finance-panel"><header><div><h2>Gastos y obligaciones</h2><p>Consumo del período seleccionado; pendiente calculado ahora.</p></div><RegisterButton action={{ type: "CREATE_EXPENSE" }} onAction={onAction}><Plus size={16} aria-hidden="true" /> Registrar gasto</RegisterButton></header>
    {report.expenses.length ? <div className="finance-rows">{report.expenses.map((expense) => <article key={expense.id} className="finance-expense-row"><div><button className="finance-text-link" onClick={(event) => onExpense(expense.id, event.currentTarget)}>{expense.description}<ArrowRight size={16} aria-hidden="true" /></button><p>{formatPureDate(expense.consumedOn)} · {expense.counterpartyName ?? "Sin contraparte"}</p><p>{expense.evidenceMissing ? "Evidencia faltante" : expense.reference === null ? "Sin referencia textual; consulta los comprobantes adjuntos." : `Referencia: ${expense.reference}`}</p></div>
      <dl><div><dt>Total</dt><dd>{formatMoney(expense.amountMinor)}</dd></div><div><dt>Pagado</dt><dd>{formatMoney(expense.paidAmountMinor)}</dd></div><div><dt>Pendiente actual</dt><dd>{formatMoney(expense.outstandingMinor)}</dd></div></dl>
      <div><span className={`finance-status${expense.overdue ? " finance-status--warning" : ""}`}>{expense.outstandingMinor === 0 ? "Pagado" : expense.overdue ? "Vencido" : "Pendiente"}</span><p>Vence: {formatPureDate(expense.dueOn)}</p><div className="finance-actions">{expense.outstandingMinor > 0 ? <RegisterButton action={{ type: "SETTLE_EXPENSE", expense }} onAction={onAction}>Registrar pago</RegisterButton> : null}<RegisterButton action={{ type: "SET_EVIDENCE", expense }} onAction={onAction}>Referencia</RegisterButton></div></div>
    </article>)}</div> : <Empty>No hay gastos consumidos en este período. Registra un gasto o cambia las fechas.</Empty>}
  </section>;
}
export function AccountsPanel({ report, onAction, onAccount }: Props) {
  return <><section className="finance-panel"><header><div><h2>Cuentas propias</h2><p>Saldo registrado al inicio de {formatPureDate(report.to)}; excluye movimientos anteriores a la apertura.</p></div><RegisterButton action={{ type: "CREATE_ACCOUNT" }} onAction={onAction}><Plus size={16} aria-hidden="true" /> Agregar cuenta</RegisterButton></header>
    {report.accounts.length ? <div className="finance-account-grid">{report.accounts.map((account) => <article key={account.id}><h3>{account.name}</h3><p>{account.kind === "CASH" ? "Efectivo" : "Banco informativo"}{account.archived ? " · archivada" : ""}</p><strong className="finance-account-balance">{account.balanceMinor === null ? "Saldo desconocido" : formatMoney(account.balanceMinor)}</strong>{account.negative ? <p className="finance-warning">Saldo registrado negativo</p> : null}<p>{account.opening ? `Apertura ${formatMoney(account.opening.amountMinor)} · ${formatBusinessInstant(account.opening.occurredAt, report.timeZone)}` : "Sin apertura informada. Los movimientos no permiten afirmar un saldo conocido."}</p>
      {onAccount ? <Button type="button" variant="secondary" size="sm" onClick={(event) => onAccount(account.id, event.currentTarget)}>Ver origen del saldo</Button> : null}
      {!account.archived ? <div className="finance-actions">{account.opening ? <RegisterButton action={{ type: "CASH_MOVEMENT", account, openingCorrection: true }} onAction={onAction}>Corregir apertura</RegisterButton> : <RegisterButton action={{ type: "OPEN_ACCOUNT", account }} onAction={onAction}>Registrar apertura</RegisterButton>}<RegisterButton action={{ type: "ARCHIVE_ACCOUNT", account }} onAction={onAction}>Archivar</RegisterButton></div> : null}</article>)}</div> : <Empty>No hay cuentas. Agrega una caja o cuenta bancaria informativa con una apertura explícita.</Empty>}
  </section><section className="finance-panel"><header><div><h2>Categorías y contrapartes</h2><p>El archivo conserva los datos utilizados por gastos históricos.</p></div><RegisterButton action={{ type: "CREATE_CATALOG" }} onAction={onAction}>Agregar categoría o contraparte</RegisterButton></header>
    {report.catalogs.length ? <ul className="finance-catalog-list">{report.catalogs.map((catalog) => <li key={catalog.id}><span><strong>{catalog.name}</strong> · {catalog.kind === "CATEGORY" ? "Categoría" : "Contraparte"}{catalog.archived ? " · archivada" : ""}</span>{!catalog.archived ? <RegisterButton action={{ type: "ARCHIVE_CATALOG", catalog }} onAction={onAction}>Archivar</RegisterButton> : null}</li>)}</ul> : <Empty>Crea una categoría para registrar el detalle de un gasto.</Empty>}
  </section></>;
}
export function MovementsPanel({ report, onAction, onSource }: Props) {
  const accountName = (id: string) => report.accounts.find((account) => account.id === id)?.name ?? "Cuenta";
  return <><section className="finance-panel"><header><div><h2>Movimientos registrados</h2><p>La revisión manual no equivale a conciliación bancaria.</p></div><div className="finance-actions"><RegisterButton action={{ type: "TRANSFER" }} onAction={onAction}>Transferencia interna</RegisterButton><RegisterButton action={{ type: "CASH_MOVEMENT" }} onAction={onAction}>Aporte, retiro o ajuste</RegisterButton></div></header>
    {report.movements.length ? <div className="finance-rows">{report.movements.map((movement) => <article key={movement.id} className="finance-movement-row"><div><strong>{movement.description}</strong><p>{accountName(movement.accountId)} · {formatBusinessInstant(movement.occurredAt, report.timeZone)}</p><p>{movement.includedInBalance ? "Incluido en saldo" : "Fuera del corte de apertura; no suma al saldo"} · {sourceLabels[movement.sourceType]} · versión {movement.sourceVersion}</p>{onSource ? <Button type="button" variant="ghost" size="sm" onClick={(event) => onSource(movement, event.currentTarget)}>Ver origen e historial</Button> : null}</div><strong className="finance-amount">{formatMoney(movement.amountMinor)}</strong><div><p>{movement.reviewStale ? "Revisión desactualizada" : movement.reviewed ? "Revisado manualmente" : "Sin revisar"}</p>{movement.reviewDetails ? <p>Revisó: {movement.reviewDetails.actorUserId} · {formatBusinessInstant(movement.reviewDetails.occurredAt, report.timeZone)} · {movement.reviewDetails.reason}</p> : null}<RegisterButton action={{ type: "REVIEW_MOVEMENT", movement }} onAction={onAction}>{movement.reviewed && !movement.reviewStale ? "Quitar revisión" : "Marcar revisado"}</RegisterButton></div></article>)}</div> : <Empty>No hay movimientos en este período.</Empty>}
  </section><section className="finance-panel"><header><div><h2>Arqueos de efectivo</h2><p>El conteo conserva la diferencia; un ajuste requiere otro registro explícito.</p></div><RegisterButton action={{ type: "COUNT_CASH" }} onAction={onAction}>Registrar arqueo</RegisterButton></header>
    {report.cashCounts.length ? <div className="finance-rows">{report.cashCounts.map((count) => <article className="finance-count-row" key={count.id}><div><strong>{accountName(count.accountId)}</strong><p>{formatBusinessInstant(count.occurredAt, report.timeZone)}</p><p>{count.reason}</p></div><dl><div><dt>Esperado</dt><dd>{formatMoney(count.expectedAmountMinor)}</dd></div><div><dt>Contado</dt><dd>{formatMoney(count.countedAmountMinor)}</dd></div><div><dt>Diferencia</dt><dd>{formatMoney(count.differenceMinor)}</dd></div></dl>{count.adjustmentId ? <span>Ajuste registrado</span> : count.differenceMinor !== 0 ? <RegisterButton action={{ type: "ADJUST_COUNT", count }} onAction={onAction}>Registrar ajuste</RegisterButton> : <span>Sin diferencia</span>}</article>)}</div> : <Empty>No hay arqueos en este período.</Empty>}
  </section></>;
}
export function PaymentsPanel({ report, onAction }: Props) {
  return <section className="finance-panel"><header><div><h2>Cobros de reservas</h2><p>El bruto conserva el original; los reversos y devoluciones conservan su origen y versión. Las devoluciones del período también aparecen en Movimientos, aunque el cobro original sea anterior.</p></div><Link className="finance-text-link" to="/app/payments">Gestionar cobros <ArrowRight size={16} aria-hidden="true" /></Link></header>
    {report.payments.length ? <div className="finance-rows">{report.payments.map((payment) => <article key={payment.id} className="finance-payment-row"><div><Link to={`/app/bookings/${payment.bookingId}/payments`} className="finance-text-link">Reserva {payment.bookingId.slice(0, 8)}<ArrowRight size={16} aria-hidden="true" /></Link><p>Estado: {({RETAINED:"Retenido",PARTIALLY_REFUNDED:"Devuelto parcialmente",REFUNDED:"Devuelto por completo",VOIDED:"Anulado"} as const)[payment.effectiveStatus]} · versión del cobro {payment.paymentVersion}</p><p>{formatBusinessInstant(payment.paidAt, report.timeZone)} · {payment.reference ?? "Sin referencia"}</p><p>{payment.accountId ? report.accounts.find((account) => account.id === payment.accountId)?.name ?? "Cuenta archivada" : "Sin cuenta asignada"}{payment.accountId && !payment.includedInBalance ? " · anterior al corte de apertura" : ""}</p></div><dl className="finance-payment-amounts"><div><dt>Bruto registrado</dt><dd>{formatMoney(payment.grossRecordedAmountMinor, payment.currency)}</dd></div><div><dt>Anulado</dt><dd>{formatMoney(payment.voidedAmountMinor, payment.currency)}</dd></div><div><dt>Devuelto hasta el corte</dt><dd>{formatMoney(payment.refundedAmountMinor, payment.currency)}</dd></div><div><dt>Neto retenido al corte</dt><dd>{formatMoney(payment.netRetainedAmountMinor, payment.currency)}</dd></div></dl><RegisterButton action={{ type: "LINK_PAYMENT", payment }} onAction={onAction}>{payment.accountId ? "Corregir cuenta" : "Asignar cuenta"}</RegisterButton></article>)}</div> : <Empty>No hay cobros registrados en este período.</Empty>}
  </section>;
}
