import { deriveFinanceAlerts,FinanceAlertExpenseFact } from './finance-v2-alerts.rules';
const expense:FinanceAlertExpenseFact={id:'expense',version:1,description:'Compra',outstandingMinor:500,dueOn:'2026-09-30',reference:'Factura',hasEvidenceFile:false};
describe('FIN031 readonly alerts from live facts',()=>{
  const input={expenses:[expense],cashCounts:[],pendingService:[]};
  it('settlement to zero removes overdue alert without persisting a fake resolved record',()=>{expect(deriveFinanceAlerts('2026-10-01',input).map(row=>row.kind)).toEqual(['OVERDUE_PAYABLE']);expect(deriveFinanceAlerts('2026-10-01',{...input,expenses:[{...expense,version:2,outstandingMinor:0}]})).toEqual([]);});
  it('refresh with unchanged sources gives the same stable alert id',()=>{const one=deriveFinanceAlerts('2026-10-01',input);const two=deriveFinanceAlerts('2026-10-02',input);expect(one[0].id).toBe(two[0].id);expect(deriveFinanceAlerts('2026-10-01',{...input,expenses:[{...expense,version:2}]} )[0].id).not.toBe(one[0].id);});
  it('due today and unknown due date are not overdue',()=>{expect(deriveFinanceAlerts('2026-09-30',input)).toEqual([]);expect(deriveFinanceAlerts('2026-10-01',{...input,expenses:[{...expense,dueOn:null}]})).toEqual([]);});
  it('missing evidence is independent of debt and uses a typed expense link',()=>{const result=deriveFinanceAlerts('2026-10-01',{...input,expenses:[{...expense,outstandingMinor:0,reference:null}]});expect(result[0]).toMatchObject({kind:'MISSING_EXPENSE_EVIDENCE',amountMinor:null,target:{type:'EXPENSE',id:'expense'}});});
  it('unresolved latest count shows signed discrepancy; linked adjustment removes it',()=>{const count={id:'count',accountId:'account',version:1,differenceMinor:-25,adjustmentId:null};expect(deriveFinanceAlerts('2026-10-01',{expenses:[],cashCounts:[count],pendingService:[]})[0]).toMatchObject({kind:'UNRESOLVED_CASH_DIFFERENCE',amountMinor:-25,target:{type:'CASH_COUNT',id:'count',accountId:'account'}});expect(deriveFinanceAlerts('2026-10-01',{expenses:[],cashCounts:[{...count,adjustmentId:'adjust'}],pendingService:[]})).toEqual([]);});
  it('service evidence alerts only elapsed local nights and has no invented revenue',()=>{const source={sourceId:'booking:2026-09-30',sourceVersion:'hash',bookingId:'booking',localNight:'2026-09-30',reason:'Falta certificación'};const rows=deriveFinanceAlerts('2026-10-01',{expenses:[],cashCounts:[],pendingService:[source,{...source,sourceId:'booking:2026-10-01',localNight:'2026-10-01'}]});expect(rows).toHaveLength(1);expect(rows[0]).toMatchObject({kind:'PENDING_SERVICE_EVIDENCE',amountMinor:null,target:{type:'SERVICE_NIGHT',bookingId:'booking',localNight:'2026-09-30'}});});
});
