import { composeFinanceReceivables,FinanceBookingFinancialBasis,FinancePaymentObligationBasis } from './finance-v2-receivable.rules';
const booking:FinanceBookingFinancialBasis={bookingId:'b',sourceVersion:2,currency:'PYG',pricingStatus:'CURRENT',agreedMinor:100,pricingToken:'price-a'};
function payment():FinancePaymentObligationBasis{return{complete:true,token:'pay-a',payments:[{id:'p',bookingId:'b',currency:'PYG',status:'RECORDED',netRetainedAmountMinor:40,paymentVersion:1}],paymentPlans:[{id:'plan',bookingId:'b',currency:'PYG',totalAmountMinor:100}],installments:[{id:'i1',paymentPlanId:'plan',amountMinor:40,dueDate:'2026-09-01'},{id:'i2',paymentPlanId:'plan',amountMinor:60,dueDate:'2026-10-01'}],applications:[{paymentId:'p',installmentId:'i1',effectiveAmountMinor:40}]};}
describe('actual obligation sources from public Booking/Pricing/Payment',()=>{
  it('takes explicit unpaid installment and excludes applied paid installment',()=>{const result=composeFinanceReceivables([booking],payment());expect(result.rows).toEqual([{sourceKey:'PAYMENT_INSTALLMENT:i2',bookingId:'b',amountMinor:60,dueOn:'2026-10-01',sourceVersion:2,needsReview:false}]);});
  it('cannot call unpaid installments overdue when retained receipt has not been applied',()=>{const basis=payment();basis.applications=[];const result=composeFinanceReceivables([booking],basis);expect(result.rows).toEqual([{sourceKey:'BOOKING:b',bookingId:'b',amountMinor:60,dueOn:null,sourceVersion:2,needsReview:true}]);expect(result.reviewBookingIds).toEqual(['b']);});
  it('reports current credits separately and never as negative debt',()=>{const result=composeFinanceReceivables([{...booking,agreedMinor:30}],payment());expect(result.rows).toEqual([]);expect(result.credits).toEqual([{bookingId:'b',amountMinor:10}]);});
  it('does not turn missing/currently uncertain price into zero debt',()=>{const result=composeFinanceReceivables([{...booking,pricingStatus:'REVIEW',agreedMinor:null}],payment());expect(result.rows).toEqual([]);expect(result.reviewBookingIds).toEqual(['b']);});
  it('refund restores only reversed effective installment application',()=>{const basis=payment();basis.payments=[{...basis.payments[0],netRetainedAmountMinor:20,paymentVersion:2}];basis.applications=[{paymentId:'p',installmentId:'i1',effectiveAmountMinor:20}];const result=composeFinanceReceivables([booking],basis);expect(result.rows.map(row=>row.amountMinor)).toEqual([20,60]);});
  it('a plan changed after the requested cut cannot fabricate history',()=>{expect(()=>composeFinanceReceivables([booking],{...payment(),complete:false})).toThrow();});
  it('mixed currency, repeated booking and invalid plan arithmetic fail closed',()=>{expect(()=>composeFinanceReceivables([booking],{...payment(),payments:[{...payment().payments[0],currency:'USD'}]})).toThrow();expect(()=>composeFinanceReceivables([booking,booking],payment())).toThrow();expect(()=>composeFinanceReceivables([booking],{...payment(),installments:[{...payment().installments[0],amountMinor:110}]})).toThrow();});
});
