import { createHash, randomUUID } from 'node:crypto';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { DeleteObjectCommand, GetObjectCommand, HeadObjectCommand, ListObjectsV2Command, PutObjectCommand, S3Client, type GetObjectCommandOutput } from '@aws-sdk/client-s3';
import { PrismaClient } from '@prisma/client';
import { AuthorizationPolicy, Capability } from '../../../src/shared/application/authorization-policy';
import { MembershipRole } from '../../../src/modules/identity/domain/membership-role.enum';
import { readS3Configuration } from '../../../src/config/environment';
import { createFinanceEvidencePersistence } from '../../../src/modules/finance/infrastructure/finance-evidence.factory';
import { FinanceEvidenceS3Storage } from '../../../src/modules/finance/infrastructure/finance-evidence-s3.storage';
import { FinanceV2PrismaSqlHost } from '../../../src/modules/finance/infrastructure/finance-v2-prisma-sql.adapter';
import { validateFinanceEvidenceFile } from '../../../src/modules/finance/domain/finance-evidence-file.rules';

const execFileAsync=promisify(execFile);
export const evidencePdf=Buffer.from('%PDF-1.4\n1 0 obj\n<< /Type /Catalog >>\nendobj\nstartxref\n0\n%%EOF\n');
export const evidencePng=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64');
export const evidenceHash=(bytes:Uint8Array):string=>createHash('sha256').update(bytes).digest('hex');

export function exactLimitEvidencePdf():Buffer {
  const suffix=Buffer.from('\nstartxref\n0\n%%EOF\n'),prefix=Buffer.from('%PDF-1.4\n% synthetic boundary fixture\n');
  return Buffer.concat([prefix,Buffer.alloc(2097152-prefix.length-suffix.length,0x20),suffix]);
}
function required(name:string):string {
  const value=process.env[name];if(!value)throw new Error(`Files real QA requires ${name}.`);return value;
}
function bucket(name:string):string {
  const value=required(name);if(!/^top-finance-files(?:-restore)?-test-[a-f0-9]{32}$/.test(value))throw new Error('Files QA bucket must be an explicitly named root-owned synthetic resource.');return value;
}
function configuration(privateBucket:string):{get(key:string):unknown}{
  return {get:key=>key==='FINANCE_S3_BUCKET'||key==='S3_BUCKET'?privateBucket:process.env[key]};
}
export interface FilesProviderFixture {client:S3Client;bucket:string;restoreBucket:string;ownerId:string;storage:FinanceEvidenceS3Storage}

/** Read-only resource attestation. Root must create the two private buckets and ownership sentinels. */
export async function ownedFilesProviderFixture():Promise<FilesProviderFixture> {
  if(required('FINANCE_EVIDENCE_STORAGE')!=='s3-private')throw new Error('Files real QA requires the real private provider.');
  const main=bucket('TEST_FINANCE_S3_BUCKET'),restore=bucket('TEST_FINANCE_S3_RESTORE_BUCKET');
  if(main!==required('FINANCE_S3_BUCKET')||main===restore)throw new Error('Files QA requires separate original and restore buckets.');
  const ownerId=required('TEST_FINANCE_S3_OWNER_ID');if(!/^[0-9a-f]{32}$/i.test(ownerId))throw new Error('Files QA requires the explicit root-generated hex ownership marker.');
  const config=readS3Configuration(configuration(main)),endpoint=new URL(config.endpoint);
  if(!['localhost','127.0.0.1','[::1]'].includes(endpoint.hostname))throw new Error('Files QA permits only the root-owned loopback provider.');
  const client=new S3Client({endpoint:config.endpoint,region:config.region,forcePathStyle:config.forcePathStyle,credentials:{accessKeyId:config.accessKeyId,secretAccessKey:config.secretAccessKey}});
  try {await Promise.all([main,restore].map(async value=>{
    const sentinel=await client.send(new HeadObjectCommand({Bucket:value,Key:`qa-owned/${ownerId}`}));
    if(sentinel.Metadata?.owner!==ownerId||sentinel.Metadata?.purpose!=='fin032-synthetic-test')throw new Error('Files provider ownership sentinel does not match.');
  }));}catch(error){client.destroy();throw error;}
  return {client,bucket:main,restoreBucket:restore,ownerId,storage:new FinanceEvidenceS3Storage(configuration(main),{privateBucket:true})};
}

export function realFilesPersistence(prisma:PrismaClient,provider:FilesProviderFixture,restored=false):ReturnType<typeof createFinanceEvidencePersistence> {
  const policy=new AuthorizationPolicy(),storage=restored?new FinanceEvidenceS3Storage(configuration(provider.restoreBucket),{privateBucket:true}):provider.storage;
  return createFinanceEvidencePersistence({host:new FinanceV2PrismaSqlHost(prisma),storage,capabilities:{allows:(role,operation)=>policy.isAllowed(role as MembershipRole,operation==='READ'?Capability.FINANCE_EVIDENCE_READ:Capability.FINANCE_EVIDENCE_WRITE)}});
}

/** Test teardown only: exact UUID tenant prefixes generated by this suite; never a runtime purge. */
export async function ownEvidenceKeys(provider:FilesProviderFixture,businessId:string,restore=false):Promise<string[]> {
  if(!/^[0-9a-f-]{36}$/i.test(businessId))throw new Error('Files teardown requires an explicit generated tenant UUID.');
  const prefix=`finance-evidence/${businessId}/`,keys:string[]=[];let continuationToken:string|undefined;
  do {
    const page=await provider.client.send(new ListObjectsV2Command({Bucket:restore?provider.restoreBucket:provider.bucket,Prefix:prefix,ContinuationToken:continuationToken}));
    for(const object of page.Contents??[]){if(!object.Key?.startsWith(prefix))throw new Error('Files provider returned a foreign key.');keys.push(object.Key);}
    if(keys.length>5000)throw new Error('Files QA source limit exceeded.');continuationToken=page.NextContinuationToken;
  }while(continuationToken);
  return keys;
}
export async function removeOwnEvidenceKeys(provider:FilesProviderFixture,businessId:string):Promise<void>{
  for(const restored of [false,true])for(const key of await ownEvidenceKeys(provider,businessId,restored))await provider.client.send(new DeleteObjectCommand({Bucket:restored?provider.restoreBucket:provider.bucket,Key:key}));
}

function testDatabase(urlText:string):URL {
  const url=new URL(urlText);
  if(!['localhost','127.0.0.1','[::1]'].includes(url.hostname)||!/^\/[a-z0-9_]*test[a-z0-9_]*$/i.test(url.pathname)||decodeURIComponent(url.username)!==required('TEST_DATABASE_OWNER'))throw new Error('Files restore requires an explicitly owned loopback test database.');
  return url;
}
export async function restoredFilesDatabase():Promise<PrismaClient>{
  const url=required('TEST_FINANCE_RESTORE_DATABASE_URL');testDatabase(url);
  if(url===required('DATABASE_URL'))throw new Error('Files restore destination must differ from the source.');
  const prisma=new PrismaClient({datasources:{db:{url}}});
  const identity=await prisma.$queryRaw<{database:string;owner:string}[]>`SELECT current_database() AS database,current_user AS owner`;
  if(identity[0]?.owner!==required('TEST_DATABASE_OWNER')||identity[0]?.database!==decodeURIComponent(new URL(url).pathname.slice(1))){await prisma.$disconnect();throw new Error('Files restore target identity mismatch.');}
  return prisma;
}
interface OwnedPostgresInspection {Id:string;Config:{Labels:Record<string,string>};State:{Running:boolean};Mounts:{Type:string}[]}
async function restoreContainer():Promise<{containerId:string;runId:string}> {
  const containerId=required('TEST_FINANCE_PG_CONTAINER_ID'),runId=required('TEST_FINANCE_PG_RUN_ID');
  if(!/^[a-f0-9]{64}$/.test(containerId)||!/^[a-f0-9]{32}$/.test(runId))throw new Error('Files restore requires exact owned PostgreSQL container IDs.');
  const result=await execFileAsync('docker',['inspect',containerId],{timeout:10000,windowsHide:true});
  const inspections=JSON.parse(result.stdout)as OwnedPostgresInspection[],current=inspections[0];
  if(inspections.length!==1||current?.Id!==containerId||current.Config.Labels['top.portable.qa.run']!==runId||!current.State.Running||current.Mounts.some(mount=>mount.Type==='bind'||mount.Type==='volume'))throw new Error('Files restore PostgreSQL container ownership or tmpfs isolation mismatch.');
  return{containerId,runId};
}
/** Full own test DB dump/restore inside the attested root container; no shell, URLs, credentials or persistent mounts. */
export async function restoreFilesDatabaseCopy():Promise<void> {
  const source=testDatabase(required('DATABASE_URL')),target=testDatabase(required('TEST_FINANCE_RESTORE_DATABASE_URL'));
  if(source.pathname===target.pathname||required('DATABASE_URL')!==required('TEST_DATABASE_URL'))throw new Error('Files restore requires separate database names and explicit source test attestation.');
  if(source.hostname!==target.hostname||source.port!==target.port||source.port!=='55473')throw new Error('Files restore requires both databases on the owned PostgreSQL loopback port.');
  const{containerId,runId}=await restoreContainer(),dump=`/tmp/finance-evidence-restore-${runId}-${randomUUID()}.dump`,actor=required('TEST_DATABASE_OWNER');
  try {
    await execFileAsync('docker',['exec',containerId,'pg_dump','--username',actor,'--dbname',decodeURIComponent(source.pathname.slice(1)),'--format=custom','--no-owner','--no-privileges','--file',dump],{timeout:60000,windowsHide:true});
    await execFileAsync('docker',['exec',containerId,'pg_restore','--username',actor,'--clean','--if-exists','--no-owner','--no-privileges','--exit-on-error','--dbname',decodeURIComponent(target.pathname.slice(1)),dump],{timeout:60000,windowsHide:true});
  }finally{await execFileAsync('docker',['exec',containerId,'rm','-f',dump],{timeout:10000,windowsHide:true}).catch(()=>undefined);}
}
function restoreEvidenceObjectSize(length:number|undefined):number {
  if(length===undefined||!Number.isSafeInteger(length)||length<1||length>2097152)throw new Error('Files restore source object unavailable or exceeds the byte limit.');
  return length;
}
async function readRestoreEvidenceObject(result:GetObjectCommandOutput):Promise<Buffer> {
  if(!result.Body)throw new Error('Files restore source object unavailable.');
  const bytes=Buffer.alloc(restoreEvidenceObjectSize(result.ContentLength));let consumed=0;
  for await(const chunk of result.Body as AsyncIterable<Uint8Array>){if(!(chunk instanceof Uint8Array)||consumed+chunk.byteLength>bytes.length)throw new Error('Files restore source stream exceeds its declared size.');bytes.set(chunk,consumed);consumed+=chunk.byteLength;}
  if(consumed!==bytes.length||result.Metadata?.sha256!==evidenceHash(bytes))throw new Error('Files restore object integrity mismatch.');
  validateFinanceEvidenceFile({filename:'restored-proof',mimeType:result.ContentType,bytes});return bytes;
}
export async function copyOwnEvidenceToRestore(provider:FilesProviderFixture,businessId:string):Promise<void> {
  for(const key of await ownEvidenceKeys(provider,businessId)){
    const result=await provider.client.send(new GetObjectCommand({Bucket:provider.bucket,Key:key})),bytes=await readRestoreEvidenceObject(result);
    await provider.client.send(new PutObjectCommand({Bucket:provider.restoreBucket,Key:key,Body:bytes,ContentType:result.ContentType,ContentLength:bytes.length,Metadata:result.Metadata,ACL:'private',IfNoneMatch:'*'}));
  }
}
export function filesCommandKey():string{return `files-real-${randomUUID()}`;}
