import type { RegisterPaymentPayload } from "../types/payment.types";
const VERSION = 1; const prefix = "top.payment-attempt.v1";
export interface PaymentAttempt { version: 1; idempotencyKey: string; userId: string; businessId: string; bookingId: string; payload: RegisterPaymentPayload; }
export type PaymentAttemptRead = { state: "absent" } | { state: "valid"; attempt: PaymentAttempt } | { state: "corrupt" };
function key(userId: string, businessId: string, bookingId: string) { return `${prefix}:${encodeURIComponent(userId)}:${encodeURIComponent(businessId)}:${encodeURIComponent(bookingId)}`; }
function validPayload(value: unknown): value is RegisterPaymentPayload { if (!value || typeof value !== "object") return false; const payload = value as RegisterPaymentPayload; return Number.isSafeInteger(payload.amountMinor) && payload.amountMinor > 0 && ["CASH", "BANK_TRANSFER", "CARD", "OTHER"].includes(payload.method) && typeof payload.paidAt === "string" && !Number.isNaN(new Date(payload.paidAt).valueOf()) && (payload.reference === undefined || typeof payload.reference === "string") && (payload.note === undefined || typeof payload.note === "string"); }
export function readPaymentAttemptResult(userId: string, businessId: string, bookingId: string): PaymentAttemptRead { try { const raw = sessionStorage.getItem(key(userId, businessId, bookingId)); if (raw === null) return { state: "absent" }; const value: unknown = JSON.parse(raw); if (!value || typeof value !== "object") return { state: "corrupt" }; const attempt = value as PaymentAttempt; return attempt.version === VERSION && attempt.userId === userId && attempt.businessId === businessId && attempt.bookingId === bookingId && typeof attempt.idempotencyKey === "string" && !!attempt.idempotencyKey && validPayload(attempt.payload) ? { state: "valid", attempt } : { state: "corrupt" }; } catch { return { state: "corrupt" }; } }
export function readPaymentAttempt(userId: string, businessId: string, bookingId: string): PaymentAttempt | null { const result = readPaymentAttemptResult(userId, businessId, bookingId); return result.state === "valid" ? result.attempt : null; }
export function writePaymentAttempt(attempt: PaymentAttempt): boolean { try { sessionStorage.setItem(key(attempt.userId, attempt.businessId, attempt.bookingId), JSON.stringify(attempt)); return true; } catch { return false; } }
export function clearPaymentAttempt(userId: string, businessId: string, bookingId: string) { try { sessionStorage.removeItem(key(userId, businessId, bookingId)); } catch { /* storage is best effort */ } }
export function clearAllPaymentAttempts() { try { for (let index = sessionStorage.length - 1; index >= 0; index -= 1) { const storageKey = sessionStorage.key(index); if (storageKey?.startsWith(`${prefix}:`)) sessionStorage.removeItem(storageKey); } } catch { /* logout remains authoritative */ } }
