import { compareFinanceV2Budget } from './finance-v2-budget.comparison-reader';
import type { FinanceBudgetDto,FinanceCostReport,FinanceCommitmentDto } from '../domain/finance-v2.types';
const budget:FinanceBudgetDto={id:'budget',businessId:'biz',periodMonth:'2026-09',kind:'OPERATING_COST',version:3,approvedRevisionId:'approved',revisions:[{id:'approved',revisionNo:1,lines:[{id:'line',ordinal:0,categoryId:'cat',resourceId:'r',approvedMinor:100}],recordedByUserId:'owner',reason:'Aprobado',createdAt:'now',approvedByUserId:'owner',approvedAt:'now'},{id:'draft',revisionNo:2,lines:[{id:'line2',ordinal:0,categoryId:'cat',resourceId:'r',approvedMinor:1000}],recordedByUserId:'owner',reason:'Pendiente',createdAt:'now',approvedByUserId:null,approvedAt:null}]};
function costs():FinanceCostReport{return{businessId:'biz',currency:'PYG',timeZone:'America/Asuncion',from:'2026-09-01',to:'2026-10-01',asOf:'now',token:'cost-a',sourceLimit:5000,basis:'SOURCE_COSTS',rows:[{source:{kind:'EXPENSE_LINE',id:'src',version:1,hash:'hash'},expenseId:'expense',expenseLineId:'src',bookingId:null,resourceId:null,categoryId:'cat',consumedOn:'2026-09-15',basis:'ACTUAL',kind:'COMMON',amountMinor:100,ruleId:'rule',ruleVersion:1,allocationVersion:1,destinations:[{resourceId:'r',amountMinor:75}],unassignedMinor:25}],totals:{actualCostMinor:100,estimatedSelectedMinor:0,ownerImputedMinor:0,unknownSourceCount:0},coverage:{missingEvidenceSourceIds:[],unknownSourceIds:[],unsupportedReasons:[]}};}
function commitment():FinanceCommitmentDto{return{id:'commit',businessId:'biz',description:'Compra',amountMinor:100,categoryId:'cat',resourceId:'r',expectedConsumptionOn:'2026-09-15',dueOn:null,operational:true,reference:null,reason:'Plan',version:2,state:'ACTIVE',consumedMinor:40,pendingMinor:60,recordedByUserId:'owner',createdAt:'now',conversions:[{id:'x',expenseId:'expense',consumedMinor:40,recordedByUserId:'owner',createdAt:'now'}]};}
describe('budget comparison from source allocations, no double cost or forecast',()=>{
  it('uses approved snapshot and resource destinations plus explicit unassigned remainder',()=>{const result=compareFinanceV2Budget({budget,costs:costs(),commitments:[commitment()]});expect(result.lines.find(line=>line.resourceId==='r')).toMatchObject({approvedMinor:100,actualMinor:75,committedPendingMinor:60,actualDeviationMinor:-25,forecastMinor:null,forecastDeviationMinor:null});expect(result.lines.find(line=>line.resourceId===null)).toMatchObject({approvedMinor:null,actualMinor:25,committedPendingMinor:0,actualDeviationMinor:null});expect(result.forecastBasis).toBeNull();});
  it('conversion leaves actual source and pending remainder once; cancelled/future commitments absent',()=>{const result=compareFinanceV2Budget({budget,costs:costs(),commitments:[{...commitment(),state:'CANCELLED'},{...commitment(),id:'future',expectedConsumptionOn:'2026-10-15'}]});expect(result.lines.find(line=>line.resourceId==='r')?.committedPendingMinor).toBe(0);});
  it('never invents approved budget zero when none approved; source changes alter token',()=>{const one=compareFinanceV2Budget({budget:{...budget,approvedRevisionId:null},costs:costs(),commitments:[]});expect(one.lines.every(line=>line.approvedMinor===null)).toBe(true);const two=compareFinanceV2Budget({budget,costs:costs(),commitments:[commitment()]});expect(two.token).not.toBe(one.token);expect(()=>compareFinanceV2Budget({budget:null,costs:costs(),commitments:[]})).toThrow();});
});
