ALTER TYPE "ConversationSessionState" ADD VALUE 'AVAILABILITY_ASK_CHECK_IN';
ALTER TYPE "ConversationSessionState" ADD VALUE 'AVAILABILITY_ASK_CHECK_OUT';
ALTER TYPE "ConversationSessionState" ADD VALUE 'AVAILABILITY_ASK_GUESTS';
ALTER TYPE "ConversationSessionState" ADD VALUE 'AVAILABILITY_RESULTS';
