import { ArrowDown, Mail, Menu, Phone, X } from "lucide-react";
import { motion, useReducedMotion } from "motion/react";
import { FormEvent, useState } from "react";

const navLinks = [{ label: "Operación", href: "#features" }, { label: "Tarifas", href: "#pricing" }, { label: "Acerca de TOP", href: "#footer" }, { label: "Recursos", href: "#footer" }, { label: "Preguntas frecuentes", href: "#footer" }];

export function SaasLaunchCta() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const reducedMotion = useReducedMotion() ?? false;
  function onSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitted(true); }
  return <section className="saas-cta" id="contact" aria-labelledby="saas-cta-title"><div className="saas-cta__frame"><header className="saas-cta__header"><a className="saas-cta__brand" href="#top">TOP</a><nav className="saas-cta__desktop-nav" aria-label="Navegación del contacto">{navLinks.map((link) => <a key={link.label} href={link.href}>{link.label}</a>)}</nav><a className="saas-cta__login" href="/login">Iniciar sesión</a><button className="saas-cta__menu" type="button" aria-label={menuOpen ? "Cerrar navegación" : "Abrir navegación"} aria-expanded={menuOpen} onClick={() => setMenuOpen((value) => !value)}>{menuOpen ? <X size={22} aria-hidden="true" /> : <Menu size={22} aria-hidden="true" />}</button></header>{menuOpen ? <nav className="saas-cta__mobile-nav" aria-label="Navegación móvil del contacto">{navLinks.map((link) => <a key={link.label} href={link.href} onClick={() => setMenuOpen(false)}>{link.label}<ArrowDown size={15} aria-hidden="true" /></a>)}<a href="/login">Iniciar sesión</a></nav> : null}
    <div className="saas-cta__content"><div className="saas-cta__intro"><motion.span className="saas-eyebrow saas-eyebrow--dark" initial={{ opacity: 0, y: reducedMotion ? 0 : 10 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: reducedMotion ? 0 : 0.6 }}>ESTAMOS PARA ACOMPAÑARTE</motion.span><motion.h2 id="saas-cta-title" initial={{ opacity: 0, y: reducedMotion ? 0 : 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: reducedMotion ? 0 : 0.7, delay: reducedMotion ? 0 : 0.08 }}>Operá mejor,<br /><span>recibí mejor.</span></motion.h2><motion.p initial={{ opacity: 0, y: reducedMotion ? 0 : 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: reducedMotion ? 0 : 0.7, delay: reducedMotion ? 0 : 0.14 }}>¿Tenés una idea o querés conocer TOP? Conversemos sobre cómo hacer más simple el día a día de tu alojamiento.</motion.p><div className="saas-cta__contact-list"><a href="mailto:hola@topplatform.app"><span><Mail size={21} aria-hidden="true" /></span><small>E-mail</small><strong>hola@topplatform.app</strong></a><a href="tel:+595000000"><span><Phone size={21} aria-hidden="true" /></span><small>Contacto</small><strong>+595 (000) 000 000</strong></a></div></div>
      <motion.div className="saas-cta__form-panel" initial={{ opacity: 0, y: reducedMotion ? 0 : 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: reducedMotion ? 0 : 0.8, delay: reducedMotion ? 0 : 0.18 }}><div className="saas-cta__form-heading"><h3>Conocé TOP</h3><p>Dejanos tus datos y te mostramos una operación pensada para alojamientos pequeños.</p></div><form onSubmit={onSubmit} className="saas-cta__form"><label>Nombre completo<input required name="name" type="text" placeholder="Tu nombre" autoComplete="name" /></label><label>Correo electrónico<input required name="email" type="email" placeholder="vos@ejemplo.com" autoComplete="email" /></label><div className="saas-cta__form-row"><label>Contraseña<input required minLength={8} name="password" type="password" placeholder="Elegí una contraseña" autoComplete="new-password" /></label><label>Confirmar contraseña<input required minLength={8} name="passwordConfirmation" type="password" placeholder="Repetí la contraseña" autoComplete="new-password" /></label></div><p className="saas-cta__hint">Para esta demo, el formulario no crea una cuenta ni envía datos.</p>{submitted ? <p className="saas-cta__success" role="status">Gracias. Esta interacción es sólo una demostración de la página.</p> : null}<button type="submit">Enviar consulta</button><p className="saas-cta__form-footnote">¿Ya tenés una cuenta? <a href="/login">Iniciar sesión</a></p></form></motion.div></div><div className="saas-cta__banner"><div><h3>Conocé TOP en minutos</h3><p>Explorá una forma más clara de organizar reservas, recursos y huéspedes.</p></div><a href="/signup">Empezar a explorar</a></div>
  </div></section>;
}
