import { CheckCircle2 } from "lucide-react";
import { useState } from "react";

type Tier = { title: string; currency: string; amount: string; period: string; description: string; popular?: boolean };
const planTabs: Record<string, { label: string; tiers: Tier[] }> = {
  inicial: { label: "Inicial", tiers: [{ title: "Mensual", currency: "₲", amount: "0", period: "por alojamiento", description: "Para conocer la operación" }, { title: "Trimestral", currency: "₲", amount: "0", period: "por alojamiento", description: "La opción más elegida", popular: true }, { title: "Anual", currency: "₲", amount: "0", period: "por alojamiento", description: "Para planificar con calma" }] },
  profesional: { label: "Profesional", tiers: [{ title: "Mensual", currency: "₲", amount: "—", period: "por alojamiento", description: "Próximamente" }, { title: "Trimestral", currency: "₲", amount: "—", period: "por alojamiento", description: "Próximamente", popular: true }, { title: "Anual", currency: "₲", amount: "—", period: "por alojamiento", description: "Próximamente" }] },
};
const features = [["Reservas centralizadas", "Una vista clara para cada llegada, estadía y salida."], ["Disponibilidad", "Consultá recursos libres y ocupados sin perder contexto."], ["Precios y temporadas", "Organizá tarifas que acompañen la realidad de tu alojamiento."], ["Contactos de huéspedes", "Mantené la información operativa a mano y ordenada."], ["Roles del equipo", "Cada persona ve lo que necesita para trabajar mejor."], ["Historial operativo", "Conservá los cambios importantes y las decisiones tomadas."], ["Bloqueos", "Protegé recursos fuera de servicio o reservados para otro uso."], ["Ingresos", "Leé el movimiento del alojamiento desde una base consistente."], ["Acompañamiento TOP", "Una experiencia pensada para equipos pequeños."]];

export function SaasLaunchPricing() {
  const [activeTab, setActiveTab] = useState("inicial");
  const activePlan = planTabs[activeTab];
  return <section className="saas-section saas-pricing" id="pricing" aria-labelledby="saas-pricing-title"><header className="saas-centered-heading"><span className="saas-pricing__badge">Planes de referencia</span><h2 id="saas-pricing-title">Simple, predecible y alineado a tu operación.</h2></header><div className="saas-tabs" role="tablist" aria-label="Planes de TOP">{Object.entries(planTabs).map(([id, tab]) => <button key={id} type="button" role="tab" id={`pricing-tab-${id}`} aria-selected={activeTab === id} aria-controls={`pricing-panel-${id}`} onClick={() => setActiveTab(id)}>{tab.label}</button>)}</div><div id={`pricing-panel-${activeTab}`} className="saas-pricing__tiers" role="tabpanel" aria-labelledby={`pricing-tab-${activeTab}`}>{activePlan.tiers.map((tier) => <article className={tier.popular ? "saas-price-card is-popular" : "saas-price-card"} key={tier.title}><div className="saas-price-card__inner"><div className="saas-price-card__heading"><h3>{tier.title}</h3>{tier.popular ? <span>Más elegido</span> : null}</div><div className="saas-price-card__amount"><span>{tier.currency}</span><strong>{tier.amount}</strong></div><div className="saas-price-card__period">{tier.period}</div><p>{tier.description}</p></div></article>)}</div><div className="saas-pricing__features">{features.map(([title, description]) => <div className="saas-pricing__feature" key={title}><CheckCircle2 size={19} aria-hidden="true" /><p><strong>{title}:</strong> {description}</p></div>)}</div></section>;
}
