import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useEffect, useRef, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { ApiError, ApiResponseError, ApiTransportError } from "../../../shared/api/api-client";
import { registerPayment } from "../api/register-payment";
import { clearPaymentAttempt, readPaymentAttempt, writePaymentAttempt, type PaymentAttempt } from "../storage/payment-attempt-storage";
import type { PaymentMethod, RegisterPaymentPayload } from "../types/payment.types";

const methods = ["CASH", "BANK_TRANSFER", "CARD", "OTHER"] as const;
const schema = z.object({ amountMinor: z.coerce.number().int("El monto debe ser un entero.").positive("El monto debe ser mayor que cero.").refine(Number.isSafeInteger, "El monto es demasiado grande."), method: z.enum(methods), paidAt: z.string().min(1, "Indicá la fecha y hora."), reference: z.string().max(120, "Máximo 120 caracteres."), note: z.string().max(500, "Máximo 500 caracteres.") });
type Values = z.input<typeof schema>;
interface Props { userId?: string; businessId: string; bookingId: string; accessToken?: string | null; timezone: string; enabled: boolean; canRecord: boolean; bookingStatus?: string; currency?: string; }
function normalized(values: z.output<typeof schema>): RegisterPaymentPayload {
  const reference = values.reference.trim(); const note = values.note.trim();
  return { amountMinor: values.amountMinor, method: values.method as PaymentMethod, paidAt: "", ...(reference ? { reference } : {}), ...(note ? { note } : {}) };
}
function localBusinessInstant(value: string, timezone: string): string {
  const match = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})$/.exec(value); if (!match) throw new Error("Indicá una fecha y hora válida.");
  const wanted = match.slice(1).map(Number); const utc = Date.UTC(wanted[0], wanted[1] - 1, wanted[2], wanted[3], wanted[4]);
  const formatter = new Intl.DateTimeFormat("en-CA", { timeZone: timezone, year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" });
  for (let offset = -840; offset <= 840; offset += 15) { const candidate = new Date(utc - offset * 60_000); const parts = Object.fromEntries(formatter.formatToParts(candidate).filter((part) => part.type !== "literal").map((part) => [part.type, part.value])); if ([parts.year, parts.month, parts.day, parts.hour, parts.minute].map(Number).every((part, index) => part === wanted[index])) return candidate.toISOString(); }
  throw new Error("La hora no existe en la zona horaria del negocio.");
}
function businessLocal(value: string, timezone: string) { const parts = Object.fromEntries(new Intl.DateTimeFormat("en-CA", { timeZone: timezone, year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(new Date(value)).filter((part) => part.type !== "literal").map((part) => [part.type, part.value])); return `${parts.year}-${parts.month}-${parts.day}T${parts.hour}:${parts.minute}`; }
function newKey() { return globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random()}`; }
function isUncertain(error: unknown) { return error instanceof ApiTransportError || error instanceof ApiResponseError || error instanceof ApiError && error.status >= 500; }

export function RegisterPaymentForm(props: Props) {
  const queryClient = useQueryClient(); const sending = useRef(false); const controller = useRef<AbortController | null>(null); const context = useRef(`${props.userId}:${props.accessToken}:${props.businessId}:${props.bookingId}`); const [attempt, setAttempt] = useState<PaymentAttempt | null>(null); const [message, setMessage] = useState<string | null>(null);
  const form = useForm<Values>({ resolver: zodResolver(schema), defaultValues: { amountMinor: "" as unknown as number, method: "CASH", paidAt: "", reference: "", note: "" } });
  useEffect(() => { controller.current?.abort(); context.current = `${props.userId}:${props.accessToken}:${props.businessId}:${props.bookingId}`; setMessage(null); const stored = props.userId ? readPaymentAttempt(props.userId, props.businessId, props.bookingId) : null; setAttempt(stored); form.reset(stored ? { ...stored.payload, paidAt: businessLocal(stored.payload.paidAt, props.timezone), reference: stored.payload.reference ?? "", note: stored.payload.note ?? "" } : { amountMinor: "" as unknown as number, method: "CASH", paidAt: "", reference: "", note: "" }); return () => controller.current?.abort(); }, [props.userId, props.accessToken, props.businessId, props.bookingId, props.timezone, form]);
  const mutation = useMutation({ mutationFn: (next: PaymentAttempt) => registerPayment({ ...next, accessToken: props.accessToken, signal: controller.current?.signal }), retry: false });
  const eligible = props.enabled && Boolean(props.userId && props.accessToken && props.canRecord && props.currency && ["CONFIRMED", "IN_PROGRESS", "COMPLETED"].includes(props.bookingStatus ?? ""));
  async function send(next: PaymentAttempt) {
    if (sending.current) return; sending.current = true; setMessage(null);
    controller.current = new AbortController(); const operationContext = `${next.userId}:${props.accessToken}:${next.businessId}:${next.bookingId}`;
    try { await mutation.mutateAsync(next); if (context.current !== operationContext) return; const current = readPaymentAttempt(next.userId, next.businessId, next.bookingId); if (current?.idempotencyKey === next.idempotencyKey) clearPaymentAttempt(next.userId, next.businessId, next.bookingId); setAttempt(null); form.reset(); setMessage("Pago registrado."); void queryClient.invalidateQueries({ queryKey: ["outstanding-balance", next.userId, next.businessId, next.bookingId] }); void queryClient.invalidateQueries({ queryKey: ["payment-history", next.userId, next.businessId, next.bookingId] }); void queryClient.invalidateQueries({ queryKey: ["payment-plan", next.businessId] }); void queryClient.invalidateQueries({ queryKey: ["dashboard", next.businessId] }); }
    catch (error) { if (context.current !== operationContext) return; setAttempt(next); setMessage(isUncertain(error) || controller.current?.signal.aborted ? "No pudimos confirmar el registro. Verificá el pago antes de recuperarlo." : error instanceof Error ? error.message : "No pudimos registrar el pago."); }
    finally { sending.current = false; }
  }
  async function submit(values: Values) { if (!props.userId || sending.current) return; if (attempt) { await send(attempt); return; } if (!eligible) return; let payload: RegisterPaymentPayload; try { const parsed = schema.parse(values); payload = { ...normalized(parsed), paidAt: localBusinessInstant(parsed.paidAt, props.timezone) }; if (new Date(payload.paidAt) > new Date()) throw new Error("La fecha y hora no puede estar en el futuro."); } catch (error) { form.setError("paidAt", { message: error instanceof Error ? error.message : "Fecha inválida." }); return; } const next = { version: 1 as const, idempotencyKey: newKey(), userId: props.userId, businessId: props.businessId, bookingId: props.bookingId, payload }; if (!writePaymentAttempt(next)) { setMessage("No pudimos preparar un registro recuperable. No se envió el pago."); return; } await send(next); }
  if (!eligible) return <p className="booking-payments__unavailable" role="status">El registro de pagos no está disponible para esta reserva o tu perfil.</p>;
  const frozen = mutation.isPending || Boolean(attempt); return <section className="booking-payments__register" aria-labelledby="payment-register-title"><h3 id="payment-register-title">Registrar pago</h3><p>Moneda contractual: <strong>{props.currency}</strong>. La fecha y hora se interpretan en la zona del negocio: {props.timezone}.</p><form onSubmit={form.handleSubmit(submit)} noValidate><label>Monto (unidades menores)<input aria-invalid={!!form.formState.errors.amountMinor} inputMode="numeric" disabled={frozen} {...form.register("amountMinor")} /></label>{form.formState.errors.amountMinor && <p role="alert">{form.formState.errors.amountMinor.message}</p>}<label>Método<select disabled={frozen} {...form.register("method")}>{methods.map((method) => <option key={method} value={method}>{method}</option>)}</select></label><label>Fecha y hora<input type="datetime-local" disabled={frozen} {...form.register("paidAt")} /></label>{form.formState.errors.paidAt && <p role="alert">{form.formState.errors.paidAt.message}</p>}<label>Referencia<input aria-invalid={!!form.formState.errors.reference} disabled={frozen} {...form.register("reference")} /></label>{form.formState.errors.reference && <p role="alert">{form.formState.errors.reference.message}</p>}<label>Nota<textarea aria-invalid={!!form.formState.errors.note} disabled={frozen} {...form.register("note")} /></label>{form.formState.errors.note && <p role="alert">{form.formState.errors.note.message}</p>}<button type="submit" className="top-button" disabled={mutation.isPending}>{mutation.isPending ? "Registrando..." : attempt ? "Recuperar el mismo intento" : "Registrar pago"}</button></form>{message && <p role={message === "Pago registrado." ? "status" : "alert"} aria-live="polite">{message}</p>}<p className="booking-payments__attempt-note">Cerrar sesión o la pestaña puede impedir recuperar este intento. Verificá el pago antes de registrarlo nuevamente.</p></section>;
}
