import { BadRequestException, Body, ConflictException, Controller, Get, HttpCode, HttpStatus, NotFoundException, Param, Patch, Post } from '@nestjs/common';
import { ApiBadRequestResponse, ApiConflictResponse, ApiCreatedResponse, ApiNotFoundResponse, ApiOkResponse, ApiOperation, ApiTags } from '@nestjs/swagger';
import { CreateRatePlanUseCase, InvalidRatePlanInputError, RatePlanBusinessArchivedError, RatePlanBusinessNotFoundError, RatePlanResourceArchivedError, RatePlanResourceNotFoundError } from '../application/create-rate-plan.use-case';
import { CreateSeasonalRateUseCase } from '../application/create-seasonal-rate.use-case';
import { ListSeasonalRatesUseCase } from '../application/list-seasonal-rates.use-case';
import { InvalidSeasonalRateInputError, SeasonalRateBusinessArchivedError, SeasonalRateBusinessNotFoundError, SeasonalRateOverlapError, SeasonalRatePlanArchivedError, SeasonalRatePlanNotFoundError, SeasonalRateValidityConflictError } from '../application/seasonal-rate.errors';
import { RatePlanArchivedError, RatePlanNotFoundError, UpdateRatePlanUseCase } from '../application/update-rate-plan.use-case';
import { CreateRatePlanRequestDto } from './dto/create-rate-plan.request.dto'; import { CreateSeasonalRateRequestDto } from './dto/create-seasonal-rate.request.dto'; import { RatePlanResponseDto } from './dto/rate-plan.response.dto'; import { SeasonalRateResponseDto } from './dto/seasonal-rate.response.dto'; import { UpdateRatePlanRequestDto } from './dto/update-rate-plan.request.dto';
const isNotFound=(e:unknown)=>e instanceof RatePlanBusinessNotFoundError||e instanceof RatePlanResourceNotFoundError||e instanceof RatePlanNotFoundError||e instanceof SeasonalRateBusinessNotFoundError||e instanceof SeasonalRatePlanNotFoundError;
const isConflict=(e:unknown)=>e instanceof RatePlanBusinessArchivedError||e instanceof RatePlanResourceArchivedError||e instanceof RatePlanArchivedError||e instanceof SeasonalRateBusinessArchivedError||e instanceof SeasonalRatePlanArchivedError||e instanceof SeasonalRateValidityConflictError||e instanceof SeasonalRateOverlapError;
@ApiTags('Pricing') @Controller('businesses/:businessId/rate-plans') export class PricingController { constructor(private readonly createRatePlan:CreateRatePlanUseCase,private readonly updateRatePlan:UpdateRatePlanUseCase,private readonly createSeasonalRate:CreateSeasonalRateUseCase,private readonly listSeasonalRates:ListSeasonalRatesUseCase){} @Post() @HttpCode(HttpStatus.CREATED) @ApiOperation({summary:'Creates an active rate plan with an optional resource assignment.'}) @ApiCreatedResponse({type:RatePlanResponseDto}) @ApiBadRequestResponse() @ApiNotFoundResponse() @ApiConflictResponse() async create(@Param('businessId') businessId:string,@Body() body:CreateRatePlanRequestDto):Promise<RatePlanResponseDto>{try{return RatePlanResponseDto.fromDomain(await this.createRatePlan.execute({businessId,...body}));}catch(error){throw this.mapError(error);}} @Post(':ratePlanId/seasonal-rates') @HttpCode(HttpStatus.CREATED) @ApiOperation({summary:'Creates a seasonal price rule for an active rate plan.'}) @ApiCreatedResponse({type:SeasonalRateResponseDto}) @ApiBadRequestResponse() @ApiNotFoundResponse() @ApiConflictResponse() async createSeason(@Param('businessId') businessId:string,@Param('ratePlanId') ratePlanId:string,@Body() body:CreateSeasonalRateRequestDto):Promise<SeasonalRateResponseDto>{try{return SeasonalRateResponseDto.fromDomain(await this.createSeasonalRate.execute({businessId,ratePlanId,...body}));}catch(error){throw this.mapError(error);}} @Get(':ratePlanId/seasonal-rates') @ApiOperation({summary:'Lists seasonal price rules in deterministic date order.'}) @ApiOkResponse({type:[SeasonalRateResponseDto]}) @ApiBadRequestResponse() @ApiNotFoundResponse() async listSeasons(@Param('businessId') businessId:string,@Param('ratePlanId') ratePlanId:string):Promise<SeasonalRateResponseDto[]>{try{return (await this.listSeasonalRates.execute(businessId,ratePlanId)).map(rate=>SeasonalRateResponseDto.fromDomain(rate));}catch(error){throw this.mapError(error);}} @Patch(':ratePlanId') @ApiOperation({summary:'Updates an active rate plan partially.'}) @ApiOkResponse({type:RatePlanResponseDto}) async update(@Param('businessId') businessId:string,@Param('ratePlanId') ratePlanId:string,@Body() body:UpdateRatePlanRequestDto):Promise<RatePlanResponseDto>{try{return RatePlanResponseDto.fromDomain(await this.updateRatePlan.execute({businessId,ratePlanId,...body}));}catch(error){throw this.mapError(error);}} private mapError(error:unknown):Error {if(error instanceof InvalidRatePlanInputError||error instanceof InvalidSeasonalRateInputError)return new BadRequestException(error.message);if(isNotFound(error))return new NotFoundException(error.message);if(isConflict(error))return new ConflictException(error.message);return error instanceof Error?error:new Error('Error inesperado.');} }
