import type { FinanceV2IntegrationConfiguration } from "../v2/FinanceV2Bridge";
// Propuesta opt-in: root copia sólo tras validar los gates y las rutas de la matriz.
// OWNER y los permisos del servidor siguen siendo obligatorios para cada operación.
export const FINANCE_V2_INTEGRATION: FinanceV2IntegrationConfiguration = {
  capabilities: [
    "finance.read",
    "finance.write",
    "finance.export",
    "finance.import",
    "finance.planning",
    "finance.approve",
    "finance.labor",
    "booking.read",
    "payment.void",
    "payment.refund",
    "pricing.final-amount",
    "finance.evidence.read",
    "finance.evidence.write"
  ],
  availableSections: [
    "drafts",
    "templates",
    "approval-policy",
    "budget",
    "budget-comparison",
    "commitments",
    "bank-match-sources",
    "bank-statements",
    "bank-matches",
    "allocation-rules",
    "labor-costs",
    "costs",
    "resource-results",
    "aging",
    "alerts",
    "commands",
    "history-preview",
    "bank-preview",
    "bank-match-preview",
    "planning-preview",
    "booking-choices",
    "recognition-sources",
    "service-certificates",
    "terminal-recognitions",
    "booking-result",
    "corrections",
    "payment-adjustments",
    "terminal-pricing",
    "periods",
    "period-close",
    "period-reopen",
    "period-snapshot",
    "period-package",
    "expense-evidence"
  ],
};
