import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {cleanup,render,screen,waitFor,within} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {StrictMode} from 'react';
import {MemoryRouter} from 'react-router-dom';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import * as auth from '../../auth/context/AuthContext';
import * as business from '../../business/context/BusinessContext';
import {FinancePage} from './FinancePage';
import {financeFixture} from './finance.fixture';
import {getFinanceReport} from '../api/finance-api';
import type {FinancePayment,FinanceReport} from '../types/finance.types';
import {formatMoney} from '../../../shared/utils/money';
const paymentId='da6313a0-1508-4ba2-b85f-c82f684c4b93';const adjustmentId='da6313a0-1508-4ba2-b85f-c82f684c4b94';
const json=(value:unknown)=>new Response(JSON.stringify(value),{headers:{'Content-Type':'application/json'}});
const clients:QueryClient[]=[];
function mount(report:FinanceReport){const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});clients.push(client);return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[`/app/finance?from=${report.from}&to=${report.to}`]}><StrictMode><FinancePage/></StrictMode></MemoryRouter></QueryClientProvider>);}
beforeEach(()=>{vi.spyOn(auth,'useAuth').mockReturnValue({status:'authenticated',isAuthenticated:true,isLoggingOut:false,establishSession:vi.fn(),updateUserProfile:vi.fn(),logout:async()=>undefined,session:{user:{id:'owner-a',email:'owner@example.test',status:'ACTIVE'},accessToken:'synthetic-token',refreshToken:'synthetic-refresh',tokenType:'Bearer',expiresIn:900,memberships:[{businessId:'synthetic-a',role:'OWNER'}]}});vi.spyOn(business,'useBusinessContext').mockReturnValue({activeBusinessId:'synthetic-a',activeRole:'OWNER',activeMembership:{businessId:'synthetic-a',role:'OWNER'},activeBusiness:{id:'synthetic-a',name:'Negocio Cash QA',currency:'PYG',timezone:'America/Asuncion',status:'ACTIVE',legalName:null,taxId:null,createdAt:'2026-09-01T00:00:00.000Z',updatedAt:'2026-09-01T00:00:00.000Z'},businesses:[],status:'ready',error:null,selectBusiness:vi.fn(),retry:vi.fn()});});
afterEach(()=>{cleanup();clients.splice(0).forEach((client)=>client.clear());vi.restoreAllMocks();vi.unstubAllGlobals();});
function voidReport(){const report=financeFixture();const payment:FinancePayment={...report.payments[0],id:paymentId,amountMinor:1000000,accountId:'account-a',version:1,paymentVersion:2,effectiveStatus:'VOIDED',grossRecordedAmountMinor:1000000,voidedAmountMinor:1000000,refundedAmountMinor:0,netRetainedAmountMinor:0,includedInBalance:true};report.payments=[payment];report.totals={...report.totals,paymentsMinor:1000000,grossRecordedAmountMinor:1000000,voidedAmountMinor:1000000,refundedAmountMinor:0,netRecordedReceiptFlowMinor:0,paymentNetRetainedAmountMinor:0,unassignedPaymentsMinor:0};const receipt={id:paymentId,sourceType:'PAYMENT' as const,sourceId:paymentId,sourceVersion:2,accountId:'account-a',amountMinor:1000000,occurredAt:payment.paidAt,description:'Cobro original QA',includedInBalance:true,reviewed:false,reviewVersion:0,reviewStale:false,bookingId:payment.bookingId,paymentId};const reversal={...receipt,id:adjustmentId,sourceType:'VOID' as const,sourceId:adjustmentId,amountMinor:-1000000,description:'Cobro anulado QA'};report.movements=[...report.movements,receipt,reversal];report.balanceSources=[...report.balanceSources,receipt,reversal];return report;}
it('VOID conserva bruto1M y cuatro importes/estado del servidor; flujo y retenido0 no borran el original',async()=>{const report=voidReport();vi.stubGlobal('fetch',vi.fn().mockResolvedValue(json(report)));const user=userEvent.setup();mount(report);expect(await screen.findByRole('button',{name:/Cobros brutos registrados del período/})).toHaveTextContent(formatMoney(1000000));expect(screen.getByRole('button',{name:/Cobros anulados del período original/})).toHaveTextContent(formatMoney(1000000));expect(screen.getByRole('button',{name:/Flujo neto de cobros del período/})).toHaveTextContent(formatMoney(0));await user.click(screen.getByRole('button',{name:'Cobros'}));const row=document.querySelector('.finance-payment-row')!;expect(within(row as HTMLElement).getByText(/Estado: Anulado/)).toBeInTheDocument();for(const label of ['Bruto registrado','Anulado','Devuelto hasta el corte','Neto retenido al corte'])expect(within(row as HTMLElement).getByText(label)).toBeInTheDocument();expect(within(row as HTMLElement).getByText('Neto retenido al corte').nextElementSibling).toHaveTextContent(formatMoney(0));expect(report.payments[0].amountMinor).toBe(1000000);});
it('drilldown VOID usa UUID del ajuste, muestra actor/motivo reales del endpoint y enlaza el cobro original',async()=>{const report=voidReport();const fetch=vi.fn(async(url:string)=>json(url.includes(`/audit/VOID/${adjustmentId}`)?[{id:'audit-owned',action:'VOID_PAYMENT',sourceId:adjustmentId,actorUserId:'actual-test-actor',occurredAt:'2026-10-05T12:00:00.000Z',details:{command:{reason:'Registro erróneo declarado'}}}]:report));vi.stubGlobal('fetch',fetch);const user=userEvent.setup();mount(report);await user.click(await screen.findByRole('button',{name:/Saldo registrado al corte/}));await user.click(screen.getByRole('button',{name:'Ver origen del saldo'}));const balance=screen.getByRole('dialog',{name:'Origen del saldo registrado'});expect(within(balance).getByText('Reverso de cobro')).toBeInTheDocument();await user.click(within(balance).getAllByRole('button',{name:'Ver origen e historial'}).at(-1)!);const source=screen.getByRole('dialog',{name:'Origen e historial del movimiento'});expect(await within(source).findByText(/actual-test-actor/)).toBeInTheDocument();expect(within(source).getByText('Anulación de cobro')).toBeInTheDocument();expect(within(source).getByText(/Registro erróneo declarado/)).toBeInTheDocument();expect(within(source).getByRole('link',{name:'Abrir cobro original de la reserva'})).toHaveAttribute('href','/app/bookings/booking-a/payments');expect(fetch.mock.calls.some(([url])=>url.includes(`/audit/VOID/${adjustmentId}`))).toBe(true);});
it('refund de cobro anterior produce flujo firmado negativo del período y cohorte0, sin atribuir ingreso nuevo',async()=>{const report=financeFixture();report.from='2026-10-01';report.to='2026-11-01';report.payments=[];report.expenses=[];report.movements=[{id:adjustmentId,sourceType:'REFUND',sourceId:adjustmentId,sourceVersion:2,accountId:'account-a',amountMinor:-200000,occurredAt:'2026-10-05T12:00:00.000Z',description:'Devolución de cobro de septiembre',includedInBalance:true,reviewed:false,reviewVersion:0,reviewStale:false,bookingId:'booking-a',paymentId}];report.totals={...report.totals,paymentsMinor:0,grossRecordedAmountMinor:0,voidedAmountMinor:0,refundedAmountMinor:200000,netRecordedReceiptFlowMinor:-200000,paymentNetRetainedAmountMinor:0,unassignedPaymentsMinor:0,expenseMinor:0,outstandingMinor:0};vi.stubGlobal('fetch',vi.fn().mockResolvedValue(json(report)));const user=userEvent.setup();mount(report);expect(await screen.findByRole('button',{name:/Flujo neto de cobros del período/})).toHaveTextContent(formatMoney(-200000));expect(screen.getByRole('button',{name:/Neto retenido de los cobros del período/})).toHaveTextContent(formatMoney(0));expect(screen.getByRole('button',{name:/Devoluciones realizadas en el período/})).toHaveTextContent(formatMoney(200000));await user.click(screen.getByRole('button',{name:'Movimientos y arqueos'}));expect(screen.getByText('Devolución de cobro de septiembre')).toBeInTheDocument();expect(screen.getByText(/Devolución externa.*versión 2/)).toBeInTheDocument();});
it('lector acepta flujo negativo explícito y rechaza nuevos importes/status ausentes o inválidos',async()=>{const report=financeFixture();report.totals.netRecordedReceiptFlowMinor=-200000;const fetch=vi.fn().mockResolvedValueOnce(json(report)).mockResolvedValueOnce(json({...report,totals:{...report.totals,paymentNetRetainedAmountMinor:undefined}})).mockResolvedValueOnce(json({...report,payments:[{...report.payments[0],effectiveStatus:'UNKNOWN'}]}));vi.stubGlobal('fetch',fetch);const context={businessId:'synthetic-a',userId:'owner-a',accessToken:'synthetic-token'};await expect(getFinanceReport(context,{from:report.from,to:report.to})).resolves.toEqual(report);await expect(getFinanceReport(context,{from:report.from,to:report.to})).rejects.toMatchObject({name:'ApiResponseError'});await expect(getFinanceReport(context,{from:report.from,to:report.to})).rejects.toMatchObject({name:'ApiResponseError'});});
it('exporta CSV exacto servidor con token de este reporte, incluidos VOID/REFUND sin recomputar el flujo',async()=>{const report=voidReport();const csv='source_type,amount_minor\r\nPAYMENT,1000000\r\nVOID,-1000000\r\nREFUND,-200000\r\n';const fetch=vi.fn(async(url:string)=>url.includes('/finance/export?')?new Response(csv,{headers:{'Content-Type':'text/csv'}}):json(report));vi.stubGlobal('fetch',fetch);const create=vi.fn().mockReturnValue('blob:cash-report-owned');vi.spyOn(URL,'createObjectURL').mockImplementation(create);vi.spyOn(URL,'revokeObjectURL').mockImplementation(()=>undefined);vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>undefined);const user=userEvent.setup();mount(report);await user.click(await screen.findByRole('button',{name:'Exportar este reporte'}));await waitFor(()=>expect(create).toHaveBeenCalledOnce());const contents=await new Promise<string>((resolve)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.readAsText(create.mock.calls[0][0]);});expect(contents).toBe(csv);const request=fetch.mock.calls.find(([url])=>url.includes('/finance/export?'))!;const url=new URL(request[0]);expect(url.searchParams.get('token')).toBe(report.token);expect(url.searchParams.get('from')).toBe(report.from);expect(url.searchParams.get('to')).toBe(report.to);});
